### ISSUE TITLE
Finer grained control over logging verbosity

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#10]
We globally set the loglevel in cocotb.**init**.py:

> log.setLevel(logging.INFO)

We've split the messages hierarchically using the standard python logging mechanism.  It would be useful to provide and document a more convenient way to set up, for example all of the following can be different verbosity:

scheduler
drivers
monitors
scoreboard
coroutines

**Comment by ktbarrett** [comment]
This can be accomplished using the standard Python logging facilities now.

For example:
```python
import logging
logging.getLogger("cocotb.regression").setLevel(logging.WARNING)
```
