### ISSUE TITLE
fprintf messages in C code do not give context

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1017]
I got the error "FATAL: We are calling up again" (while investigating #1014) but nothing hinted at this being a message from cocotb, much less any additional context like file name or line number.
We should at least start such strings with "cocotb: ".

**Comment by eric-wieser** [comment]
I think this is because it did not come from cocotb, but from within the simulator. My guess is that writing a signal with no delay causes the edge event to fire on the same internal tick.

**Comment by cmarqu** [comment]
This specific string comes fromhttps://github.com/potentialventures/cocotb/blob/a8765a6c6e41acb3e7c09fc61d5514cdd8d86608/cocotb/share/lib/utils/cocotb_utils.c though.

**Comment by cmarqu** [comment]
Should we just prefix "cocotb: " here (for the rare cases where such messages are actually printed), or is there an easy way of hooking this up into some logging mechanisms that provides context?
