### ISSUE TITLE
PyPi deployment not working

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#1046]
"Skipping a deployment with the pypi provider because this branch is not permitted: v1.2.0"

https://travis-ci.org/cocotb/cocotb/jobs/563023042

@themperek do you know what's going on here? Can you manually upload a package to PyPi to get this release out of the door?

**Comment by themperek** [comment]
Will check/do asap (in few hours)

**Comment by themperek** [comment]
Seems like "on: tag" is necessary (i have checked few version on my private Travis).

Best would be to change remove "on: tag" realise/tag and do it one more time.
Should I do PR?

**Comment by imphil** [comment]
We can try the automation for the next release, but this release is tagged and pushed, we cannot re-tag it.

**Comment by themperek** [comment]
Uploaded: https://pypi.org/project/cocotb/
