### ISSUE TITLE
= vs := in Makefile.questa

### ISSUE THREAD

**Issue by ashmanskas** [cocotb/cocotb#1057]
I found today, when simulating with questa a design that we had previously simulated with Cadence ius, that I needed to replace "=" with ":=" in the VLOG_ARGS assignment in Makefile.questa.  Before this one-character Makefile.questa edit, I had encountered the error message: "Recursive variable `VLOG_ARGS' references itself (eventually).  Stop".

Is this a change whose motivation is obvious to Makefile aficionados, or shall I document the specific circumstances of the failure more carefully?

(Only tangentially related, FWIW, yesterday I ran the whole cocotb 1.2.0 test suite with questa 10.7 and found that 129 tests passed and 8 failed.  (No change to Makefile.questa was needed.)  I paste in at the bottom the 8 failing tests.)

----

ashmansk@lxhiggs:cocotb$ git diff | cat
diff --git a/cocotb/share/makefiles/simulators/Makefile.questa b/cocotb/share/makefiles/simulators/Makefile.questa
index f25b472..ed3e8c9 100644
--- a/cocotb/share/makefiles/simulators/Makefile.questa
+++ b/cocotb/share/makefiles/simulators/Makefile.questa
@@ -48,9 +48,9 @@ RTL_LIBRARY ?= work
 TOPLEVEL := "$(RTL_LIBRARY).$(TOPLEVEL)"
 
 ifdef VLOG_ARGS
-VLOG_ARGS = $(VLOG_ARGS)
+VLOG_ARGS := $(VLOG_ARGS)
 else
-VLOG_ARGS = -timescale 1ns/100ps -mfcu +acc=rmb
+VLOG_ARGS := -timescale 1ns/100ps -mfcu +acc=rmb
 endif
 ifdef VERILOG_INCLUDE_DIRS
 VLOG_ARGS += +incdir+$(VERILOG_INCLUDE_DIRS)
ashmansk@lxhiggs:cocotb$ 

----

ashmansk@lxhiggs:try_cocotb_120$ grep ' FAIL ' run_cocotb_regression_questa.log | cut -c120-
** test_closedown.test_failure_from_system_task    FAIL            1.06          0.00       352.49  **
** test_discovery.access_var_string_verilog         FAIL            0.02          0.00        30.26  **
** test_iteration.test_drivers                    FAIL           10.10          0.00      3561.07  **
** test_iteration.recursive_discovery       FAIL          101.00          5.90        17.11  **
** test_cocotb_array.test_in_2d_arr_unpacked                    FAIL            1.10          0.00       803.09  **
** test_cocotb_array.test_in_arr_packed_unpacked                FAIL            1.10          0.00      1732.53  **
** test_cocotb_array.test_in_vect_packed_packed_unpacked        FAIL            1.10          0.00      1718.98  **
** plusargs.plusargs_test    FAIL         1000.10          0.00    879396.95  **
ashmansk@lxhiggs:try_cocotb_120$ 

----

**Comment by nevsan** [comment]
```Makefile
ifdef VLOG_ARGS
VLOG_ARGS = $(VLOG_ARGS)
else
VLOG_ARGS = -timescale 1ns/100ps -mfcu +acc=rmb
endif
```
The first `if` statement doesn't make any sense (assigning `VLOG_ARGS` to itself without anything else to add to the mix--if you did want to add something, just use `+=`). Just delete `VLOG_ARGS = $(VLOG_ARGS)` and all should be good.

In general, for make variables that are designed for users to append to, I like the keep them as recursive variables (see [Make Variable Flavors](https://www.gnu.org/software/make/manual/html_node/Flavors.html)), as users don't have to worry so much about altering them before or after the inclusion of your makefile (and in many cases, you can't get the desired behavior of letting the user override if you use the variable in a target or dependency definition).

Simply expanded variables have their performance advantages, but I don't think they really matter these days, so they are most appropriate for variables that need to be expanded often _and_ have significant costs with evaluating (like ones that use complex `shell` statements).
