### ISSUE TITLE
Hardcoded SIM_ARGS in test_iteration_vhdl

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1073]
c61e945f5315e19a408e535d3dc567269222c2b3 introduced https://github.com/cocotb/cocotb/commit/c61e945f5315e19a408e535d3dc567269222c2b3#diff-7f8f2afbf01273966c2300e863acd5d9R30 which sets a simulator-specific ``SIM_ARGS`` .
@cogsy23 could you e.g. wrap this with a simulator check please?

**Comment by eric-wieser** [comment]
xref #1052
