### ISSUE TITLE
Timer value argument is misleading 

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1115]
With the existence of the ``units`` argument, the value in ``Timer`` should not be ``time_ps`` (https://cocotb.readthedocs.io/en/latest/triggers.html?highlight=Timer#cocotb.triggers.Timer). 

How about ``value``?

**Comment by ktbarrett** [comment]
Regarding this and #1117. 

I don't even think the default units are picoseconds, but the simulator's timescale, which can change via flags to the simulator. Not using `units` is probably a bug/bug waiting to happen. Maybe a `DeprecationWarning` is appropriate.

**Comment by cmarqu** [comment]
Maybe we should even take the step and create ``SimTime`` as @imphil suggested in #872.

**Comment by ktbarrett** [comment]
I'd like something like `std::chrono::duration` for expressing sim time, I've run into the need for such a type on a few occassions.

**Comment by ktbarrett** [comment]
@garmin-mjames What is the request for 1.5 here? The rename, or the simulation time physical type I described?

**Comment by garmin-mjames** [comment]
A rename was my goal for 1.5.
Supporting a physical `time` type in Python would help #1233 as well.

**Comment by cmarqu** [comment]
https://stackoverflow.com/questions/49802412/how-to-implement-deprecation-in-python-with-argument-alias could be useful here

**Comment by ktbarrett** [comment]
The first part of the first solution would not be good for Sphinx, but the second part would work fine. I would introduce two special objects that would be helpful for showing the intended use.

```python
DEPRECATED = object()
REQUIRED = object()

def function(new_name=REQUIRED, *, old_name=DEPRECATED):
    # ... logic from answer 1 part 2 just replacing `None`, `None` might be a possible argument anyway, so we need a better sentinel
```
