### ISSUE TITLE
Cocotb doesn't work with Modelsim

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#112]
As title.

Issue opened primarily to track commits.  May be duplicate of issue #103.

**Comment by omkars3** [comment]
How to install modelsim in windows for cocotrb()through ming?

**Comment by omkars3** [comment]
How to install modelsim in windows for cocotrb(through ming)?

**Comment by imphil** [comment]
@omkars3 you replied in an old closed issue. Please open a new discussion if needed.
