### ISSUE TITLE
Cocotb logo

### ISSUE THREAD

**Issue by themperek** [cocotb/cocotb#1126]
Together with @cmarqu we made a logo proposition for cocotb. Would be nice to know your opinion and decide yes/now for this one or propose something else.
![logo8small](https://user-images.githubusercontent.com/4158544/65598660-3e9ed680-df9c-11e9-8869-e259a21f9908.png) 

| ![logo7___](https://user-images.githubusercontent.com/4158544/65598685-48283e80-df9c-11e9-9013-ab2ddb650bfa.png) | ![logo_wavey](https://user-images.githubusercontent.com/4158544/65669223-71e87080-e043-11e9-86e2-f7cb4f4a4b78.png) | ![logo_wavey2](https://user-images.githubusercontent.com/4158544/65681543-63a54f00-e059-11e9-92aa-4c0445bc55f5.png)
| -- | -- | -- |

(edited by @eric-wieser: Shink the text-less logos to make this thread easier to browse)

**Comment by imphil** [comment]
Can you explain the logo a bit? What does the symbol stand for?

**Comment by themperek** [comment]
Up to interpretation but for me is square waveform (clock) made out of python logo elements.

**Comment by tmeissner** [comment]
I like it. Maybe you could add a waveform in the image to clarify.

**Comment by eric-wieser** [comment]
Not a huge plan of the cut and paste approach from the python logo, but I like the concept.

**Comment by mgielda** [comment]
Hm, nice idea, but it is indeed a tad controversial with the cut and paste. What if we just had the text (cocotb in this font) for now? That would be a good first step as we discuss the symbol further. Otherwise we keep running into the problem of cocotb not having a logo ;)

**Comment by themperek** [comment]
Maybe this will be ok?

![logo_square](https://user-images.githubusercontent.com/4158544/70042591-70957000-15bf-11ea-9997-e8e1a9fd5f7d.png)

Or this (green wave is chasing red one ?)

![logo8_square_col](https://user-images.githubusercontent.com/4158544/70042763-bc481980-15bf-11ea-82db-0f6dde87af05.png)

**Comment by eric-wieser** [comment]
@themperek, what's the font in the first image?

Also, can you upload these as SVG to make it easier for others to edit and suggest changes to?

**Comment by themperek** [comment]
The font is: Neuropolitical

Files: https://uni-bonn.sciebo.de/s/pTbCDZEVyqeDZCr

**Comment by cmarqu** [comment]
I like the blue/yellow version for its clear reference to Python that is much less obvious in the green/red one.

**Comment by eric-wieser** [comment]
How's this?

![efw_logo](https://user-images.githubusercontent.com/425260/70046657-6030c580-15be-11ea-80d4-8bd9e357ebf3.png)


[logo_efw.zip](https://github.com/cocotb/cocotb/files/3916276/logo_efw.zip)

**Comment by cmarqu** [comment]
I'd say @themperek's last version has the advantage that it would work even in very small resolutions.

**Comment by themperek** [comment]
@eric-wieser We could make a poll https://github.com/apps/polls and wait for some time?

**Comment by eric-wieser** [comment]
@themperek: I thought about that exact tool, but it doesn't allow options to be added later - so perhaps we should wait a little longer for other options.

**Comment by themperek** [comment]
![image](https://user-images.githubusercontent.com/4158544/113607985-33753e00-964a-11eb-8fb2-44e2cc80c456.png)

**Comment by themperek** [comment]
![image](https://user-images.githubusercontent.com/4158544/113608922-72f05a00-964b-11eb-825e-bab4f7c84956.png)

**Comment by wallento** [comment]
I prefer the upper right I believe

**Comment by eric-wieser** [comment]
I'd be tempted to flip them left/right - waveforms usually grow to the right

**Comment by ktbarrett** [comment]
I agree with Eric. The top left or top middle but mirrored horizontally would like nice. Over or next to the "cocotb" in the Neuropolitical font as suggested earlier. For my course in lieu of a decision I actually used Eric's contribution.

**Comment by themperek** [comment]
![flip](https://user-images.githubusercontent.com/4158544/113770185-2166ce80-9722-11eb-8f14-b8228711ef06.png)

**Comment by ktbarrett** [comment]
I think I might like the one without eyes more, but I like both.

**Comment by themperek** [comment]
Can look for other/better font. Many free ones: https://www.dafont.com/

**Comment by eric-wieser** [comment]
I think the eyes look better when connected to the heads 😉 

![image](https://user-images.githubusercontent.com/425260/113775554-c84a6b00-9720-11eb-9bd2-7bd9de878c47.png)

**Comment by PackDevLab** [comment]
Hi! Here is a suggestion for new logo. 
The C is representing the testbench an the arrow representing the data flow. 
I have also suggested some different variations in color and finish.
 
![Cocotb C arrow big](https://user-images.githubusercontent.com/61089202/114089735-cc0ff600-98b6-11eb-889a-b53052f23798.png)
![Cocotb C arrow versions monochrome green](https://user-images.githubusercontent.com/61089202/114090142-548e9680-98b7-11eb-8716-3c45441f039d.png)
![Cocotb C arrow versions monochrome blue](https://user-images.githubusercontent.com/61089202/114090162-5b1d0e00-98b7-11eb-9a8c-04948dbab6a8.png)
![Cocotb C arrow versions](https://user-images.githubusercontent.com/61089202/114090176-5fe1c200-98b7-11eb-9858-68c9c28a4460.png)

**Comment by PackDevLab** [comment]
As a comment to the suggestions above; i believe the python snakes are to close to the original python logo, in all versions. As this is a rather conservative area, i have gone for a less playful style, but still trying to show a bit of creativity.

**Comment by themperek** [comment]
@PackDevLab Thank you!

What you think to make the first symbol look more like a flip-flop? Maybe this would give a bit more relation to electronics.

![ff](https://user-images.githubusercontent.com/4158544/114091426-f662b300-98b8-11eb-9fe8-67c0ef3215c4.png)

**Comment by eric-wieser** [comment]
> i believe the python snakes are to close to the original python logo, in all versions

For a good overview of how "snakey" other logos for python packages are, https://python3statement.org/#sections30-projects has a large collection of logos across popular packages.

**Comment by ktbarrett** [comment]
@PackDevLab 
> The C is representing the testbench an the arrow representing the data flow.

Could you explain that a bit more?

**Comment by eric-wieser** [comment]
![114089735-cc0ff600-98b6-11eb-889a-b53052f23798](https://user-images.githubusercontent.com/425260/114758646-1d0b6880-9d55-11eb-91ce-c4d8ff841438.png)

A possible variant of @PackDevLab's design, using the "C" to represent the input-output. Very rough

**Comment by themperek** [comment]
![image](https://user-images.githubusercontent.com/4158544/114758796-aaeb5180-9d5d-11eb-86aa-9605763a4d62.png)

**Comment by PackDevLab** [comment]
Here are some sketches based on previous comment. I also tried just adding colors as shadows to the "o"s .
I believe making the C look to much like a snake could be a bit too litteral, so my take on the resemblance to Python logo was to separate the blue and yellow in the same style as they do. The sketch doesnt show that correctly due to lack of time, but i thing you get the gist.  I used an "arrow" instead of snake to symbolize the flow.
![python_c](https://user-images.githubusercontent.com/61089202/115160378-228bea00-a098-11eb-9b7d-68cdd04e5500.png)
![Arrow_o](https://user-images.githubusercontent.com/61089202/115160380-2586da80-a098-11eb-9b08-c3271b94b228.png)
![color shodow](https://user-images.githubusercontent.com/61089202/115160384-291a6180-a098-11eb-8038-63bc46040745.png)

**Comment by wallento** [comment]
For the first one, there could be an "icon" version with the two arrows only then, which I always like.

**Comment by marlonjames** [comment]
Playing with the chip idea. I used gold/yellow for the input, as in "golden" stimulus/reference.

![cocotb_logo_1](https://user-images.githubusercontent.com/47790688/115169742-bdbe9880-a073-11eb-9125-79cf37b48199.png)

**Comment by alexforencich** [comment]
I think we also need a mascot of some sort, perhaps named "coco".

**Comment by ktbarrett** [comment]
> perhaps named "coco".

![Forgive my nostalgia](https://user-images.githubusercontent.com/22162772/115187066-55d67500-a0a8-11eb-9dba-6c840ef5d0ff.png).

**Comment by PackDevLab** [comment]
I absolutely love the yellow/blue with chip "o",  without an outline. 
I also absolutely love Coco but that might be to intrusive and also associating to Crash might be contra productive ;)

**Comment by imphil** [comment]
@marlonjames The arrow and the chip look good to me. The font I don't like at all honestly, it reminds me of a free font that tries to look playful, but just doesn't get the balance between rounded and rectangular right.

**Comment by eric-wieser** [comment]
I think the arrow looks much better the way @marlonjames draws it with the endpoints rather than the center aligning with the center of the "o" - the way I had it makes it harder to read as a "c"

**Comment by marlonjames** [comment]
@imphil I think any nice font with a "rounded rectangle" style would work.
For the arrows I started with a larger sized capital `C` so the rounded corners matched.

**Comment by marlonjames** [comment]
Are any of these appealing?
https://www.fontsc.com/font/tag/rounded-square?pt=Cocotb&ps=2&o=1&ls=50&co=1

**Comment by eric-wieser** [comment]
I quite like "Anita semi-square" (ignoring the odd kerning the `tb` looks interesting) and "Play" (the o looks somewhat chip-shaped already).

**Comment by marlonjames** [comment]
Here's with the **Play** font.

![cocotb_logo_3_play](https://user-images.githubusercontent.com/47790688/115289618-a335ff00-a107-11eb-8e52-971ca90d6b2f.png)

**Comment by imphil** [comment]
Cocotb now has a logo, which will be revealed as part of a web site launch in the coming months. Thank you all for your input!
