### ISSUE TITLE
Use of a cocotb signal in expression does not work

### ISSUE THREAD

**Issue by svancau** [cocotb/cocotb#1133]
Hi,

During my tests I found out constructs like this :
`mysignal <= 0 if myinputsignal == 3 else 1`

typically don't work and just don't affect outputs. Whereas 

```
if myinputsignal == 3:
  mysignal <= 0
else:
  mysignal <= 1

```
just works

Do you have an idea why it doesn't work ?

Config : Windows 10 + Msys2 + Modelsim 10.6d

**Comment by eric-wieser** [comment]
Operator precedence is not what you think it is - this probably should go in the docs. You wrote:

```
mysignal <= 0 if myinputsignal == 3 else 1
```
Which means
```
(mysignal <= 0) if myinputsignal == 3 else 1
```
But you meant
```
mysignal <= (0 if myinputsignal == 3 else 1)
```

**Comment by ktbarrett** [comment]
I guess it's a little late to start complaining about how `<=` was a bad idea. It precludes the usage of signals in comparisons. You can overload assignment by modifying the ast prior to loading cocotb, https://github.com/RyanKung/assign.

**Comment by svancau** [comment]
Thanks, I just didn't figure out it was an operator precedence issue.
