### ISSUE TITLE
Cocotb library project list ?

### ISSUE THREAD

**Issue by Martoni** [cocotb/cocotb#1140]
I know that cocotb repository is for the core of cocotb and library like bus driver or monitor should be written in separate library.

But is there a library project list ? Where we should search before reinventing the wheel ?

For example I have to test a slave SPI component, I'm ready to write a spi driver for that. It would be better if I contribute to a SPI library.

**Comment by Martoni** [comment]
Ok I finally found the list: 
https://github.com/cocotb/cocotb/wiki/Further-Resources

Sorry  for the inconvenience.

**Comment by cmarqu** [comment]
Related: #1008.
