### ISSUE TITLE
QuestaSim: -noautoldlibpath does not work

### ISSUE THREAD

**Issue by da-gazzi** [cocotb/cocotb#1150]
In the Questa Makefile, `vsim` is called twice recursively - once to execute the `runsim.do` script, where `SIM_ARGS` are not applied and once in the `runsim.do` script with the `SIM_ARGS` arguments. The `-noautoldlibpath` argument prevents the `vsim` launch script from setting the `LD_LIBRARY_PATH` environment variable - but if this is done only when the nested `vsim` call is executed, it's too late - `LD_LIBRARY_PATH` is already contaminated. This can be a problem because the Mentor-distributed GCC distributions are really old and some dependencies in your CocoTB code may require newer C/C++ libraries. In my case, this was a problem when I tried to use PyTorch.

I have worked around this by adding a `PRE_SIM_ARGS` variable which is applied at the first call to `vsim` already, but maybe there is a nicer way to do it...

**Comment by ktbarrett** [comment]
We have this issue as well. We are trying to load C++11 and more modern standard C++ code in old versions of Questa. The culprit (for us at least) seems to be the vsim application launcher script. According to the script, unless vsim is invoked as 'hdloffice' or 'hdlstudio' a variable is set (`doatenv`) that causes the `LD_LIBRARY_PATH` to be set right before vsim is actually exec'd. Short of modifying the startup script, I see no way around this. However, Questa 10.6 (Early 2017, yeah only 6 years late...) and newer do ship with a libstdc++ that will work with C++11 if this is a problem.
