### ISSUE TITLE
Python 3.8: Check flags passed to python-config

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#1165]
From the Python 3.8 release notes:

----

To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.

Add a pkg-config python-3.8-embed module to embed Python into an application: pkg-config python-3.8-embed --libs includes -lpython3.8. To support both 3.8 and older, try pkg-config python-X.Y-embed --libs first and fallback to pkg-config python-X.Y --libs (without --embed) if the previous command fails (replace X.Y with the Python version).

On the other hand, pkg-config python3.8 --libs no longer contains -lpython3.8. C extensions must not be linked to libpython (except on Android and Cygwin, whose cases are handled by the script); this change is backward incompatible on purpose. (Contributed by Victor Stinner in bpo-36721.)

----

(https://docs.python.org/3/whatsnew/3.8.html)

We need to double-check our Makefiles and potentially adjust them as needed.

**Comment by ktbarrett** [comment]
I don't think this applies anymore.
