### ISSUE TITLE
AMBA Drivers and Monitors

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#117]
It would be very handy to have AMBA drivers and monitors included in Cocotb.

**Comment by Jimcinnati** [comment]
Hello, I'd like to add a driver for AXI4-Lite Slaves for cocotb. I've already created one for a testbench I've built recently and I'd like to contribute back. Is it alright if I make a contribution and tie it to this issue?

**Comment by themperek** [comment]
@Jimcinnati We have the plan to not include custom protocols into cocotb (and remove existing)  but create external plugins/components and if possible add them here: https://github.com/cocotb

Some early example (although not a protocol): https://github.com/mciepluc/cocotb-coverage/
AXI would definitely interesting if you need help let me know. You can start your private repo and if everything is ok and you want we can move to https://github.com/cocotb.

**Comment by lukedarnell** [comment]
There's already an AXI4 Lite Master in [amba.py](https://github.com/potentialventures/cocotb/blob/master/cocotb/drivers/amba.py)

@Jimcinnati does that do what you need?

**Comment by Jimcinnati** [comment]
@themperek Thanks, I'll start there.

@lukedarnell Not quite. I was testing an AXI4 Lite interconnect and needed both AXI 4 Lite masters and slaves to communicate with one another. I wanted to generate some arbitrary number of slave devices that I could write to and read from.

**Comment by themperek** [comment]
Example extension : https://github.com/mciepluc/cocotb-coverage/
If you need help (packaging/testing) let me know.

**Comment by cmarqu** [comment]
Another extension example: https://github.com/wallento/cocomod-uart

**Comment by ktbarrett** [comment]
There are some now in the cocotb-bus repo and there are several extensions. I will consider this closed rather than transfering it.
