### ISSUE TITLE
Improve the docstring for fork()

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1176]
``fork`` is missing a docstring, and so it doesn't show up in https://cocotb.readthedocs.io/en/latest/library_reference.html.

**Comment by cmarqu** [comment]
Okay, when I add ``.. autofunction:: cocotb.fork``, it does give me the docstring of ``scheduler.add`` (because ``fork`` is an alias for it) - but this should be rewritten to be useful for an end user. Right now, it's:

> Add a new coroutine.
> Just a wrapper around self.schedule which provides some debug and
> useful error messages in the event of common gotchas.

**Comment by eric-wieser** [comment]
Leaving this open, since the docstring itself needs work

**Comment by cmarqu** [comment]
> Leaving this open, since the docstring itself needs work

Indeed. It should also link to ``Join``.

**Comment by ktbarrett** [comment]
Is this considered complete? Do we want just demos, or a more detailed docstring as well?

**Comment by cmarqu** [comment]
Let's close this.
I think https://docs.cocotb.org/en/latest/coroutines.html should mention ``Join``, but that's for another issue.
