### ISSUE TITLE
LD_PRELOAD mmap library for cosimulation of unmodified software

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#118]
Thought this would be fun.

We can cosimulate unmodified software that uses some kind of read/write call to access the underlying hardware.  We do this by linking against a library that provides these calls but calls into Python.  The test can then call the unmodified software (in previous uses wrapped using SWIG) by wrapping in the `@external` decorator which executes the call in a separate thread.  This all works well and we can use production software to configure our DUT.

However if the software library uses `mmap()` rather than explicitly calling read/write functions this scheme falls down.  See stackoverflow here: http://stackoverflow.com/questions/21068714/trap-all-accesses-to-an-address-range-linux

**Comment by themperek** [comment]
How libraries are compiled has changed (#1306). The default optimization for setuptools is '-O3'  and can be changed with `CFLAGS`.

**Comment by ktbarrett** [comment]
Interesting idea, but I'm not sure this needs to be a core feature. I have heard of people doing cosimulation with qemu using VHPI and that seems like a more comprehensive approach.
