### ISSUE TITLE
Improve assignment mechanism to simulator handles

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#119]
Currently Cocotb provides the following constructs to assign variables to signals:
### Overloaded **le**

``` python
@cocotb.test()
def my_test(dut):
    # Assignment form 1: overloaded __le__ method
    dut.clk <= 1
```

This a slightly cheeky way to provide RTL-like syntax in Python.  For people familiar with Python it's counter-intuitive (and "un-pythonic": https://twitter.com/jandecaluwe/status/370597832971259904).  However it doesn't alias any functionality since it's not valid to compare a handle to anything other than direct equality to another handle (for example to check whether `clk == dut.clk`).  If attempting to compare the actual value of a signal the signal value would have to be read:

``` python
if dut.clk.value <= 1:
    # do something
```

although we should probably support the following to avoid the `value` aliasing problem described below:

``` python
if int(dut.clk) <= 1:
    # do something
```
### Value property

``` python
@cocotb.test()
def my_test(dut):
    # Assignment form 2: use the "value" property
    dut.clk.value = 0
```

This form will cause problems if an object in the RTL hierarchy is called "value", for example if we had a port named `value` we wouldn't be able to read or write to it.
### Possible enhancement

There is a third possible mechanism - to use the `__setattr__` method.  This also has limitations in that it will only work if descending at least one level into the hierarchy.

``` python
@cocotb.test()
def my_test(dut):
    # Assignment form 3: Use __setattr__
    dut.clk = 1

    # limitation - doesn't work if we only have a handle to the signal
    clk = dut.clk
    clk = 0      # Reassigns clk, doesn't drive a value
```

What is the best way to tidy this up?

Discuss.

**Comment by themperek** [comment]
Alternative "c-style":

```python
@cocotb.test()
def my_test(dut):
    dut.clk(1)
```

For ```__setattr__ ``` mechanism can define something like:
```python
assign(clk, dut.clk)
clk = 0
```

**Comment by eric-wieser** [comment]
Another approach would be a special object:
```python
class _DriverHelper:
    def __getitem__(self, sig):
        return sig.value
    def __setitem__(self, sig, value):
        sig.value = value
value_of = _DriverHelper()
```
Used as:
```python
value_of[clk] = 0
val = value_of[clk]
```

**Comment by eric-wieser** [comment]
A note on wierdness: Our use of `__le__` means that we inadvertently support
```python
3 >= dut.some_sig
```
as a spelling of
```python
dut.some_sig <= 3
```

**Comment by ktbarrett** [comment]
I've mentioned [this](https://github.com/RyanKung/assign) before. Because we start the user, we can easily enforce it's loading.

```python
dut.signal = 4
```

**Comment by ktbarrett** [comment]
We have recently deprecated the `__setattr__` and `<=` syntax. Only `.value` remains. The problems with it can be side-stepped by traversing the hierarchy with a different syntax than the syntax used to access handle operators:

```python
dut["a"]["b"'][0].value = 0
# or maybe as a convenience
dut["a.b[0]"].value = 0
```

We shouldn't let pretty syntax get in the way of things working.

**Comment by ktbarrett** [comment]
I'm going to consider this discussion closed as we have a single recommended method.
