### ISSUE TITLE
Internal tests should use expect_error=Exception

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1208]
Now that #1116 is in, our tests should make use of that feature.

**Comment by cmarqu** [comment]
Also see ``assert_raises`` in https://github.com/cocotb/cocotb/blob/281e6c0f120956921536f3215719c4534c521de1/tests/test_cases/test_cocotb/common.py

**Comment by ktbarrett** [comment]
@cmarqu I think this is done now?

**Comment by cmarqu** [comment]
Indeed.
