### ISSUE TITLE
Tests that fail before the scheduler are not handled properly

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1253]
For example:
https://github.com/cocotb/cocotb/blob/92a032a4349b2fe9e2f9bff5d1060ef44cd4cd72/tests/test_cases/test_cocotb/test_cocotb.py#L85-L88

This is considered "N/A" in the regression results banner and passes whether `expect_fail` or `expect_error` are set to `True` or `False`. A traceback is printed, but it's not apparent there was any failure if you are running a number of tests, like in `test_cocotb`.

The regression manager nor the `cocotb.test` decorator make any attempt to handle potential issues.
https://github.com/cocotb/cocotb/blob/92a032a4349b2fe9e2f9bff5d1060ef44cd4cd72/cocotb/regression.py#L157
https://github.com/cocotb/cocotb/blob/92a032a4349b2fe9e2f9bff5d1060ef44cd4cd72/cocotb/decorators.py#L477-L478

I put some time into refactoring `initialize` and `handle_result` in the regression manager, but felt like I more or less had to copy-paste to victory, which I didn't like. I think a larger refactor is in order.

**Comment by ktbarrett** [comment]
Note, this isn't an issue if the test coroutine is an async function. When async functions are called, nothing executes immediately, so they cannot fail until they get to the scheduler.

**Comment by eric-wieser** [comment]
Pretty sure we could detect this with `insoect.isgeneratorfunction` or similar

**Comment by ktbarrett** [comment]
I just didn't find a clean way of modifying `handle_result` to call it from `initialize` in the error case, but I see it now with fresh eyes.

**Comment by eric-wieser** [comment]
PR appreciated, this has been annoying me for a while when writing and screwing up new tests.

**Comment by ktbarrett** [comment]
I'm actually wondering if instead of modifying regression I should modify the decorators so that `__call__` does not immediately run the coroutine's body to the first `yield`. async coroutine functions have that deferred execution behavior, it doesn't make much sense for async and non-async coroutines to have different behavior.

**Comment by eric-wieser** [comment]
> The issue is with errors that cause coroutine initialization to fail like NameError, not necessarily any exception before the first yield.

I suspect the issue is actually errors during coroutine initialization, such as:
```
@cocotb.coroutine
def not_a_coroutine(dut):
    raise RuntimeError()
```
or
```
@cocotb.coroutine
def returns_a_coroutine(dut):
    return the_coroutine_with_a_typo()
```
