### ISSUE TITLE
Honor NO_COLOR to disable colored output

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#1309]
The NO_COLOR environment variable is proposed as a way to disable all colored output, and more and more projects are using it now. (https://no-color.org/) We should support this variable, and deprecate  COCOTB_ANSI_OUTPUT (don't remove it just yet).

**Comment by cmarqu** [comment]
Interesting - there was a related proposal in https://bixense.com/clicolors/.
Also, FWIW, most (but not all) makefiles use ``| tee <logfile>`` which makes terminal auto-detection (``isatty``) fail.
