### ISSUE TITLE
Add support for MSVC

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1372]
#1306 adds support for using setuptools, which knows how to invoke MSVC. However, initial experimentation revealed some follow-up work:

* Compiler flags need fixing (they are currently `-Werror` instead of `/W4` for instance)
* `.lib` files seem missing (https://travis-ci.org/themperek/cocotb/builds/646876123)
  * Can't use `dlltool`, need `lib /def:modelsim.def /out:modelsim.lib /machine:x86` etc

Opening this issue to track future work.

**Comment by ktbarrett** [comment]
MSVC does not support C99 which is called out as our minimum supported C version. I don't know how trivial it would be to knock C support back to the C89 standard. Honestly, there does not need to be any C files in this project. Then standards are not an issue at all...

**Comment by eric-wieser** [comment]
Numpy is able to build under MSVC and uses (most of) C99 - so I don't expect an issue there.
