### ISSUE TITLE
Icarus: Rename VPI library from gpivpi to libvpi for consistency

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#1389]
All other simulators using VPI use a library named "libvpi", for Icarus it's named gpivpi. There seems to be no technical reason for this discrepancy. Rename it for consistency.

**Comment by eric-wieser** [comment]
I think the technical reason is that icarus comes with `libvpi.a`, and this avoids a name collision

**Comment by cmarqu** [comment]
``libcocotbvpi`` would align nicely with the VHPI library name that we use since #1168.
