### ISSUE TITLE
Passing plusargs to FLI: Find code that works with different TCL versions

### ISSUE THREAD

**Issue by themperek** [cocotb/cocotb#1404]
There is an error on RHEL7 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

Compilation error in ‘Tcl_Interp’ has no member named ‘result’ 

```
 cocotb/share/lib/fli/FliCbHdl.cpp:164:44: error: ‘Tcl_Interp’ has no member named ‘result’
       unsigned long argc_u = strtoul(interp->result, NULL, 10);
                                              ^
  cocotb/share/lib/fli/FliCbHdl.cpp:183:43: error: ‘Tcl_Interp’ has no member named ‘result’
           argv[i] = new char[strlen(interp->result)+1];
                                             ^
  cocotb/share/lib/fli/FliCbHdl.cpp:184:33: error: ‘Tcl_Interp’ has no member named ‘result’
           strcpy(argv[i], interp->result);
                                   ^
```

Seems to be related to https://github.com/cocotb/cocotb/pull/1256  @ktbarrett

**Comment by imphil** [comment]
Is cocotb picking up the right tcl library and header file from Questa, or is it using the system-provided one?

**Comment by themperek** [comment]
It looks as if it is ok for Questa 10.x but 2019.x fails.

**Comment by imphil** [comment]
Can you try reverting https://github.com/cocotb/cocotb/commit/b283b48368a3a7f507110c6699db3a6c7ce01677 and see if that fixes compilation? (If so, I'll back out this change until we find a solution that universally works.)

**Comment by themperek** [comment]
Checked https://github.com/cocotb/cocotb/commit/b283b48368a3a7f507110c6699db3a6c7ce01677 seems to be a problem.

**Comment by themperek** [comment]
The version of tcl changed from 8.5 to 8.6

**Comment by imphil** [comment]
OK, revert in #1407. @ktbarrett can you look into finding a solution which works for both simulators? Ideally, one that doesn't involve conditional compilation (see #1392).
