### ISSUE TITLE
Partition environment variables

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1477]
From https://github.com/cocotb/cocotb/pull/1293#discussion_r386031732.

In the [Build options and Environment Variables]( https://cocotb.readthedocs.io/en/latest/building.html#build-options-and-environment-variables) section of the the documentation, there are a lot of environment variables under the sections: "Make Variables", "Environment Variables", and "More Environment Variables", which aren't terribly useful names or ways of partitioning the variables.

They should be broken into several partitions according to the consumer/owner of the variable: GPI, Python/GPI interface, the regression manager, the scheduler, and the makefile-based test scripts, etc.

**Comment by cmarqu** [comment]
I agree. In order to ease collaboration on the partitioning, I have taken the names and short description from ``Makefile.sim`` and copied them to https://github.com/cocotb/cocotb/wiki/__Playground__

**Comment by cmarqu** [comment]
Of the list, I would pull the variables marked in <https://github.com/cocotb/cocotb/wiki/__Playground__> with ``(__common__)`` into a beginners tutorial in #1482 (or follow-up PR).

**Comment by ktbarrett** [comment]
Updated the wiki, added `RANDOM_SEED`.
