### ISSUE TITLE
An unexpected termination has occurred in sim_build/simv due to a signal: Segmentation fault

### ISSUE THREAD

**Issue by futurehome** [cocotb/cocotb#1480]
Hi,

I tried to run an example test - axi_lite_slave, with cocotb 1.3, vcsmx/2018.09_sp2_8, but the simulation crashed, I found something unusual in the log file:
1)     -.--ns ERROR    cocotb.gpi                                 VpiCbHdl.cpp:74   in arm_callback                    VPI: Unable to register a callback handle for VPI type cbStartOfSimulation(11)
2)     -.--ns ERROR    cocotb.gpi                                 VpiCbHdl.cpp:74   in arm_callback                    VPI: Unable to register a callback handle for VPI type cbEndOfSimulation(12)
3) The VPI function 'vpi_chk_error' is not supported in the compiler.
4) An unexpected termination has occurred in sim_build/simv due to a signal: Segmentation fault.

Please find the detail in the attached log file.
Can you please help to figure it out?

Thanks,
Alex

[axi_lite_slave.log](https://github.com/cocotb/cocotb/files/4290643/axi_lite_slave.log)

**Comment by cmarqu** [comment]
Related: #1261

**Comment by futurehome** [comment]
Are there any ways that I can use to avoid this bug temporarily?

Alex

**Comment by cmarqu** [comment]
Try the change described in https://github.com/cocotb/cocotb/issues/1261#issuecomment-571718339 which is here: https://github.com/cocotb/cocotb/blob/77ecf0ef67aad31916be1baf16b8174e8591b70d/cocotb/share/lib/gpi/GpiCommon.cpp#L137

**Comment by futurehome** [comment]
Still the same issue after modify GpiCommon.cpp file.
![image](https://user-images.githubusercontent.com/6230304/76183113-41b41900-6202-11ea-93bd-43150cd3f6af.png)

**Comment by cmarqu** [comment]
One pitfall that may be the cause: if you installed cocotb with pip (in editable mode), you need to re-run pip with the ``-f`` option in order to actually compile the C++ code change.

**Comment by themperek** [comment]
>One pitfall that may be the cause: if you installed cocotb with pip (in editable mode), you need to re-run pip with the -f option in order to actually compile the C++ code change.

@cmarqu This is the only case for >= 1.4
