### ISSUE TITLE
Memory leak in simulation

### ISSUE THREAD

**Issue by JaewonHur** [cocotb/cocotb#1481]
When running cocotb with verilator, there is a memory leak in simulation.

I ran valgrind and found some result, but I couldn't know whether it is the issue of cocotb or verilator.
(I just yield 1000 cycles of clock with on RocketTile)

[valgrind-out.txt](https://github.com/cocotb/cocotb/files/4291126/valgrind-out.txt)

**Comment by JaewonHur** [comment]
It is related to verilator, there is no memory leak when using iverilog.

**Comment by themperek** [comment]
@JaewonHur I this situation I close it. Please feel free to reopen if needed.
