### ISSUE TITLE
'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by futurehome** [cocotb/cocotb#1483]
Hi,

When I try to run example like ping_tun_tap, it shows the error below:

Chronologic VCS simulator copyright 1991-2017
Contains Synopsys proprietary information.
Compiler version N-2017.12-SP1_Full64; Runtime version N-2017.12-SP1_Full64;  Mar  6 11:38 2020
     -.--ns INFO     cocotb.gpi                                  gpi_embed.c:78   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     cocotb.gpi                                GpiCommon.cpp:104  in gpi_print_registered_impl       VPI registered

Traceback (most recent call last):
  **_File "/home/alewa/.local/lib/python3.7/site-packages/cocotb/__init__.py", line 41, in <module>
    import cocotb.handle
  File "/home/alewa/.local/lib/python3.7/site-packages/cocotb/handle.py", line 35, in <module>
    if sys.version_info.major < 3:
AttributeError: 'tuple' object has no attribute 'major'_**

     -.--ns ERROR    cocotb.gpi                                  gpi_embed.c:224  in get_module_ref                  _**Failed to load Python module "cocotb"**_

Can you please help to figure it out? I'm using cocotb 1.3.
Thanks,
Alex

**Comment by ktbarrett** [comment]
Could you post the result of the command `python --version`?

**Comment by futurehome** [comment]
It's the setting issue for python, thanks.

Alex

**Comment by futurehome** [comment]
It's my setting issue for python, thanks.

Alex
