### ISSUE TITLE
Questa Makefile changes for 2020 releases

### ISSUE THREAD

**Issue by sjalloq** [cocotb/cocotb#1492]
Hi,

I recently received a 2020.1 patch fix for a Cocotb issue I reported to Mentor.  One issue that users will soon see is that Questa errors out if the old style +acc=rmb is used.  This requires a simple change to Makefile.questa.

```
# QuestaSim-64 vlog QA Baseline: 2020_weekly_200214 - 4305442 Compiler 2020.02 Feb 14 2020
# ** Error (suppressible): (vlog-14401) Option specified: +acc=rmb. Following acc options are now deprecated 'f' 'm' 'q' 't' 'x' 'y'.
# Errors: 1, Warnings: 0
```

**Comment by ktbarrett** [comment]
This has been fixed in #1832 and #1908.
