### ISSUE TITLE
Test names are incorrect in summary

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1499]
From https://github.com/cocotb/cocotb/pull/1380#issuecomment-599155133. Introduced in #1262. It's due to all the unnecessary monkeying the decorators and regression manager do to compute a name. The PR changed how the module name is passed to `_store_test_result`. It uses `__module__`, but on `RunningTest`s that value is `cocotb.decorator` instead of the module name of the underlying function.

**Comment by ktbarrett** [comment]
`RunningTest` mostly exists for use by the regression manager. It really doesn't need all the extra attributes on it, they already exist on the `test` object. The regression manager should be changed to just work off `test` objects instead of stuffing all the info it needs from that object into yet another object. `RunningTest` and `RunningCoroutine` should just go away entirely. I think this will require a change to the scheduler as well as the regression manager due to how `handle_result` works. The relationship between the scheduler and regression manager are just very very irregular...

**Comment by eric-wieser** [comment]
To be clear, you're advocating that `RunningTest` and `RunningCoroutine` should both be replaced with their `RunningTask` baseclass, which doesn't have any of the weird attributes.

**Comment by eric-wieser** [comment]
> The relationship between the scheduler and regression manager are just very very irregular...

What I'd eventually like to happen is for the regression manager to just be a single coroutine run by the scheduler, with the weirdness wrapped into a few new scheduler methods or context managers

**Comment by ktbarrett** [comment]
@eric-wieser Yes, deprecated `RunningTest` and `RunningCoroutine` and change the decorators to create `RunningTasks` in their place. The regression manager could simply `fork` a test "watcher", which in turn `fork`s the test coroutine and records the outcome of the test once it finishes. I don't think we need any additional scheduler features to support that.

**Comment by eric-wieser** [comment]
We need a feature to collect and kill all coroutines forked by the test before starting the next one, which is currently embedded in the scheduler.

**Comment by ktbarrett** [comment]
I think we should destroy the scheduler between tests and have each trigger/coroutine clean itself up. But don't we already have `finish_scheduler` for that purpose?
