### ISSUE TITLE
Improve error reporting for `yield` inside async function

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1512]
Those that are in the process of converting `cocotb.coroutine` functions using `yield` to async functions may run into problems where they miss a `yield`, which turns their coroutine into an async generator. If an async generator makes it to the scheduler it will result in a less than helpful error message. Instead we should check for async generators where we expect coroutines and throw a `TypeError` with a more helpful message, much like we do with old style coroutines missing `yield` statements.

**Comment by eric-wieser** [comment]
Good idea

**Comment by eric-wieser** [comment]
I assume the current error message is from these lines:

https://github.com/cocotb/cocotb/blob/c4a573defa921e5a16e63f585481ad3790bcf5d7/cocotb/decorators.py#L90-L98

Is all you're suggesting a more precise error if `inspect.isasyncgen` is true?

**Comment by ktbarrett** [comment]
@eric-wieser I think that will be the only place that needs to change, `fork`s and `yield`s must go through that, when using `await` you have different semantics. But I will test.
