### ISSUE TITLE
Consider deprecating property aliases in BinaryValue

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1513]
We should consider deprecating all of these `BinaryValue` methods:

  * `.set_value(x)`, which is just `.value = x`
  * `.get_value()`, which is just `.value`
  * `.set_buff(x)`, which is just `.buff = x`
  * `.get_buff()`, which is just `.buff`
  * `.get_value_signed()`, which is just `.signed_integer`
  * `.set_binstr(x)`, which is just `.binstr = x`
  * `.get_binstr()`, which is just `.binstr`

As of #719, none of these are shown in the sphinx docs.
Documenting these has the same caveats as #1503.

**Comment by ktbarrett** [comment]
The whole damn thing is deprecated. Does that work?
