### ISSUE TITLE
Consider changing base class of NonConstantObject

### ISSUE THREAD

**Issue by marlonjames** [cocotb/cocotb#1522]
I don't see why `NonConstantObject` should inherit from `NonHierarchyIndexableObject`. Wouldn't it make more sense for it to be another branch from `NonHierarchyObject`?

See https://cocotb.readthedocs.io/en/latest/library_reference.html#simulation-object-handles for class diagram.

**Comment by eric-wieser** [comment]
It's worth thinking about the effect this would have on these lines:

https://github.com/cocotb/cocotb/blob/7c3f44df806184d1b3ccade7b8492bde826dd34e/cocotb/handle.py#L810-L821

Not to say that I've done that thinking yet.
