### ISSUE TITLE
Remove support for cross-compilation in the endian example

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1585]
We have some weird code here that seemingly tries to support building 32-bit extension modules with 64-bit python, if the user overrides the `ARCH` variable:

https://github.com/cocotb/cocotb/blob/688d391376eda47446d8f949d9e62f8ca93d51b0/cocotb/share/makefiles/Makefile.pylib#L34-L35

https://github.com/cocotb/cocotb/blob/688d391376eda47446d8f949d9e62f8ca93d51b0/cocotb/share/makefiles/Makefile.pylib.Linux#L34-L38

https://github.com/cocotb/cocotb/blob/688d391376eda47446d8f949d9e62f8ca93d51b0/cocotb/share/makefiles/Makefile.pylib.Darwin#L34-L38

I don't know why we'd ever want to support this. If the user needs a 32-bit extension module, then they should be using `cocotb-config` installed inside a 32-bit python. Or better yet, they should be looking at the python docs to build it,  not our docs.

If we removed it, we could merge all the `Makefile.pylib` files into a single file.

It seems that maybe this is a remnant of when this override was in place:

https://github.com/cocotb/cocotb/blob/688d391376eda47446d8f949d9e62f8ca93d51b0/cocotb/share/makefiles/simulators/Makefile.modelsim#L31

**Comment by themperek** [comment]
I am for it. In any case, it may not be so easy and not sure that those lines will help (rather more confusion). 

It can be moved to the endian example worst case.

**Comment by eric-wieser** [comment]
> It can be moved to the endian example worst case.

Or perhaps also in the best case. After removing these workaround, there are only two interesting lines left in the makefile:

https://github.com/cocotb/cocotb/blob/688d391376eda47446d8f949d9e62f8ca93d51b0/cocotb/share/makefiles/Makefile.pylib.Linux#L32

https://github.com/cocotb/cocotb/blob/688d391376eda47446d8f949d9e62f8ca93d51b0/cocotb/share/makefiles/Makefile.pylib.Linux#L40

These could easily be moved to within the endian example makefile

**Comment by eric-wieser** [comment]
After gh-1619, this is already not supported - we may as well delete the makefiles now.
