### ISSUE TITLE
Fatal Python error: no mem for sys.argv

### ISSUE THREAD

**Issue by abhisheietk** [cocotb/cocotb#159]
I am trying to compile cocotb example and getting this error.

TESTCASE= TOPLEVEL=endian_swapper \
        vvp -M /home/abhishek/2014_devel/cocotb/potentialventures-cocotb-11f9ac0/build/libs/x86_64 -m gpivpi sim_build/sim.vvp  
Fatal Python error: no mem for sys.argv
ValueError: character U+6f636f63 is not in range [U+0000; U+10ffff]
/home/abhishek/2014_devel/cocotb/potentialventures-cocotb-11f9ac0/makefiles/simulators/Makefile.icarus:36: recipe for target 'results.xml' failed

Please help.

python --version
Python 2.7.8
Cocotb => potentialventures-cocotb-11f9ac0
System => 64 bit Archlinux

**Comment by ILMostro** [comment]
So...this was closed 3 years ago as, presumably, *WONTFIX* (at least for Linux)?

Is there no plan to add support for Python3?

**Comment by AlexanderSpirin** [comment]
@ILMostro COCOTB supports Python3. What problems do you have?
