### ISSUE TITLE
Set/use $(ARCH) based python binary version not system in the Makefiles

### ISSUE THREAD

**Issue by themperek** [cocotb/cocotb#1600]
See: https://stackoverflow.com/questions/2208828/detect-64bit-os-windows-in-python

**Comment by eric-wieser** [comment]
Do we even need `ARCH`?

**Comment by themperek** [comment]
Like here: https://github.com/cocotb/cocotb/blob/master/cocotb/share/makefiles/simulators/Makefile.questa#L119

So if one has 32bit python on 64bit system it will fail.
