### ISSUE TITLE
Update the contributors section of the docs

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1625]
As requested by @imphil in https://github.com/cocotb/cocotb/pull/1482, which I requested we revert in order to handle as a separate PR.

> Please remove the whole contributors section for now, it's outdated. You can replace it with something like:
> 
> ```rst
> cocotb is developed and maintained by an active community under the umbrella of the `Free and Open Source Silicon Foundation <https://www.fossi-foundation.org>`_. 
> 
> Our GitHub repository contains a list of all `contributors <https://github.com/cocotb/cocotb/graphs/contributors>`_. 
> ```
> 

In my opinion we should keep the old attributions too, in case they are historically interesting - although I don't think they need to be as visible as they are today.

**Comment by imphil** [comment]
Yes, they have to stay somewhere discoverable, but not on the quickstart page.
