### ISSUE TITLE
Remove deprecated "_compat_mapping"

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1638]
Use of ``_compat_mapping``:
https://github.com/cocotb/cocotb/blob/90023310e8f6b6c9124c725266733578de3665f8/cocotb/handle.py#L58-L66

has been giving deprecation warnings for a long time (https://github.com/cocotb/cocotb/blame/ba0fb097efbd2939ad6a961ee8d02793104ef8f7/cocotb/handle.py#L131), so  we can remove it.

**Comment by eric-wieser** [comment]
Remember that deprecation warnings have been visible by default for much less time

**Comment by cmarqu** [comment]
Indeed, I'm setting the 2.0 milestone for this. 

Related: #1642

**Comment by marlonjames** [comment]
Removed in #3455
