### ISSUE TITLE
Document deprecation and removal strategy

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1642]
We should document our deprecation and removal strategy. 

From https://github.com/cocotb/cocotb/pull/1496#pullrequestreview-387405087

"Only deprecate things in minor releases, and remove them in the next major release. (See https://symfony.com/doc/current/setup/upgrade_major.html#make-your-code-deprecation-free for a project that follows this principle"

**Comment by cmarqu** [comment]
What we could do is for every ``.. deprecated::`` line, specify the version number where support is going to be removed.
This would require that we do use predictable future version numbers.

**Comment by themperek** [comment]
Last supported versions would be easier.

**Comment by cmarqu** [comment]
Would it really? We would have to write something like "Last version this is supported in is 1.x.y", since we cannot know how many x'es and y's may still come.

**Comment by themperek** [comment]
>Would it really? We would have to write something like "Last version this is supported in is 1.x.y", since we cannot know how many x'es and y's may still come.

This is exactly what I get with some IC place & route tools.

**Comment by cmarqu** [comment]
We should have a section like that in the docs of the 1.5 release: https://docs.antora.org/antora/2.3/whats-new/#caution-coming-soon
