### ISSUE TITLE
Add debug rule to makefiles

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#168]
To diagnose build problems on various platforms it would be good to have a `make debug` rule that would dump a load of useful information.

**Comment by ktbarrett** [comment]
>.. a `make debug` rule that would dump a load of useful information.

There was a rule added to Makefile.pylib, that has since been removed (#1632). I think this issue is too vague about what such a target would do, so I will close it in preference of a new issue that is more specific.

**Comment by eric-wieser** [comment]
Note that many makefiles already have a debug target:

https://github.com/cocotb/cocotb/blob/dfaac9732e3b6b07e37c928c25bc93b7cc9e6d77/cocotb/share/makefiles/simulators/Makefile.icarus#L65-L81

Agreed we can track unifying that in a new issue.
