### ISSUE TITLE
Document how cocotb can be bolted onto an existing simulation environment (bypassing makefiles...)

### ISSUE THREAD

**Issue by gretzteam** [cocotb/cocotb#1687]
Adding cocotb support to an existing simulation environment is doable without the use of Makefiles. Document what needs to be done for each simulator.

Snippet from Gitter discussion:

> At this point, bolting in cocotb into an existing environment is really just a case of adding -m libcocotbvpi_icarus or similar to the simulator invocation, and setting the environment variables MODULE, TOPLEVEL, TOPLEVEL_LANG, and COCOTB_SIM. .. For other simulators, the flag for libcocotb* is slightly different

>xcelium: -loadvpi /cocotb/cocotb/libs/libcocotbvpi_ius:vlog_startup_routines_bootstrap

>We may want to rename MODULE to COCOTB_MODULE etc. so that it's clear what this is about when used to together with other envvars from the original testbench environment

**Comment by themperek** [comment]
Related to #1461 #1562

**Comment by garmin-mjames** [comment]
See #1718

**Comment by cmarqu** [comment]
Closed a while ago by https://github.com/cocotb/cocotb/pull/2340.
