### ISSUE TITLE
Possible Optimisations - cache get_sim_time for performance

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#171]
Using this issue as a placeholder for potential optimisations because we're prone to forget things.

**Comment by themperek** [comment]
@eric-wieser Do you think we can close this? In favor of #961?

**Comment by eric-wieser** [comment]
I think we should retitle this issue to "cache get_sim_time for performance"

**Comment by ktbarrett** [comment]
From the profiling done in #961, this is pretty low on the list of possible optimization. I don't think it deserves it's own issue.
