### ISSUE TITLE
Move utility scripts out of the cocotb package

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1716]
We should introduce another namespace to put python libraries/scripts that don't depend on the cocotb runtime. For example, the build script.

**Comment by ktbarrett** [comment]
In the case of the `build_ext` it probably should be merged into setup.py, as it is done in the [main python distribution](https://github.com/python/cpython/blob/master/setup.py).

**Comment by eric-wieser** [comment]
But note that that setup.py imports `distutils`, so its still the case that not all the code is in one place. In my opinion the split aids clarity for now, so we should keep it as long as we do so in a way that doesn't cause other issues.

**Comment by ktbarrett** [comment]
I tried just moving build libs into the top level, but the import fails when using tox. Perhaps there is some option to get tox to recognize it as a build dependency? CPython puts their `build_ext` overload in setup.py; it's a big file, I feel if they knew how to split it up, they would.

**Comment by eric-wieser** [comment]
Did you remember to add it to `MANIFEST.in`?
