### ISSUE TITLE
Convert examples to use `async def` syntax

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1730]
Currently, the examples use [the old `yield` syntax.](https://docs.cocotb.org/en/latest/coroutines.html#generator-based-coroutines)

We should change them to use the now-recommended [`async def` / `await` syntax](https://docs.cocotb.org/en/latest/coroutines.html#async-functions).

Split from #1289.

These are:

* [x] `adder` (#1826)
* [x] `axi_lite_slave` (#1941)
* [x] `dff` (#1752)
* [x] `simple_dff` (always in the new style)
* [x] `endian_swapper` (#1941)
* [x] `mean` (#1902)
* [x] `mixed_language` (#1941)
* [x] ~~`ping_tun_tap`~~ (#2234)

**Comment by ktbarrett** [comment]
#2234 would remove the last unconverted example.
