### ISSUE TITLE
Error messages that don't hint at cocotb

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1736]
The strings in
https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/utils/cocotb_utils.cpp
do not say that they are coming from cocotb, but they should so that they can be differentiated from simulator messages.
Also, can e.g. "We are calling up again" get a bit more context?

**Comment by ktbarrett** [comment]
I feel like we should make those functions macro functions and use the `LOG_*` functions instead of directly printing to stdut/stderr. I have that change hanging out in a branch.

**Comment by cmarqu** [comment]
Fixed by #1743.
