### ISSUE TITLE
WAVES=1 doesn't generate waveforms for modelsim

### ISSUE THREAD

**Issue by scottwilson46** [cocotb/cocotb#174]
Requires a change to the Makefile.modelsim:

runsim.do : $(VHDL_SOURCES) $(VERILOG_SOURCES) $(CUSTOM_SIM_DEPS)
        echo "vlib work" > $@
ifneq ($(VERILOG_SOURCES),)
        echo "vlog -timescale 1ns/100ps -mfcu +acc=rmb -sv $(VLOG_ARGS) $(VERILOG_SOURCES)" >> $@
else
        echo "vcom $(VHDL_ARGS) $(VHDL_SOURCES)" >> $@
endif
        echo "vsim $(VSIM_ARGS) $(TOPLEVEL)" >> $@
ifneq ($(GUI),1)
        echo "run -all" >> $@
        echo "quit" >> $@
endif

to:
runsim.do : $(VHDL_SOURCES) $(VERILOG_SOURCES) $(CUSTOM_SIM_DEPS)
        echo "vlib work" > $@
ifneq ($(VERILOG_SOURCES),)
        echo "vlog -timescale 1ns/100ps -mfcu +acc=rmb -sv $(VLOG_ARGS) $(VERILOG_SOURCES)" >> $@
else
        echo "vcom $(VHDL_ARGS) $(VHDL_SOURCES)" >> $@
endif
        echo "vsim $(VSIM_ARGS) $(TOPLEVEL)" >> $@
ifneq ($(GUI),1)
ifeq ($(WAVES),1)
        echo "log -r /*" >> $@
endif
        echo "run -all" >> $@
        echo "quit" >> $@
endif

**Comment by themperek** [comment]
It should work now. In case you still have issues please reopen. @cmarqu  thank you for pointg out.
