### ISSUE TITLE
Makefiles write to sim.log inconsistently

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#1746]
Our ``Makefile.ghdl`` doesn't have the usual `` | tee $(SIM_BUILD)/sim.log`` at the end of the simulation command line nor any other option to that effect, so it doesn't produce a ``sim.log`` file at all.

**Comment by cmarqu** [comment]
Actually, this file ``sim.log`` is only used in about 50% of our Makefiles, the other ones are letting the simulator write whatever file it likes.
Since the ``| tee`` is breaking the ``isatty`` detection for color output, we should rather try to remove this.

**Comment by cmarqu** [comment]
The ``| tee`` is our way to collect all log output, even the lines before and after the actual simulator run.

**Comment by garmin-mjames** [comment]
There's some issue with **activehdl**, `tee`, and `set -o pipefail`. On some tests and examples when running regression suite it fails even if the tests pass and the simulator exits normally.

I haven't been able to track down the exact details, but it looked like somehow `tee` is exiting with a non-zero status.

**Comment by cmarqu** [comment]
@garmin-mjames Huh. Probably worth its own issue?

**Comment by garmin-mjames** [comment]
Yeah I'll try to track it down more precisely and make an issue
