### ISSUE TITLE
sim target at the end of Makefile

### ISSUE THREAD

**Issue by m-kru** [cocotb/cocotb#1763]
I have realized, that some Makefiles have `sim` target at the end.  It looks like [Creating a Makefile](https://docs.cocotb.org/en/latest/quickstart.html#creating-a-makefile) does not document this. When this `sim` target is required, what is its purpose?

```Makefile
# list all required Python files here
sim: $(MODULE).py
```

**Comment by cmarqu** [comment]
There is a default ``sim`` target:
https://github.com/cocotb/cocotb/blob/7db4c187e2c303d31f8226782b2afece6432eade/cocotb/share/makefiles/Makefile.inc#L35-L40
