### ISSUE TITLE
Is yield planned to be deprecated ?

### ISSUE THREAD

**Issue by Martoni** [cocotb/cocotb#1768]
With async framework we now can «block» on events with two methods.
Will these two methods continue to coexist?
Or is it planned to abandon the yield method?

**Comment by eric-wieser** [comment]
> Will these two methods continue to coexist?

At least for the next release, yes

> Or is it planned to abandon the yield method?

Doing so would break a very large number of existing users. At the very least we'd want to wait for cocotb 2.0 before doing that, or possibly even longer.

Having said that, if you have the ability to choose which style to use today, you should choose `await`!

**Comment by Martoni** [comment]
> Having said that, if you have the ability to choose which style to use today, you should choose await!

Ok, that's what I wanted to know.

Thanks
