### ISSUE TITLE
Turn on -O2

### ISSUE THREAD

**Issue by stuarthodgson** [cocotb/cocotb#178]
Quick test with a modified endian_swapper test to no do randomisation yields.

Icarus
real    0m49.448s
user    0m48.949s
sys     0m0.483s

Icarus + -O2
real    0m42.136s
user    0m41.642s
sys     0m0.491s

But on Aldec
real    0m52.423s
user    0m53.104s
sys     0m2.406s

Aldec + -O2
real    1m2.930s
user    1m4.344s
sys     0m3.050s

Should figure out why before turning on as default.

**Comment by themperek** [comment]
How libraries are compiled has changed (#1306). The default optimization for setuptools is '-O3' and can be changed with `CFLAGS`.
