### ISSUE TITLE
Consider setting default documentation page to `stable`

### ISSUE THREAD

**Issue by themperek** [cocotb/cocotb#1794]
At the moment default documentation page points to `latest` that is taken from the development branch (`master`).  This leads often to confusion for many since they install vial `pip install cocotb` and may exhibit compatibility issues. To improve this consider using `stable` to be the default.

**Comment by eric-wieser** [comment]
Doing so would mean we lose our note saying "download exactly the right version of the examples". This might be a good idea _after_ we next release though.

**Comment by eric-wieser** [comment]
This was done.
