### ISSUE TITLE
AvalonSTPkts hexdump needs a minor fix now that the transaction is of type bytes rather than string

### ISSUE THREAD

**Issue by ajeshp** [cocotb/cocotb#1799]
When DEBUG logging level is enabled, the `hexdump` call in `_monitor_recv` function of AvalonSTPkts calls hexdump after converting the `pkt` in to `str` which is no longer needed

**Comment by eric-wieser** [comment]
Mind giving a filename and line number?

**Comment by ajeshp** [comment]
line 220 in `cocotb/cocotb/monitors/avalon.py`

**Comment by eric-wieser** [comment]
https://github.com/cocotb/cocotb/blob/c7da01ce2d09aec7f76da9f1b802a3bd679942fc/cocotb/monitors/avalon.py#L220

Thanks, good find. Want to make a PR to fix that?

**Comment by ajeshp** [comment]
Sure, will do soon.

**Comment by ajeshp** [comment]
Submitted a PR: https://github.com/cocotb/cocotb/pull/1800
But I think I screwed up the linking of this PR to this issue. Apologies, this is my first PR.
