### ISSUE TITLE
crv.py module 

### ISSUE THREAD

**Issue by tsengr0916** [cocotb/cocotb#1814]
We used  to have crv.py module in cocotb. It is not in there any more. Is there a reason for that? What constraint random module would you recommend to use now? And where can we download it from? 

Thanks,
Richard

**Comment by ktbarrett** [comment]
If that file was in this repo, it should be in the history. Otherwise you could take a look at [cocotb-coverage](https://github.com/mciepluc/cocotb-coverage).

**Comment by garmin-mjames** [comment]
See also https://github.com/cocotb/cocotb/wiki/Further-Resources for other cool stuff.

**Comment by tsengr0916** [comment]
Thank you all very much. This is helpful!!

There is another python-constraint at this link seems to be a global wised effort for constraint solver: https://github.com/python-constraint/python-constraint

Could we integrate it into COCOTB constraint solver engine?

Richard

**Comment by themperek** [comment]
>There is another python-constraint at this link seems to be a global wised effort for constraint solver: https://github.com/python-constraint/python-constraint

[cocotb-coverage](https://github.com/mciepluc/cocotb-coverage) is using it.

>Could we integrate it into COCOTB constraint solver engine?

The consensus is at the moment this should be an external module.

**Comment by themperek** [comment]
@tsengr0916 I think this answers your question so I close. Fell free to reopen if it is not the case.
