### ISSUE TITLE
Constant string handle __str__ returns garbage value

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1865]
If a constant is a string, it gets the value with `get_signal_value_str` which returns a `bytes` object. The `__str__` implementation simply casts the underlying value using `str()` and returns that. Casting a bytes object to a string results in a garbage value: `"b'handle value'"`. This needs to be better thought out. Perhaps constant objects need to be split out into different type classes like `ModifiableObjects` are.

**Comment by eric-wieser** [comment]
Implementing `__bytes__` instead of `__str__` would fix this, right?

**Comment by ktbarrett** [comment]
Yeah, but that still leaves the existing surprising behavior in the `str` cast. It's easy enough to just use `handle.value` and deal with type conversion yourself. This kind of ties into #1222 where using the built in casts operators directly on handles results in surprising behavior.

**Comment by eric-wieser** [comment]
I agree with the sentiment of #1222, but I think we need to add `__bytes__` and remove `__str__` to be consistent with the general change from str to bytes.

**Comment by eric-wieser** [comment]
That is, I'd consider this a regression we need to fix for 1.4, _in addition_ to a design flaw we need to address at some point.

**Comment by ktbarrett** [comment]
Note this also affects `StringObject`s.

**Comment by ktbarrett** [comment]
We also can't remove `__str__` and supplant it with `__bytes__` due to the poor design. That would affect existing string casts on constant logic vectors (`BinaryValue` doesn't implement `__bytes__`) and constant integers and reals (`__str__` is well defined, `__bytes__` is not).

**Comment by eric-wieser** [comment]
Isn't this equally a problem for _non_-constant objects?

**Comment by ktbarrett** [comment]
Yes, I mentioned it affect `StringObject`s as well, but they can simply have `__str__` -> `__bytes__` without problem, but `ConstantObject` is hard because it services all const types.


I'd really like to see the whole thing refactored so that `SimHandle` can have custom type registered to use a specific `ModifiableObject` subtype, then we could register provided subtypes for strings, reals, logic vector, etc by default. Constness would only be checked/raise when setting the handle. This would require we add the ability to obtain the type of a signal as a string to the GPI so we could support types other than the basics. But that's 2.0 work.
