### ISSUE TITLE
Can't get signals handle under generate blocks using vcs

### ISSUE THREAD

**Issue by dzplay** [cocotb/cocotb#1897]
In cocotb we get signal value as:
   b = dut.sub_top_inst.gen_mods.test_byte_fifo_wdata_force_net_gen
The 'gen_mods' in list is created by generate block, in line 78:
![image](https://user-images.githubusercontent.com/25949699/83472564-259add80-a4ba-11ea-995d-3308df29fd94.png)
the root cause is when finding node 'gen_mods' with vpi_handle_by_name() , it will return null.
our simulator is vcs_P-2019.06-SP2-1
Can anyone solve this problem？

**Comment by ktbarrett** [comment]
See #2190. This is currently a bug in cocotb we have yet to resolve.
