### ISSUE TITLE
Consolidate examples

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#19]
The examples also double as a regression to ensure we don't break the APIs. We probably want only 2 examples in the repo:

1 - A set of separate tests that exercise all of the available features
- Communication between coroutines using events
- Fork/Join simultaneous execution
- All the various trigger types
- Combining triggers
- Test timeout
- Expected test failure etc
- Use of Driver, Monitor, Scoreboard class etc

2 - An example of a verified block with a suite of tests

Example 1 ("features") would also work as a tutorial / introduction to cocotb.

**Comment by ktbarrett** [comment]
I think we have decided against only having 2 examples in the repo. We have several examples and a slew of unit tests. I don't think a single example could act as a good unit test (or a good example) either.
