### ISSUE TITLE
Make coverage deterministic

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1930]
Every PR is showing slight fluctuations in coverage, likely due to random test data. I find this irritating. We should try to design tests that cover all branches of the thing we are testing. Fixing the seed would also work, but I think that's a bad idea.

**Comment by imphil** [comment]
> Fixing the seed would also work, but I think that's a bad idea.

Deterministic tests are important for CI runs, and fixing the seed is a absolutely valid way of doing that.

**Comment by ktbarrett** [comment]
If that's the case, we probably should test with multiple fixed seeds.

**Comment by ktbarrett** [comment]
That might mask errors if we also don't write our tests for 100% coverage.

**Comment by ktbarrett** [comment]
It seems there were many issues with coverage collection that are now fixed (#2397).
