### ISSUE TITLE
Increase Python code coverage

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1962]
There are a few reasons why coverage is low; the reasons vary. This issue exists to list and track the completion of tasks relating to increasing code coverage. I think the next realistic goal is to take coverage above 80%. In general, we need to mark error cases we cannot trigger on our own with `pragma: no cover`.

## Dead Code
Coverage is 0% on dead code... Some code is "public" and must go through a deprecation cycle, but the rest can be removed.
- xunit_reporter.py
  - [x] update_testsuite
  - [x] update_testsuites
  - [x] add_log
  - [x] add_failure
  - [x] The entire `File` class 
- utils.py
  - [x] reject_remaining_kwargs
  - [x] get_python_integer_types
  - [x] main script part

## Untested, potential code baggage

This stuff isn't tested, likely because it's not a very useful feature and/or undocumented.
- utils.py
  - [x] pack
  - [x] unpack, and the associated code in handle.py

## Untested

- [x] memdebug.py and MEM_CHECK=1 is never tested in CI.
- scheduler.py
  - [ ] COCOTB_SCHEDULER_DEBUG=1 is never run in CI, so a lot of statements are missed
  - [ ] COCOTB_ENABLE_PROFILING=1 is never run in CI, so a lot of statements are missed
- regression.py
  - [ ] COVERAGE=1 is never run in CI, so a lot of statements are missed
  - [ ] actually failing tests are untested.
- handle.py
  - just a lot of stuff, it has a pretty large interface and most of it isn't useful, so it isn't tested
- binary.py
  - [x] All of the logic and arithmetic functionality are untested
  - [x] in general `bigEndian=True` isn't well tested
- [X] `cocotb.hook`s are untested. This affects scheduler.py and decorators.py
- Testbenching components are all low.
  - [X] scoreboard has some untested features
  - bus
    - [X] `drive`, `capture`, `sample`, and `<=` are unused on the base classe
  - drivers
    - [X] OBP is untested
    - [X] XGMIII is untested
    - [X] AXI4Slave is untested
    - [X] optional signals and some features in AvalonDriver are untested
  - monitors
    - [X] XGMII is untested
  - generators
    - [X] packet.py is untested

## Other

- `__init__.py`
  - [X] `initialize_testbench` isn't covered. This could be because the coverage is started in this function, there is likely some way around this.
- [ ] config.py is untested. It isn't meant to be used in the Python environment by the user. This file should probably not be in the cocotb package.

**Comment by garmin-mjames** [comment]
Coverage of the C++ code should be achievable with `gcov`, as pointed out by @cmarqu on gitter.
I got something rudimentary using `python setup.py develop` with conda/GCC, using these extra args for compiling and linking:
`["--coverage", "-fprofile-arcs", "-ftest-coverage"]`.

The libraries are built in place so the `*.gcno` and `*.gcda` files show up in the repo, and after running some of the tests I was able to generate some `*.gcov` files with coverage results.

I'm not sure how any of this would translate to our CI builds though. codecov supports C++11: https://docs.codecov.io/docs/supported-languages

**Comment by ktbarrett** [comment]
Use lcov. Youll probably need to set up includes/excludes to prevent coverage of external code. Codecov understands lcovs output IIRC.

**Comment by cmarqu** [comment]
Out-of-repo seems to be possible with https://gcc.gnu.org/onlinedocs/gcc/Cross-profiling.html

**Comment by garmin-mjames** [comment]
@cmarqu 
> You must move the data files to the expected directory tree in order to use ... the gcov tool. 
Doesn't this mean we need a copy of the source anyways?

**Comment by ktbarrett** [comment]
```command
CFLAGS="-O0 -g --coverage" LDFLAGS="--coverage" pip install -e .
make
lcov -c -d . --no-external -o cov.info
genhtml cov.info -o coverage
xdg-open coverage/inde.html
```

But VPI coverage isn't being recorded correctly. It might be the object renaming, I'm not sure how gcov works.

**Comment by cmarqu** [comment]
The C++ coverage setup is now tracked in #2088.

**Comment by ktbarrett** [comment]
Hooks were removed: #2508
The testbenching components were removed: #2289
`_initialize_testbench` is now covered as well as it can be: #2400

**Comment by ktbarrett** [comment]
`utils.pack` and `utils.unpack` were removed. `BinaryValue` was removed. `cocotb.memdebug` was removed.

I'm going to mark this as fixed. Another issue can be opened and kept more up to date if need be.
