### ISSUE TITLE
GHDL waveform documentation

### ISSUE THREAD

**Issue by jwrr** [cocotb/cocotb#1977]
I could not find how to make a cocotb+ghdl sim produce a vcd waveform. I eventually tracked it down by looking at makefile.ghdl.  All that's needed is: make SIM=ghdl SIM_ARGS=--vcd=anyname.vcd.  I tried it on the dff example and it seems to work fine.
 
If you're interested, I added a waveform sub-section to the ghdl section of https://github.com/jwrr/cocotb/blob/readme/documentation/source/simulator_support.rst.  I used the Verilator waveform section as a template.

**Comment by umarcor** [comment]
Some references:

- https://ghdl.readthedocs.io/en/latest/using/Simulation.html#export-waveforms
- ghdl/ghdl#1365
- https://github.com/umarcor/pulseview/tree/ghdl/ghdl
