### ISSUE TITLE
Cocotb doesnt recognize variables which start with underscore

### ISSUE THREAD

**Issue by crusader2000** [cocotb/cocotb#2012]
Variables starting with _ like _sw_o  throw the following error. 
```
AttributeError: 'HierarchyObject' object has no attribute '_sw_o'
```
Removing or replacing the underscore helps overcome the error but having support for variables with _ will be very helpful in long term.

**Comment by eric-wieser** [comment]
You can access these with `._id("_sw_o", extended=False)`

**Comment by cmarqu** [comment]
Duplicate of #1315. Please reopen or comment either there or one of the issues linked in #1315 if needed.
