### ISSUE TITLE
1.4.0 not marked as latest release

### ISSUE THREAD

**Issue by bluecmd** [cocotb/cocotb#2053]
Hi,

Right now 1.3.2 is marked as the latest release. Is that correct? Technically it's released after 1.4.0 but this leads to that the GitHub landing page for cocotb says the latest release is 1.3.2 - which maybe isn't what is intended?

![Screenshot_20200908-113503](https://user-images.githubusercontent.com/149442/92459917-90e60100-f1c7-11ea-9666-0c8dbee1a6c6.png)

**Comment by imphil** [comment]
1.3.2 was released after 1.4.0, but it's a separate branch. I have not seen anything on GitHub allowing me to say "this release is newer, but on a stable branch, so don't consider it the latest release". Looks like a GitHub missing feature that we can't do anything about.

**Comment by themperek** [comment]
Some ugly hack (not sure if should do this): https://stackoverflow.com/questions/22822586/swap-latest-release-on-github

**Comment by bluecmd** [comment]
Seems unreasonable :-/

**Comment by ktbarrett** [comment]
We will be releasing 1.4.1 not too far in the future, so 1.4.X will be back on top.
