### ISSUE TITLE
Document the development setup of cocotb

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#2058]
User Story 1: As a new developer to cocotb, I want to know how I need to configure my machine to make changes to the *code base*.

User Story 2: As a new developer to cocotb, I want to know how I need to configure my machine to make changes to the *documentation*.

This overlaps a bit with #2057, but should really be mostly orthogonal.

**Comment by cmarqu** [comment]
See also https://github.com/tpoikela/uvm-python/blob/master/CONTRIBUTING.md
