### ISSUE TITLE
Deprecate Wavedrom

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2066]
It's only used by the endian swapper test. The only direct reference to it is in #695. Before it causes someone a problem, lets remove it. As long as that's okay with @cmarqu.

**Comment by eric-wieser** [comment]
I've only looked at it briefly, but it seems like:
* A neat tool
* A low maintenance burden
* Something we should provide in another repo if we decide it's really not worth leaving in this one.

**Comment by cmarqu** [comment]
I agree that it's worth having around but probably as an extension. In which case we likely want to depend on https://github.com/wallento/wavedrompy, not https://github.com/wavedrom/wavedrom.
