### ISSUE TITLE
Document COCOTB_LIBRARY_COVERAGE envvar

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#2083]
The environment variable ``COCOTB_LIBRARY_COVERAGE`` -
https://github.com/cocotb/cocotb/blob/b2eda5325a1e75ef6bdde4e6523bcb0ac81a3137/cocotb/__init__.py#L160
is not documented.

**Comment by ktbarrett** [comment]
I'm not sure we need to document this, I don't think it's useful for users. Its only for collecting coverage on the cocotb internals.
