### ISSUE TITLE
Deprecate Python 3.5 after the 1.5 release

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2098]
Python 3.5 has reached end of life. I think it is responsible to support it in the current release, but should be deprecated after that. This means we can start using variable type hint syntax and uncondition async generator checks and syntax (including the async generator tests in test_cocotb).

**Comment by imphil** [comment]
Ubuntu 16.04 is the main reason for Python 3.5 support at the moment, but it's EOL in April 2021 as well, which goes together nicely with the plan you propose.

**Comment by cmarqu** [comment]
Being able to rely on at least 3.6 would allow us to use the much more readable f-strings, looking forward to that.

**Comment by ktbarrett** [comment]
Closed by #2422.
