### ISSUE TITLE
Cleanup @cocotb.test(expect_error=True)

### ISSUE THREAD

**Issue by garmin-mjames** [cocotb/cocotb#2117]
#2107 revealed how `expect_error=True` can mask a problem, because any `Exception` raised by the test will mark it as PASS.

This test passes even though the wrong error is causing the failure:

https://github.com/cocotb/cocotb/blob/89e7bd77b1e9ceb3172b4659e267bc4c42217a0f/tests/test_cases/test_discovery/test_discovery.py#L101-L106

These tests should be cleaned up to use `assert_raises` style or provide the expected `Exception` type.

**Comment by markusdd** [comment]
This test is a duplicate or very similar to what is done in test_handle.py

We agreed to merge/move/remove this in PR #2107

**Comment by markusdd** [comment]
@garmin-mjames could you please link PR #2107 to this issue, so this is closed when it gets merged? Thanks.

**Comment by garmin-mjames** [comment]
@markusdd There are other uses that should be modified. The test from #2107 is mentioned as the motivating example that showed how using `True` instead of the expected `Exception` type can lead to an inadvertent PASS. The point of this issue is to investigate the uses of `expect_error=True` and be more explicit where it makes sense to do so.

**Comment by markusdd** [comment]
Ah ok, sorry, I didn't interpret this issue to be a general cleanup task.

**Comment by ktbarrett** [comment]
Passing `True` to `except_error` can also be deprecated.
