### ISSUE TITLE
cocotb download issues

### ISSUE THREAD

**Issue by tsengr0916** [cocotb/cocotb#2122]
I'm confused with the cocotb download web site between https://github.com/cocotb/cocotb and the one in here: https://pypi.org/project/cocotb/#files
 
Which one should I pick for the latest and the greatest version?  For some reason I have problem to download from the files from the https://pypi.org/project/cocotb/#files. Is the server down?

**Comment by cmarqu** [comment]
I was able to download from pypi one minute ago.

**Comment by eric-wieser** [comment]
Note that typically the install process would be to let the `pip` command perform the download for you.
