### ISSUE TITLE
Simulation fail when enabling Verilator FST trace

### ISSUE THREAD

**Issue by alexforencich** [cocotb/cocotb#2131]
Verilator supports FST format tracing through the --trace-fst option.  However, when this option is added, cocotb fails to build it with the following error:

    /usr/lib/python3.8/site-packages/cocotb/share/lib/verilator/verilator.cpp: In function ‘int main(int, char**)’:
    /usr/lib/python3.8/site-packages/cocotb/share/lib/verilator/verilator.cpp:41:23: error: cannot convert ‘std::unique_ptr<VerilatedVcdC>::pointer’ {aka ‘VerilatedVcdC*’} to ‘VerilatedFstC*’
       41 |     top->trace(tfp.get(), 99);
          |                ~~~~~~~^~
          |                       |
          |                       std::unique_ptr<VerilatedVcdC>::pointer {aka VerilatedVcdC*}
    In file included from /usr/lib/python3.8/site-packages/cocotb/share/lib/verilator/verilator.cpp:5:
    ./Vtop.h:235:31: note:   initializing argument 1 of ‘void Vtop::trace(VerilatedFstC*, int, int)’
      235 |     void trace(VerilatedFstC* tfp, int levels, int options = 0);
          |                ~~~~~~~~~~~~~~~^~~
    make[2]: *** [Vtop.mk:61: verilator.o] Error 1

Using --trace builds fine, but the resulting VCD traces are many GB in size.

**Comment by themperek** [comment]
see #2102
