### ISSUE TITLE
GPI: Address DEBUG log spam to cocotb.gpi logger

### ISSUE THREAD

**Issue by marlonjames** [cocotb/cocotb#2141]
There are two places that produce lots of DEBUG log statements in the GPI:

https://github.com/cocotb/cocotb/blob/a9cd7ad2625cd8cbfcde3fb5959fb7316b33b4a2/cocotb/share/lib/gpi/GpiCbHdl.cpp#L94-L100

https://github.com/cocotb/cocotb/blob/6eb637ae1ec4110fb3aa10ef04051fe8ef163108/cocotb/share/include/cocotb_utils.h#L57-L73

They are both related to tracing the program flow between GPI and Python.

I'd like to be able to filter out these messages without losing other DEBUG info on the `cocotb.gpi` logger. I would prefer to have them disabled by default with a way to enable them when debugging cocotb issues.

I don't know what the best approach is. New lower log level (#1226)? New distinct logger with a filter?

**Comment by ktbarrett** [comment]
> New lower log level (#1226)?

Adding `TRACE` as a level, with the corresponding macro functions sound fairly easy to accomplish and conceptually covers both of those chatty cases.

> New distinct logger with a filter?

That's a good bit of work. If you were interested in adding more than one, I'd say build a facility so build more so we can have N. There really are only 4 important numbers: 0, 1, N, and 4 of course... Then we can call out different loggers in the `LOG_*` macros.

**Comment by garmin-mjames** [comment]
@ktbarrett I was leaning towards `TRACE` as well.

`logging.TRACE = 5` ?

**Comment by garmin-mjames** [comment]
Hmm, custom levels can clash with each other. The other approach is probably safer: https://docs.python.org/3.5/howto/logging.html#custom-levels

Thoughts @eric-wieser ?
