### ISSUE TITLE
Set decorator parameters in TestFactory

### ISSUE THREAD

**Issue by kentindell** [cocotb/cocotb#2144]
Is there a way to be able to set the decorator parameters in the test factory? It would be very useful to (for example) be able to define which of the generated tests are expected to fail.

**Comment by ktbarrett** [comment]
`expect_fail` and friends are really only meant for cocotb acceptance testing purposes. You should instead add a parameter to your `TestFactory` for expected failure, and then in the test body add the logic necessary to judge failures. Also, `TestFactory` is a fairly simple construct, you can easily write your own that handles your use case.
