### ISSUE TITLE
Deprecate TestError/expect_error

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#2174]
With the move to using assertions instead of raising exceptions, ``TestError``/``expect_error`` could/should be deprecated. https://github.com/cocotb/cocotb/pull/2170#discussion_r516712751

**Comment by ktbarrett** [comment]
There is one reference that is located in the core libraries [here](https://github.com/cocotb/cocotb/blob/4d4fffaeedd3557601f706e1b5d872b15b0a7a42/cocotb/handle.py#L223), but I'm not sure why. When would iterating over a sub handles result in a `TestError`? I will check coverage to see if this is dead code.

**Comment by garmin-mjames** [comment]
@ktbarrett Looks like it's catching this:
https://github.com/cocotb/cocotb/blob/4d4fffaeedd3557601f706e1b5d872b15b0a7a42/cocotb/handle.py#L959

**Comment by ktbarrett** [comment]
Never trust the Github search feature. Lets me down every time.
