### ISSUE TITLE
Agree on and add clang-format configuration

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#2189]
Our C/C++ code is currently a mix of styles and not auto-formatted. I'm proposing to add a clang-format configuration to solve that.

In addition, we should agree on a C/C++ coding style. I tried to play around with clang-format to get it to match what we currently have, but our style is so inconsistent that it will be a rather large diff anyways. I'd therefore go with a full reformat with a standard coding style already supported in clang-format.

As usual, this is a matter of taste, but also doesn't matter much. I'd go with the Google C/C++ coding style (https://google.github.io/styleguide/cppguide.html), which is rather comprehensive and well supported in clang-format. (It has a couple things in there which I personally find odd, but that's expected in any style and I ultimately don't care enough.)

- [ ] Agree on a style
- [ ] Add a clang-format config file to the tree
- [ ] Reformat all C/C++ code with clang-format.
- [ ] Add clang-format lint to CI.

**Comment by ktbarrett** [comment]
Need to take #1148 into consideration. It had to do with the `Python.h` include being moved around, but I'm afraid I forget the details.

**Comment by ktbarrett** [comment]
Apparently that's not an issue, I just tried it. I'm fine with the Google code style. [clang-format-lint-action](https://github.com/DoozyX/clang-format-lint-action) can be used for linting.

**Comment by garmin-mjames** [comment]
Google style is fine with me. We may be able to use [include-what-you-use-action](https://github.com/emilgedda/include-what-you-use-action) for include checking.
