### ISSUE TITLE
"make clean" on installed Cocotb spits out errors

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#221]
Typically the install has been done by a privileged account and the user shouldn't be able to modify the compiled libs.  However this causes `make clean` to report errors.

Although these errors can be safely ignored, it would be better not to report an error at all since this is expected behaviour.

**Comment by themperek** [comment]
The way the install process works have changed 2 times since 2015 and this seem irrelevant at this point.

Please feel free to reopen in case of trouble.
