### ISSUE TITLE
Warn of upcoming deprecations/removals

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#2216]
We should have a section like that in the docs of the 1.5 release: https://docs.antora.org/antora/2.3/whats-new/#caution-coming-soon

_Originally posted by @cmarqu in https://github.com/cocotb/cocotb/issues/1642#issuecomment-731851364_

**Comment by ktbarrett** [comment]
Could we perhaps just link to the 2.0 milestone and ensure we are marking all our great ideas for 2.0?

**Comment by cmarqu** [comment]
Yes, that, and we should also [link to the deprecations](https://github.com/cocotb/cocotb/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0+label%3Atype%3Adeprecation) specifically.

**Comment by cmarqu** [comment]
Warn of Python 3.6+ being required.

**Comment by ktbarrett** [comment]
I don't think we need to do this since we decided to do a 1.6 release. The 'latest' documentation after release could have a warning on the home page about it being a breaking release, and of course 1.6 will be just be a bunch of warnings about what we have changed.

**Comment by imphil** [comment]
* We're done with 1.9.
* I don't see much actionable work here anyways: we do have a deprecations section in the release notes, and users get notified via in-product messages. That's probably good enough, since nobody implemented anything better since this issue was created 4 years ago.
