### ISSUE TITLE
Add gcovr to tox config

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#2220]
We could add gcovr back to show the coverage results when running tox locally.

I also think Python/C++ coverage should be optional when running locally through a `-coverage` suffix to the tox env, but that can be a different PR.

_Originally posted by @garmin-mjames in https://github.com/cocotb/cocotb/issues/2155#issuecomment-729886895_

**Comment by garmin-mjames** [comment]
I have a branch printing coverage results, and making coverage non-default for local `tox` runs, but I ran into an issue with `tox-gh-actions` https://github.com/ymyzk/tox-gh-actions/issues/44.

I didn't want the `*-coverage` builds to be part of the default run, but `tox-gh-actions` only runs environments defined in `envlist`.

**Comment by ktbarrett** [comment]
The default run currently runs all combinations of python version and OS. The default run is already broken, is it not?

**Comment by garmin-mjames** [comment]
@ktbarrett that's true. If we don't care about `tox -l` having every combination listed, I could make a PR now.

**Comment by ktbarrett** [comment]
Does coverage take a considerable amount of time? Is there ever a reason to turn it off?

**Comment by garmin-mjames** [comment]
@ktbarrett on my PC I saw basically no difference in runtime.

If the coverage print-outs are added, then that will be what you see after running `tox` instead of the regression results currently shown.

Another option is to just not print out the coverage results and leave that to the user. The results are saved outside of the tox run.

**Comment by imphil** [comment]
Closing as we're not using tox any more. The coverage reporting is available for local users through nox.
