### ISSUE TITLE
Support changing verilator dump file name

### ISSUE THREAD

**Issue by alexforencich** [cocotb/cocotb#2241]
It may be useful to be able to change the verilator waveform dump file name.  Right now, it's fixed at either dump.vcd or dump.fst, depending on whether --dump or --dump-fst is specified (https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/verilator/verilator.cpp#L46-L57).  Seems like this would not be particularly difficult to add as a command-line option to the verilated executable file.

**Comment by ktbarrett** [comment]
This is now supported by supplying the `--dump-file` option to the verilated binary.
