### ISSUE TITLE
Update regression tests for Verilator failures/errors

### ISSUE THREAD

**Issue by marlonjames** [cocotb/cocotb#2264]
There are several errors or test failures in the regression tests related to Verilator lacking features:
- Force/Release
- Multi-dimensional arrays
- VPI access to struct members
- iteration discovery count
- possibly others...

Update the tests to expect failure/error where appropriate.

**Comment by ktbarrett** [comment]
Also #2248.

**Comment by marlonjames** [comment]
Closing in favor of #3194
