### ISSUE TITLE
Install problems on windows

### ISSUE THREAD

**Issue by blacksburg98** [cocotb/cocotb#2269]
copying cocotb\share\lib\verilator\verilator.cpp -> build\lib.win32-3.8\cocotb\share\lib\verilator
  running build_ext
  error: [WinError 2] The system cannot find the file specified

I'm using this cmd.
pip install --global-option build_ext --global-option --compiler=mingw32 cocotb
It fails on both 32 and 64.

**Comment by ktbarrett** [comment]
@blacksburg98 You are going to need to give more information than that if you want help. Post the full error output from `pip`. What exactly do you mean by "It fails on both 32 and 64."?
