### ISSUE TITLE
Run with Python 3.6.0 in CI

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#2284]
For the 2.0 release we will say that we require Python in version 3.6+, meaning people can expect Python 3.6.0 to work.
Thus we also should use this version in CI. Right now, the `py36` environment of tox yields 3.6.12.

(We also run 3.5.10 for "3.5+" right now, but it's probably not worth changing this in the few remaining weeks until 2.0.)

**Comment by cmarqu** [comment]
https://stackoverflow.com/a/62113259 seems relevant.

**Comment by ktbarrett** [comment]
I think in the setup-python action we use in CI, you can specify patch versions. We just don't currently. And this is definitely worthwhile. We had the issue in the spring where a difference in patch version broke a large section of the Python ecosystem.
