### ISSUE TITLE
Move to a src/ layout

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2286]
The benefits of putting packages in a `src/` directory in Python/pip projects has been discussed for a few years now. The advantages include running coverage collection without doing an editable install and testing what is installed and not what is local. We have to use an editable install in our tox to be able to correctly collect coverage. This has the disadvantage of not being PEP517 compliant in the future (well maybe they will add specifications for editable installs, but I doubt it), and developers have to clean all the build artifacts out every time we run `pip`/`tox` to prevent using potentially out of date C++ libraries which aren't rebuilt if they exist. And editable installs just fundamentally break isolation as provided by tox.

Preliminary testing of a move to a `src/` layout shows that the directory rewriting introduced in #2155 break paths and the build process once we move to a `src/` layout. I'm sure there is some way around this.

**Comment by eric-wieser** [comment]
I think there are ways to make coverage work without an editable install, but also I have no opposition to a src folder
