### ISSUE TITLE
Documentation release notes version is off

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2337]
It's currently showing [0.1.0.dev50+g9f27135.d20210112](https://docs.cocotb.org/en/latest/release_notes.html#cocotb-0-1-0-dev50-g9f27135-d20210112-2021-01-12). Which implies that the RTD build isn't cloning tags.

It is cloning tags, but it's limited it's depth to 50 ([see here](https://readthedocs.org/projects/cocotb/builds/12746800/)) which is why the version stops at dev50 and not dev3071. We should probably up that if we can.

I found [this](https://github.com/readthedocs/readthedocs.org/issues/5031) issue which states that lifting shallow clones is a feature flag. And another that states the build area should be wiped after changing this setting. @eric-wieser @imphil? The flag is `DONT_SHALLOW_CLONE`.

**Comment by imphil** [comment]
Filed https://github.com/readthedocs/readthedocs.org/issues/7848

**Comment by imphil** [comment]
Fixed now, https://docs.cocotb.org/en/latest/release_notes.html shows the correct version.
