### ISSUE TITLE
[Riviera-PRO] vpi_register_cb returns reused callback handle

### ISSUE THREAD

**Issue by marlonjames** [cocotb/cocotb#2344]
Cocotb version: master
Simulators: Riviera-PRO 2019.10+ 64-bit Linux, Active-HDL 11.1 32-bit Windows 10

VSimSA is re-using callbacks for `cbValueChange`.

If we have a `cbValueChange` callback handle for a signal such as `dut.clk`, say for a `RisingEdge` trigger.
If a `FallingEdge` trigger for the same `dut.clk` signal is primed, then it will register for a new `cbValueChange` callback on the same signal.
Riviera gives us back the same handle we already have for `RisingEdge` (but doesn't update the callback data for the new `FallingEdge` object).
When the original `RisingEdge` trigger is cleaned up, which calls `vpi_remove_cb` on the shared handle, the callback handle is set to NULL, and the state is set to `GPI_FREE`.
On the falling edge of `dut.clk`, the callback fires again but with the original `RisingEdge` callback object that is `GPI_FREE` so nothing happens, it just returns to the simulator.

I'm pretty sure this falls afoul of the VPI standard. I found this, which is in **38.36.1.1** in context of callbacks on statements:

> Multiple calls to `vpi_register_cb()` with the same data shall result in multiple callbacks.

_Based on https://github.com/cocotb/cocotb/pull/2338#issuecomment-759778275_

**Comment by imphil** [comment]
Filed a support case with Aldec, case number SPT81300.

**Comment by imphil** [comment]
The 2023.04 release notes mention this issue is resolved.

@marlonjames Is there something we want to do as result of that on the cocotb side?

**Comment by marlonjames** [comment]
`test_both_edge_triggers` should now pass with riviera 2023.04:
https://github.com/cocotb/cocotb/blob/c34c2bc5cf2408c0c5c386d5d9c139ecf6453889/tests/test_cases/test_cocotb/test_edge_triggers.py#L232-L244

**Comment by imphil** [comment]
I confirmed that this issue is fixed with Riviera 2023.10. https://github.com/cocotb/cocotb/pull/3471 removes the test exclusion.
