### ISSUE TITLE
Recommend checking for TOPLEVEL

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2364]
If TOPLEVEL is not set `iverilog` fails with an obscure error message because there is nothing after the `-s` option.  I recommend that `Makefile.sim` check for TOPLEVEL and (and other required variables) and give a clean error message.

**Comment by ktbarrett** [comment]
This issue is specific to Icarus. Other simulators allow `TOPLEVEL` to be empty, which in cocotb will return the root handle as the dut object, and not some entity.

**Comment by haroonshafique-10xe** [comment]
> This issue is specific to Icarus. Other simulators allow `TOPLEVEL` to be empty, which in cocotb will return the root handle as the dut object, and not some entity.

@ktbarrett I tried running it without setting `TOPLEVEL` for `icarus` as well as `verilator`, it failed for both.

**Comment by ktbarrett** [comment]
Thanks to @haroonshafique-10xe this was closed by #2547.
