### ISSUE TITLE
Why does cocotb.test() have parentheses?

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2366]
My linter complains that 

```
@cocotb.test()
async def hello_world():
    print("Hello, world")
```

Is missing a parameter named `f` in the decorator call. I rarely see parenthesis in a decorator. Why are there parenthesis here?

**Comment by eric-wieser** [comment]
Which linter are you using? I'm not surprised that we're confusing it, but if we know the linter we might be able to teach it otherwise.

> I rarely see parenthesis in a decorator. Why are there parenthesis here?

So that you can do `@cocotb.test(expect_fail=True)`

**Comment by raysalemi** [comment]
It's the one in PyCharm.

How does the test determine whether fail happened or not?

**Comment by raysalemi** [comment]
A better way to ask is, "How do I tell cocotb that a test failed?"

**Comment by eric-wieser** [comment]
Using `assert False` makes a test fail, if that's your question

**Comment by raysalemi** [comment]
So cocotb expects AsssertionError and marks a test as failed if it sees it?

**Comment by eric-wieser** [comment]
Yes, exactly

**Comment by raysalemi** [comment]
Thanks!
