### ISSUE TITLE
What is the `f` Argument in cocotb.test()?

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2367]
What does the `f` argument do below? I cannot find it in the code.
https://github.com/cocotb/cocotb/blob/f65e08a652f5f34357bda733ca397f657a73a3c0/cocotb/decorators.py#L545-L547

Also, what is the difference between `expect_fail` and `expect_error`?

(BTW. `f` is what was triggering my linter.)

**Comment by eric-wieser** [comment]
It's the test itself, and it's just passed into the coroutine constructor:

https://github.com/cocotb/cocotb/blob/f65e08a652f5f34357bda733ca397f657a73a3c0/cocotb/decorators.py#L572

There's some magic in place to ensure that `isinstance(some_test, cocotb.test)` true, which is documented here:

https://github.com/cocotb/cocotb/blob/f65e08a652f5f34357bda733ca397f657a73a3c0/cocotb/decorators.py#L429-L449

**Comment by raysalemi** [comment]
Oh, right. Regular decorator behavior.

Personally, I would have let the test-writer decide on the definition of
fail and leave the decorator as simple as possible, but of course that's
cheap engineer talk.
