### ISSUE TITLE
iterating over dut handle doesn't return any objects

### ISSUE THREAD

**Issue by lukedarnell** [cocotb/cocotb#237]
I'm running the discover_module_values testcase in examples/functionality/tests/test_discovery.py

I would expect the testcase to iterate over the ports in sample_module.v
But the 

``` python
for thing in dut:
```

loop doesn't return anything.

I'm running with ius.
Has anyone had any success running this testcase?
What should the output look like?

**Comment by cmarqu** [comment]
This is fixed for me in IUS (Xcelium).

**Comment by themperek** [comment]
This should be solved by now. Please reopen in case of issues.
