### ISSUE TITLE
Make codecov reporting more reliable

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#2397]
We see rather flaky codecov reporting, and I've identified some issues with it.

- [x] clang and macos uploads fail. We can safely disable them. #2393
- [x] Private CI uploads are done with the Python uploader, which doesn't support Azure Pipelines. That leads to missing commit metadata. The bash uploader should do the trick. (https://github.com/cocotb/cocotb-private-ci/commit/f3c6fa188fb11319e08d4b718507855780b6a3d7)
- [x] The GH Actions uploader doesn't tell which matrix job the coverage is from. Add that. (https://github.com/cocotb/cocotb/pull/2398)
- [x] We don't get coverage form Windows runs. See https://github.com/cocotb/cocotb/pull/2398#issuecomment-776726344. PR in #2399
- [x] Delay codecov notifications until all builds are in.

**Comment by marlonjames** [comment]
Delaying codecov comment: https://docs.codecov.io/docs/pull-request-comments#after_n_builds

**Comment by imphil** [comment]
Yeah, the PR is already waiting on my side :-)

**Comment by imphil** [comment]
The most recent set of updates seems to do the trick for now. No Windows C/C++ coverage yet, that's tracked in #2406.
