### ISSUE TITLE
Relese cocotb 1.5.0

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#2415]
Milestone: https://github.com/cocotb/cocotb/milestone/15

Release process checklist:
- [x] Close all issues blocking the milestone
- [x] prepare RC release
- [x] prepare release announcement email
- [x] tag release
- [x] test release build on PyPi
- [x] send out announcement to mailing list

**Comment by imphil** [comment]
I'm planning to do 1.5.0rc1 on Monday, please either get the remaining docs PRs in by then, or they'll need to wait until the next release. 
CC @cmarqu

**Comment by ktbarrett** [comment]
Don't forget to run towncrier!

**Comment by cmarqu** [comment]
https://github.com/cocotb/cocotb/wiki/Release-Process - needs a bit of clean up, but towncrier is listed.

**Comment by imphil** [comment]
I just pushed rc2 containing a single fix, let's give it a week until March 11 to see if something major comes up and do the release otherwise.

**Comment by ktbarrett** [comment]
Guess it's too late to merge #2426?

**Comment by imphil** [comment]
No problem at all, RCs are cheap. Merge it, and I'll do another one tomorrow.

**Comment by imphil** [comment]
1.5.0 is out now.
