### ISSUE TITLE
Document RunningTask / RunningCoroutine

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2454]
`RunningTask.join` and `RunningTask.kill` are mentioned, but there is no treatment of `RunningTask` proper, or how to check if the task has finished, etc.

**Comment by marlonjames** [comment]
Should `RunningTask._finished` be a public property?

**Comment by ktbarrett** [comment]
I *should* look like an [asyncio.Task](https://docs.python.org/3/library/asyncio-task.html#task-object) IMO. That would mean we should add a `done()` method.

**Comment by ktbarrett** [comment]
This is better now. Also these two classes are now just `Task`.
