### ISSUE TITLE
Simulator crash while running COCOTB with xcelium 

### ISSUE THREAD

**Issue by thmani** [cocotb/cocotb#2474]
Hi All,
I am trying to run my first cocotb simulations using xcelium. I am stuck at tool crash issue.

* the cocotb version used - 1.5.0rc3,
* the operating system and version - Linux 64 bit,
* the simulator and version - cadence xcelium 20.09.008 (64 bit),
* the Python version - 3.6, system 
* (part of) the log file 

I used pip3.6 to install cocotb version 1.5.0rc3. 
Can anyone please help to resolve this crash issue?

`
![image](https://user-images.githubusercontent.com/57434296/111309958-c5e27d00-865c-11eb-94d1-99f64e17f9de.png)

`
<!--

**Comment by imphil** [comment]
The trace shows that you're using Python 2.7 and something is a 32 bit version. Did you ensure that you are running cocotb with Python 3? How did you install cocotb?

**Comment by ktbarrett** [comment]
This is an environment issue, but I can't tell who's at fault here.

Not finding "encodings" usually implies PYTHONHOME is being set to something different from where the python executable/libpython is found. I also see in the *internal* traceback, Python. It, is also screwed up using two different Python installations. I'm wonder if Cadence is using Python internally and is setting PYTHONHOME just like they set LD_LIBRARY_PATH? Pinging @cmarqu can you confirm?

But it seems like your Xcelium install is also broken since its using multiple Python installations, including a system installation of Python 2.7 that's 32 bit? What OS are you using? "Linux" is a kernel. Red Hat 6? Ubuntu 16.04? Etc?

**Comment by cmarqu** [comment]
No, my Xcelium does not touch  my `PYTHONHOME` which is set to the Anaconda location that I'm using.
FWIW, I checked this with `make SIM=xcelium SIM_ARGS="-input \"@env | grep PYTHON\" -input \"@exit\""` in the `simple_dff` example.

**Comment by thmani** [comment]
Hi All,
Similar issue was reported by @juliusbaxter
https://github.com/cocotb/cocotb/issues/1945 

**Workround proposal was:
It indeed did turn out to be an RPATH problem in xrun and xmelab. They bundle a Python3 install with the Xcelium install, the RPATH is set to their local lib64 area, and when running with LD_DEBUG=libs it was clear it was always picking up libpython3.6m.so.1.0 from its local install and not the system one.

I've managed to make cocotb 1.4 work against Xcelium 1909002 by moving those Python 3 libraries out of the Xcelium local lib64 directory.** 

I am trying to move Python libraries out of xcelium library. Please help me if anyone knows how to do it.
I am new to python world :)

**Comment by themperek** [comment]
>I've managed to make cocotb 1.4 work against Xcelium 1909002 by moving those Python 3 libraries out of the Xcelium local lib64 directory._

It should not be needed to do anything like this for 1.5. But I am not 100% sure.

**Comment by thmani** [comment]
@ktbarrett 
Which python3.6 --> ./cocotb/first_ctb/bin/python3
cocotb-config --libpython --> /usr/lib64/libpython3.6m.so.1.0

@themperek 
I installed cocotb using "
![image](https://user-images.githubusercontent.com/57434296/111593824-aa958000-87ca-11eb-9f9e-21aecdf03547.png)

I think in 1.5.0 version they fixed libpython issue using embed.cpp code(not sure about this)
But I dont see this file in my cocotb installation. I only see the verilator
first_ctb> ls lib/python3.6/site-packages/cocotb/share/lib/
verilator/

**Comment by thmani** [comment]
Also I do not see below files in my cocotb library. Could this be a problem as I see from error message that crash happens while executing coctotb.gpi method?

![image](https://user-images.githubusercontent.com/57434296/111621481-55686700-87e8-11eb-975a-177d2e38285f.png)

**Comment by ktbarrett** [comment]
@thmani You won't see any of those files in your installation, they are compiled into shared libraries under `$(cocotb-config --prefix)/cocotb/libs`. The `Verilator.cpp` is necessary though for Verilator support.

`cocotb-config --libpython` seems to be correctly finding libpython3.6m.so in your environment. So the correct libpython is being loaded and the correct Python libraries (your system ones) should be used. ***Unless Xcelium beats you to the punch***. I think you are going to need to do some library level debugging (Adding `LD_DEBUG=libs` environment variable) to see if Xcelium is loading libpython before us. @cmarqu Could you help us again?

**Comment by ktbarrett** [comment]
@thmani Could you also send me a dump of you running `LD_DEBUG=libs xrun`?

**Comment by thmani** [comment]
@ktbarrett  sent you the log file after setting environment variable LD_DEBUG=libs

**Comment by ktbarrett** [comment]
I see it "searching" for `libpython3.6m.so` as a dependency of `libcocotbvpi_ius.so` before the VPI library is initialized. This is not cocotb 1.5 behavior. Ensure you have cocotb 1.5.0 install in the environment where you think it is.

**Comment by thmani** [comment]
@ktbarrett 
Now I have installed cocotb 1.5.1, but I still get the same error. any more ideas to try out?

**Comment by themperek** [comment]
@thmani Please minimum provide log file.

**Comment by thmani** [comment]
@themperek : Please let me know how I can share the log file directly to you. My email:thmani@gmail.com

**Comment by themperek** [comment]
It looks like something nontrivial environment miss-configuration. 
I would suggest installing and using [conda](https://docs.conda.io/en/latest/miniconda.html) (in local/home folder) that should isolate you from the system.

**Comment by thmani** [comment]
@themperek, Sorry for the very basic question..
I tried installing cocotb using conda (conda install cocotb). But cocotb is not found in default channels.
I have downloaded the cocotb 1.5.1 code. Any idea how to install this using conda?

**Comment by ktbarrett** [comment]
@thmani `pip install cocotb`

**Comment by thmani** [comment]
@ktbarrett. Thanks for the quick feedback. I started all over again without virtual env this time.
I tried below steps:
1. mkdir cocotb
2. pip3.6 install cocotb --user
3. setenv PATH ${PATH}:/$USER/.local/bin
4. cocotb> cocotb-config --version
Traceback (most recent call last):
  File "/$USER/.local/bin/cocotb-config", line 7, in <module>
    from cocotb.config import main
  File "/$USER/.local/lib/python3.6/site-packages/cocotb/__init__.py", line 43, in <module>
    import cocotb.handle
  File "/$USER/.local/lib/python3.6/site-packages/cocotb/handle.py", line 38, in <module>
    from cocotb import simulator
**ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /$USER/.local/lib/python3.6/site-packages/cocotb/libs/libgpi.so)**

5. strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
XXXXXXXXX ....
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

6. install gcc/4.9.1
7. cocotb-config --version
Traceback (most recent call last):
  File "/$USER/.local/bin/cocotb-config", line 7, in <module>
    from cocotb.config import main
  File "/$USER/.local/lib/python3.6/site-packages/cocotb/__init__.py", line 43, in <module>
    import cocotb.handle
  File "/$USER/.local/lib/python3.6/site-packages/cocotb/handle.py", line 38, in <module>
    from cocotb import simulator
**ImportError: /opt/dsard/gcc/4.9.1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /$USER/.local/lib/python3.6/site-packages/cocotb/libs/libgpi.so)**
8. strings /opt/dsard/gcc/4.9.1/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
XXXXXXXXX ....
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH

any idea why this doesnt work even after updating gcc version?

**Comment by thmani** [comment]
Hi All, Thanks a lot for your support. I fixed the issue after moving out of local virtual env and swithching to  gcc version 8.2.0.
Thanks to @themperek and @ktbarrett !

**Comment by ktbarrett** [comment]
@thmani That's good news! We will investigate why virtualenv might be causing problems.

Also, your issue with GLIBCXX_3.4.21 sounds like an environment issue as well. Your cocotb was compiled with a newer GCC and against a newer libstdc++ than the one it is picking up from your environment. You should make sure the same GCC/Clang/MSVC you compile with is the one in your environment when executing.
