### ISSUE TITLE
Improving cocotb output formatting

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2564]
Following on #2436.

Right now, test outputs looks like this.

![image](https://user-images.githubusercontent.com/22162772/122325831-e686d100-cef0-11eb-92be-689cc863be52.png)

Notice the following:
* Most things aren't highlighted
* Starting the test `Running test: ...` is BG highlighted blue
* `Test Passed` is not highlighted
* `Test Failed` is FG highlighted red
* FAIL line in summary is BG highlighted red (and the coloring includes the newline =/)
* The final summary is also not aligned with the per-test summary

Maybe it's just me, but I think this could be improved. What are your opinions?

**Comment by ktbarrett** [comment]
Another thing that could be improve may be startup and shutdown messages.

**Comment by cmarqu** [comment]
Slightly related: #2320

**Comment by cmarqu** [comment]
Maybe we could collect example output of other programs. AFL is one such example that I like: https://www.youtube.com/watch?v=uj1FTiczJSE&t=820s

**Comment by ktbarrett** [comment]
It seems the failure red BG highlighting extending passed the end of the summary is an issue specific to Windows Terminal and likely the line-endings support.

I propose we merge the summary into the PASS/FAIL table. A final line of the PASS/FAIL table could report totals: Somehting like this:

```
     0.00ns INFO     ********************************************************************************
                     ** TEST                    PASS/FAIL  SIM TIME(NS)  REAL TIME(S)  RATIO(NS/S) **
                     ********************************************************************************
                     ** test_module.test_pass     PASS            0.00          0.00         1.99  **
                     ** test_module.test_fail     FAIL            0.00          0.00         1.99  **
                     **                            1/1            0.00          0.00         0.99  **
                     ********************************************************************************
```

**Comment by ktbarrett** [comment]
Perhaps we can also list skipped tests as `SKIP` rather than `N/A` and count those towards the total?

**Comment by ktbarrett** [comment]
I think between #2618 and #2619, this has been accomplished.
