### ISSUE TITLE
Pass tests with Questa 2021.2

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#2579]
We currently fail some tests with Questa 2021.2. Go through the logs at https://dev.azure.com/fossi-foundation/cocotb-private/_build/results?buildId=2314&view=results and fix them (or file individual issues for them)

(Sorry, this log is only available to cocotb maintainers at the moment.)

**Comment by ktbarrett** [comment]
xref #834. In fact, I'll close that issue and we can continue to track the issues here. The Riviera issues are already accounted for in some way seeing as the CI runs successfully.
