### ISSUE TITLE
Document how to use `pdb_attach` to interrupt and debug a hanging simulation process

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2582]
Many times when debugging new Components I end up in a position where the simulation is running, but nothing is happening. In those cases it would be nice to break into a debugger and inspect the state of the test to find out why it's hung. This could be done by [registering a signal handler that would break into pdb](http://blog.devork.be/2009/07/how-to-bring-running-python-program.html), or [remote pdb](https://github.com/ionelmc/python-remote-pdb) for simulators that capture stdin, like Questa. 

Maybe this isn't a good idea to include in the core, but another good justification for #1225.

**Comment by eric-wieser** [comment]
See also https://pypi.org/project/pdb-attach/, which would probably make this very easy to do today, assuming we don't get screwed by the embedded debugger.

**Comment by ktbarrett** [comment]
Just tested this out with the matrix_multiplier example by adding the `pdb_attach.listen()` call to the top of the test and it works. I'll consider this feature out-of-scope, but also working and tested.

**Comment by eric-wieser** [comment]
I think the use case is common enough here that it might be worth mentioning `pdb_attach` in our documentation.

**Comment by ktbarrett** [comment]
Some basic debugging tutorials are appropriate. This can definitely be mentioned in them.

**Comment by ktbarrett** [comment]
The docs now have documentation on using `remote_pdb`.
