### ISSUE TITLE
 cannot merge previous GCDA file: corrupt arc tag (0x00000003)

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2627]
I've just done a pull from the latest version and now tox gives this error message on MacOS:

```
profiling: /Users/raysalemi/repos/cocotb/build/temp.macosx-10.9-x86_64-3.8/cocotb/libs/libgpilog/cocotb/share/lib/gpi_log/gpi_logging.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000003)
```

Any suggestions on what to clean out to resolve this?
Ray

**Comment by eric-wieser** [comment]
Try deleting the `build` directory?

**Comment by raysalemi** [comment]
Thanks. I wasn't sure which one to delete.
