### ISSUE TITLE
Delete branches?

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2639]
Do we delete our branch once the pull request goes through?

**Comment by ktbarrett** [comment]
You can go into the PR and at the bottom there should be a button to delete the branch.

**Comment by raysalemi** [comment]
Yes. I didn't know if we used it.

**Comment by eric-wieser** [comment]
The branches in question are in your copy of the repository at https://github.com/raysalemi/cocotb, and do not exist here.

What you choose to do with your copy of the repo (within the scope of the license terms) is entirely up to you!

**Comment by raysalemi** [comment]
Ah, thanks!
