### ISSUE TITLE
When re-running xcelium simulation cocotb is not running. 

### ISSUE THREAD

**Issue by ronple** [cocotb/cocotb#2648]
Hi,

After running xcelium simulation I re-run simulation but cocotb testbench is not driving any signal as it should.
Here is the run info:    
- cocotb:  _1.5.2_
- OS: _centos7_
- xcelium:  _xrun(64)  20.09-s002:_
- python: _3.6_
- log file:  [sim.log](https://github.com/cocotb/cocotb/files/6912429/sim.log)

Is the fact that the log shows that it is shutting down after the 1st run causing the re-run not to work after it?
is there a way to change it?

Regards,
ronple

**Comment by cmarqu** [comment]
The "Shutting down" is a harmless exit message.
Do the tests and examples of cocotb run successfully for you?

**Comment by ronple** [comment]
My test is running successfully.
The problem is that once the test is finished I am re-running it from the xcelium simulation side and the TB is not running at all.

**Comment by ktbarrett** [comment]
See the [startup hook](https://github.com/cocotb/cocotb/blob/2b5b820c4ded3cb22852993471dcb99b1eadf326/cocotb/share/lib/vpi/VpiCbHdl.cpp#L469-L476). Looks like Xcelium/IUS does something different for startup. Not sure why, there is no note. You could try removing that condition and see if that works? Or there is `vpiStartOfRestart` that might also work.

**Comment by marlonjames** [comment]
It's difficult for VPI/VHPI applications when the simulators don't support the necessary callbacks...

**Comment by ktbarrett** [comment]
Rerunning simulations is not a feature that cocotb currently supports.
