### ISSUE TITLE
Publish with PyPI

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2650]
For 1.6 and the future. It might be a good idea to automate the release processing using this action provided by PyPA. https://github.com/marketplace/actions/pypi-publish

**Comment by eric-wieser** [comment]
I had in my head that we already did that. Has @imphil been doing it manually this whole time?

**Comment by imphil** [comment]
No, it's automatic. See https://github.com/cocotb/cocotb/blob/master/.github/workflows/pypi-upload.yml.
