### ISSUE TITLE
Does cocotb recommend using .value?

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2671]
Is this the recommended way to get values?

```python
                self.cmd_mon_queue.put_nowait((int(self.dut.A.value),
                                               int(self.dut.B.value),
                                               int(self.dut.op.value)))
```

Or does one leave off `.value`

**Comment by cmarqu** [comment]
In the docs, we recently switched to always use `.value` even when not strictly needed, because it reduces the frustration level of new users who might have to hunt for cases where they are missing it /when/ it's needed.

**Comment by raysalemi** [comment]
So the recommendation is to always use it.  Thanks!

**Comment by themperek** [comment]
I think it can be closed. If not please reopen.
