### ISSUE TITLE
Generating random stimulus using the Seed?

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2700]
I'm trying to figure out how **cocotb** generates random stimulus using the seed.

The `generator` section has several mechanisms that have been deprecated since 1.4 but I don't see the new mechanisms. Could I get a pointer to those docs?

**Comment by imphil** [comment]
You can use any function from Python's `random` module (https://docs.python.org/3/library/random.html), e.g. `random.randint()`. The seed is passed on to it: 
https://github.com/cocotb/cocotb/blob/c9e69167615d470f428b9ee9005116969ac3d886/cocotb/__init__.py#L298-L313

**Comment by raysalemi** [comment]
Great!  Now I don’t need to change my code examples.
