### ISSUE TITLE
Broken string formatting in quickstart guide

### ISSUE THREAD

**Issue by Ben1152000** [cocotb/cocotb#2705]
When running the first example in the [quickstart guide](https://docs.cocotb.org/en/stable/quickstart.html), a type error is raised by the following line:
```
dut._log.info("my_signal_1 is", dut.my_signal_1.value)
```
Changing the line to this prevents the error:
```
dut._log.info("my_signal_1 is %d", dut.my_signal_1.value)
```
There are several other examples of this in the guide, ideally they should all be fixed in the same way.

**Comment by cmarqu** [comment]
At some point it would probably be beneficial to use `.. testcode::` et al. (see https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) but not in a PR for this bug.
