### ISSUE TITLE
Find a replacement for xunitparser

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2714]
The project has not been maintained since 2014 and is now causing [installation failures](https://github.com/cocotb/cocotb/runs/3635193264?check_suite_focus=true#step:25:106). WE should look for a new project to replace it with, or find someone to take over the project, make the fix, and upload a new version.

**Comment by themperek** [comment]
Is xunitparser actully used anywhere?

**Comment by ktbarrett** [comment]
Hmmm. I figured it was used by something, but it does not appear to be. xref #234.
