### ISSUE TITLE
Does cocotb support the vivado emulator?

### ISSUE THREAD

**Issue by qgzln** [cocotb/cocotb#2727]
Does cocotb support the vivado emulator?Do you plan to support the vivado emulator ?

**Comment by ktbarrett** [comment]
cocotb does not support the Vivado simulator and cannot because Vivado does not provide the VPI, VHPI, FLI, or similar procedural interface.

**Comment by MrDrGrumpy** [comment]
> cocotb does not support the Vivado simulator and cannot because Vivado does not provide the VPI, VHPI, FLI, or similar procedural interface.

Would the Xilinx Simulator Interface (XSI) provide a similar alternative to the VPI?

**Comment by ktbarrett** [comment]
> Would the Xilinx Simulator Interface (XSI) provide a similar alternative to the VPI?

No, it's missing a serious amount of functionality necessary for cocotb to work.

**Comment by bp-ouhaha** [comment]
Nowadays, there is DPI: https://docs.xilinx.com/r/en-US/ug900-vivado-logic-simulation/Direct-Programming-Interface-DPI-in-Vivado-Simulator

Would that be enough?

**Comment by marlonjames** [comment]
No, cocotb relies on VPI callbacks.

**Comment by themperek** [comment]
You can try https://github.com/themperek/cocotb-vivado. It is early version and  very limited because of limited XSI interface.
