### ISSUE TITLE
Clarity on the issue of restarts

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2733]
I need to find clarity on the question of whether cocotb supports the Questa `restart -f` command or restart commands in any simulator.

As a definition: `restart -f` brings a simulation back to time zero without reelaborating the design. One would like to modify a cocotb testbench and press the GUI restart button, or type `restart -f` and run the simulation from the start with a modified testbench.

It's unclear in various conversations whether cocotb intends to support this functionality.  The situation is confused by the fact that cocotb works with some simulators on restart and not others.

I can see three options:

1. **cocotb** is not expected to support restart on any simulator. If it works in a given simulator that is a happy accident.

2. **cocotb** supports restart in simulators where someone has done the work to make it support restart.

3. **cocotb** is intended to support restart in all simulators, but there is a bug with regards to Questa.

Which of the three is the correct answer?  We (Siemens) need to know so we can support our customer properly.

**Comment by riteshmentor** [comment]
Hi Marlon,

I am looking to find out the exact support that may help achieve a clean restart on Questa. Towards that, I need some additional debug help from you. What I want to find out is the following :

1) In the file "GpiCommon.cpp", there is a function named "gpi_embed_init" - which seems to represent a StartOfSimulation callback in both the VPI and VHPI implementations.
2) When I start up a simulation in Questa, I see the flow coming into this function and going to "embed_sim_init" in the file "gpi_embed.c"
3) This function (when called at the beginning of simulation) does not find the "pEventFn" pointer, and hence continues to setup the CocoTb Python environment

Now, let's say I run the simulation for some time, and issue a restart. When I run the simulation after the restart, I see that steps 1 and 2 are still happening. Hiowever, the check for "pEventFn" now returns true and the "embed_sim_init" function returns. 

My first question is - Does that look like the correct behavior to you ? Or would you expect to not find the pEventFn after restart ? 

Also - can we setup some time to debug this and talk simultaneously ? My email is ritesh_goel@mentor.com
