### ISSUE TITLE
Questa runsim.do file is not regenerated if GUI parameter is changed

### ISSUE THREAD

**Issue by mvsoliveira** [cocotb/cocotb#2734]
For Questa, runsim.do file is generated based on the value of the GUI parameter. But if the file has been generated once, its contents is not updated unless one deletes the file. Side note: Even `make clean` DOES NOT erase the file. 

So, if I run:
`GUI=0 SIM=questa make`
the runsim.do file will have the command quit at the end. 
But if I run later:
`GUI=1 SIM=questa make`
The runsim.do will still include the quit command and will exit the simulator at the end of the simulation. However, one would like to keep the simulator open for reading the results and log.

In order to have the expected behavior without modifying the source code, the user needs to delete sim_build/runsim.do file every time the GUI parameter is changed on the command line. 

The suggested fix is to regenerate runsim.do file every time the make command is invoked.

**Comment by cmarqu** [comment]
> > For Questa, runsim.do file is generated based on the value of the GUI parameter. But if the file has been generated once, its contents is not updated unless one deletes the file.
> 
> This is how makefiles work. Not much one can do here I think.

This is something that we could nicely handle with the Python-based runner.

**Comment by mvsoliveira** [comment]
> > For Questa, runsim.do file is generated based on the value of the GUI parameter. But if the file has been generated once, its contents is not updated unless one deletes the file.
> 
> This is how makefiles work. Not much one can do here I think.
Well if the target can be forced to be regenerated by using the -B flag, i.e. make -B. I imagine there is a way of ensuring it in the makefile itself. 
If it is really not possible, maybe we could make sure the documentation warns about the need of using the -B flag when GUI, WAVES, or SCRIPT_FILE parameters are changed. 

> 
> > Even make clean DOES NOT erase the file.
> 
> But this has to work: https://github.com/cocotb/cocotb/blob/master/cocotb/share/makefiles/simulators/Makefile.questa#L166
Yes, you are right. This works indeed. I was doing the make clean without setting the simulator.

**Comment by mvsoliveira** [comment]
> > > For Questa, runsim.do file is generated based on the value of the GUI parameter. But if the file has been generated once, its contents is not updated unless one deletes the file.
> > 
> > 
> > This is how makefiles work. Not much one can do here I think.
> 
> This is something that we could nicely handle with the Python-based runner.

That makes sense for me. Never really understood why cocotb is not done purely in python.

**Comment by ktbarrett** [comment]
@mvsoliveira The C++ libraries used to be built on-demand with make when running a simulation, but that was moved to setuptools in 1.4. The makefiles for running the simulation remain vestigially. We were all hoping that a solution to the problem of running simulations would appear outside of the project so we don't have to duplicate and maintain what many other projects already do, and could ideally integrate with them, but alas, no such generic solution to EDA project automation exists. The current set of tools all seem to make assumptions that don't work with cocotb. It will be interesting to see where the [EDAA](https://github.com/edaa-org/pyEDAA.ProjectModel) project goes since it seems to be design to make as little assumptions as possible.

**Comment by jonpovey** [comment]
I added this line to the makefile to force runsim.do to get regenerated every time, to work around this same issue.
`.PHONY: $(SIM_BUILD)/runsim.do`
(Modelsim user here)

**Comment by mvsoliveira** [comment]
Hi @jonpovey,
In which part of the make file does this line have to be added? Maybe you could commit it to a branch and Cocotb experts could review it to see if it can be merged to master?

**Comment by mvsoliveira** [comment]
Yes. the issue has been resolved. Thanks to all involved in this.
