### ISSUE TITLE
VCS Error : +acc+1 

### ISSUE THREAD

**Issue by maswx** [cocotb/cocotb#2746]
NOTES

|NOTES|version|
|-|-|
 | the cocotb version used | 1.7.0|
 | the operating system and version (32/64 bit) | linux 64bit|
 | the simulator and version (32/64 bit)  | VCS2018.09 Full64 |
 | the Python version, | python 3.8.5 in anaconda Sep 4 2020 |
 
Error : 
The specified option '+acc+1' is deprecated.
 Please use '-debug_access+r+w+nomemcvk -debug+region+cell' instead

I fix this bug : 

rm `./cocotb/share/makefiles/simulators/Makefile.vcs`  `+acc+1`  then rebuild cocotb :
`./setup.py build`
`./setup.py install`

and next  add  `EXTRA_ARGS=-debug_access+r+w+nomemcvk -debug+region+cell` to Makefile
finally `make `
done

**Comment by lihq0716** [comment]
Hi, I have a question for you about switching to vcs emulator. After I changed the emulator to vcs, I reported the following error:
(1) Error-[PLI_TAB_SYNE] Syntax error in pli tab file
Syntax error on line '1' of pli table file 'pli.tab'.
Please fix this error and continue.
(2) make [1], [* * *. / home/LHQ/local/lib/python3.10 / site - packages/cocotb/share/makefiles/simulators/Makefile. VCS: 80: sim_build/simv] Error 1
make[1]: Leaving directory '/home/lhq/corundum/fpga/common/tb/rx_hash'
Make: * * * [/ home/LHQ/local/lib/python3.10 / site - packages/cocotb/share/makefiles/Makefile. Inc: 40: sim] Error 2

**Comment by imphil** [comment]
@lihq0716 Please open a https://github.com/cocotb/cocotb/discussions, your issue is different than the one you're replying to.

**Comment by ktbarrett** [comment]
Closed by #3951.
