### ISSUE TITLE
Adding time to my own logger

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2747]
I've created my own formatter in the `uvm_report_object` class in **pyuvm**.  However my logger does not print the simulation time.  

How does one create formatter that uses the current simulation time?

**Comment by eric-wieser** [comment]
You need to `import cocotb.log as _log` perhaps and use that instead. The module `cocotb.log` is not the same as the `log` attribute of cocotb!

**Comment by raysalemi** [comment]
@eric-wieser I must be missing a step. I do this:

```
import cocotb.log as cocotblog

<then below>

        self._streaming_handler.addFilter(cocotblog.SimTimeContextFilter())

```

But I get this error:

```
File "/Users/raysalemi/repos/pyuvm/pyuvm/s06_reporting_classes.py", line 31, in __init__
                         self._streaming_handler.addFilter(cocotblog.SimTimeContextFilter())
                     AttributeError: 'SimBaseLog' object has no attribute 'SimTimeContextFilter'
```

Which is strange because VS Code sees the SimTimeContextFilter and puts it in the context menu.

Is there some step I am missing?

Ray

**Comment by raysalemi** [comment]
```
import cocotb.log as cocotblog
from cocotb import log as logvar

with

        self._streaming_handler.addFilter(logvar.SimTimeContextFilter())

```

Gives the same error.
