### ISSUE TITLE
xcelium waves dump question

### ISSUE THREAD

**Issue by aignacio** [cocotb/cocotb#2754]
Hey everyone,

how is it possible to  dump waves through xcelium run? I tried to add the following tcl script in the EXTRA_ARGS="-input dump.tcl" but it breaks the test run...

```tcl
#dump.tcl
database -shm -default waves -event
probe -create -shm -depth all -variables -ports -all -generics -functions -tasks -dynamic -unpacked 0
```

**Comment by PiyushSaini09** [comment]
Were you able to define a tcl script in cocotb?
