### ISSUE TITLE
test_case test_array_buses fails with verilator (make SIM=verilator)

### ISSUE THREAD

**Issue by xptrx** [cocotb/cocotb#2755]
run:

make SIM=verilator

returns:

     0.00ns INFO     *******************************************************************************************
                     ** TEST                               STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
                     *******************************************************************************************
                     ** test_array_buses.test_array_buses   FAIL           0.00           0.00          1.14  **
                     *******************************************************************************************
                     ** TESTS=1 PASS=0 FAIL=1 SKIP=0                       0.00           0.01          0.11  **
                     *******************************************************************************************

**Comment by Thomasb81** [comment]
This issue can be closed : https://github.com/verilator/verilator/pull/4618 is fixing the issue
