### ISSUE TITLE
Parsing cocotb output

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2767]
Is there a recommended way to save **cocotb** output and parse it to see if any tests say `FAIL`?

**Comment by ktbarrett** [comment]
`results.xml` outputs test results in jUnit format which includes failing tests. Do not parse the output, that may change at any time. See [bin/combine_results.py](https://github.com/cocotb/cocotb/blob/master/bin/combine_results.py) for an example of how to get failing tests from the results.xml file.

**Comment by raysalemi** [comment]
Thank you, sir.

**Comment by raysalemi** [comment]
I don't see the pass fail result in in this file:

```
<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1636295397" />
    <testcase name="random_test" classname="testbench" file=".../testbench.py" lineno="134" time="0.003201007843017578" sim_time_ns="151000" ratio_time="47172642.9316252" />
    <testcase name="max_test" classname="testbench" file="...testbench.py" lineno="141" time="0.0017879009246826172" sim_time_ns="150000" ratio_time="83897266.30217363">
      <failure />
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by Botnic** [comment]
You seem to have two test:
* random_test: Success
* max_test: Fail

**Comment by raysalemi** [comment]
Yes, I found the <failure /> tag.
