### ISSUE TITLE
combine_results.py imagined use model

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2771]
The `combine_results.py` file from `cocotb/bin` doesn't seem to get put on the `PATH` or `PYTHONPATH`.  What is the expected use model?  Should I copy the script, or did I mess up my installation somehow?

**Comment by ktbarrett** [comment]
It is used in our [internal regression](https://github.com/cocotb/cocotb/blob/7cc4e12b22213b031fa6e16565c1b5b60d19fd22/Makefile#L51). It is not packaged with the installation and we do not have an imagined use case for the end user.

**Comment by raysalemi** [comment]
Okay, thanks.  Then I'll just copy it as a starting point for my regressions.
