### ISSUE TITLE
pip3 install cocotb failed when predownload package from pypi

### ISSUE THREAD

**Issue by captainliuy** [cocotb/cocotb#2784]
below is the requirments:
cocotb==1.6.0
cocotb-bus
cocotb-test==0.2.1
cocotbext-axi==0.1.16
cocotbext-eth==0.1.18
when I use command "pip3 download -r requirements.txt -d ./packages/" to download the packages, dependencies will be downloaded also. 
Copy to the offline host, failed to install, below is the log:
`pip3 install --user --no-index --find-links="./packages" -r requirements.txt`
`ERROR: Could not find a version that satisfies the requirement cocotb`

**Comment by captainliuy** [comment]
pip3 version problem

**Comment by neutrala** [comment]
Hello,
I get the same problem,how do you solved it?
