### ISSUE TITLE
Extending and shortening regressions

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2808]
PR regression tests take a long time. But at the same time it would be nice to extend the number of tests we are doing (#2765). To accomplish this we should split the regression into a short regression and a long regression. The short regression would run on PRs, the long regression would run daily, or if a maintainer thinks a particular PR may trigger an issue.

I have put together a matrix and selected rows that I think best test the important cross-sections.

python version | environment | simulator | compiler | tier
-- | -- | -- | -- | --
3.6 | ubuntu | icarus | default | 1
3.7 | ubuntu | icarus | default | 2
3.8 | ubuntu | icarus | default | 2
3.9 | ubuntu | icarus | default | 2
3.10 | ubuntu | icarus | default | 1
default | ubuntu | icarus | clang | 1
default | ubuntu | ghdl | default | 1
default | ubuntu | verilator | default | 1
default | windows + anaconda | icarus | default | 1
default | windows + anaconda | ghdl | default | 2
default | windows + anaconda | verilator | default | 2
default | windows + anaconda | icarus | msvc | 1
default | msys2 | icarus | default | 1
default | msys2 | ghdl | default | 2
default | msys2 | verilator | default | 2
default | mingw32 | icarus | default | 2
default | mingw32 | ghdl | default | 2
default | mingw32 | verilator | default | 2
default | mingw64 | icarus | default | 2
default | mingw64 | ghdl | default | 2
default | mingw64 | verilator | default | 2
default | ucrt64 | icarus | default | 2
default | ucrt64 | ghdl | default | 2
default | ucrt64 | verilator | default | 2
default | macos + homebrew | icarus | default | 1
default | macos + homebrew | ghdl | default | 2
default | macos + homebrew | verilator | default | 2

Default compiler is GCC on Linux and Windows, and Clang on MacOS (aliases from `gcc`).
Default Python version is most recent release of Python supported by all platforms (I think that's 3.10 now, but could be 3.9 if something fails).

Generally I was going for the short (PR) regression:
* oldest and newest Python
* at least one test in each environment + compiler
* at least one test per simulator

Also I will probably compress the checks: whitespace, flake8, and clang-format into a single test using [this technique](https://stackoverflow.com/a/58859404/6614127).

It would be nice to use the same step definitions, but different matrices for the short and long regression. Not sure if that is possible...

**Comment by imphil** [comment]
With all tests running in parallel, test latency is mostly dominated by the test suite itself, not so much by how many versions of it we run.

By now, we already split out fragile or less-important tests into a separate bucket that runs weekly. I think we've found a reasonable balance at this point, with only minor adjustments needed going forward.
