### ISSUE TITLE
Windows install issue

### ISSUE THREAD

**Issue by robertcjuk** [cocotb/cocotb#2827]

**Comment by marlonjames** [comment]
Could you please provide more information?
cocotb version, etc?
Are you using conda, cygwin, or Windows Python?

There are installation instructions here: https://docs.cocotb.org/en/stable/install.html
If you plan to use something other than the cocotb Makefiles, see https://docs.cocotb.org/en/stable/custom_flows.html for details on integrating cocotb into your existing scripts.

**Comment by robertcjuk** [comment]
Thank you for your reply. I have now managed to get things up and running :-)
