### ISSUE TITLE
How to keep questa session running when simulation is done

### ISSUE THREAD

**Issue by filamoon** [cocotb/cocotb#2829]
WSL2 ubuntu
cocotb 1.6.1
questa linux 2021.2_1 64b

I'm using cocotb/cocotb-test and questa cosimulation. Each time the simulation is done, questa(vsim) quits.
Is there any way to keep the questa session running after the simulation is done, so I can inspect the waves?
I have tried adding "-onfinish ask" to the vsim CLI but it did not help.
It takes an incredibly long time to launch a vsim session.

Thanks.

**Comment by ktbarrett** [comment]
This seems like a question for cocotb-test. Pinging @themperek.

**Comment by themperek** [comment]
You can use "WAVES=1" (https://github.com/themperek/cocotb-test#environmental-variables) as an environmental variable or use `waves` parameter got `run` function (https://github.com/themperek/cocotb-test#arguments-for-simulatorrun).

Please use https://github.com/themperek/cocotb-test/issues for `cocotb/cocotb-test` related questions.

**Comment by themperek** [comment]
Correction: to not quit use `gui` parameter (https://github.com/themperek/cocotb-test#arguments-for-simulatorrun).

**Comment by jonpovey** [comment]
Commented on the cocotb-test issue (the feature is working for me)
Suggest closing this cocotb ticket.
