### ISSUE TITLE
Logging Errors are not considering on Final Test Result

### ISSUE THREAD

**Issue by HarshaReddy7569** [cocotb/cocotb#2861]
In the test, I have multiple Checkers at Multiple Levels. If I use assert, the simulation will stop there itself and show the test result as `FAIL`

But, I want to check all the instances and log them with `dut._log.error`. But these Errors are not considered on Final Test Status.

Is there any way to consider these errors also into the final Status and show the result as `FAIL`?

![image](https://user-images.githubusercontent.com/60434873/154092923-e8130ef4-6e92-451b-b1a1-940ebf9af331.png)

**Comment by ktbarrett** [comment]
Logs are not used to fail tests. You can implement this yourself by overloading the `SimHandle` to count the number of times error logs or more severe are logged, then assert on the count being 0 at the end of your test.
