### ISSUE TITLE
Rename arguments in python runner

### ISSUE THREAD

**Issue by themperek** [cocotb/cocotb#2898]
Some suggestions:

`toplevel` ->  `hdl_module` / `hdl_topmodule` / `hdl_toplevel`

`toplevel_lang` -> `toplevel_intrface` / `toplevel_if`

~`python_search` -> do we need this or just suggest using `sys.path.append`?~

different? other?

Related: https://github.com/cocotb/cocotb/issues/2848

**Comment by imphil** [comment]
Naming decisions:
* [hdl_]toplevel
* [hdl_]toplevel_lang
* gpi_interface
