### ISSUE TITLE
Modifying SIM_ARGS in the Makefile does not update runsim.do

### ISSUE THREAD

**Issue by JC-FPGA** [cocotb/cocotb#2899]
I'm using cocotb v1.6.2 on Ubuntu 20.04.1

When updating SIM_ARGS in the Makefile, the automatically generated sim_build/runsim.do does not get updated.  For example, changing
SIM_ARGS +=-gIMAGE_WIDTH=1280
to
SIM_ARGS +=-gIMAGE_WIDTH=1920

the vsim command stays at the old value:
`vsim -gIMAGE_WIDTH=1280 -onfinish exit -foreign "cocotb_init  ....`

After changing SIM_ARGS, a workaround is running "make clean" or simply deleting the runsim.do file.  Since sim_build/runsim.do is an "autogenerated" file, I would expect it to be updated upon a change to Makefile.

**Comment by themperek** [comment]
> I would expect it to be updated upon a change to Makefile.
This is nothing cocotb can do. It is how makefiles work. 

You can add your makefile to `CUSTOM_SIM_DEPS`.

**Comment by themperek** [comment]
Acuity one could add this inside `cocotb`.

**Comment by ktbarrett** [comment]
When projects become split across multiple makefiles that becomes impossible to decide. Tools like CMake handle this by creating a cache file of the variables and seeing if there is a diff between the current variables and the old variables.
