### ISSUE TITLE
"Passing and Failing Tests" suggest to use "TestFailure" (deprecated)

### ISSUE THREAD

**Issue by rodrigomelo9** [cocotb/cocotb#2900]
Hi. I was re-reading the docs and I found this inconsistency at https://docs.cocotb.org/en/stable/writing_testbenches.html#passing-and-failing-tests. If removing TestFailure from the text and the example is enough, I can do that (or let me know if I can help to fix it in another way).

Regards,
Rodrigo

**Comment by ktbarrett** [comment]
> If removing TestFailure from the text and the example is enough, I can do that

Yeah I think that is all that needs to be done. We would appreciate the help!

**Comment by rodrigomelo9** [comment]
Ok, I'm going to fix it and open a PR :-D
