### ISSUE TITLE
README dark / light images result in duplicate and/or broken logos on PyPI

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#2915]
We should see if we can get absolute URLs to work, but will also need to strip the dark mode images before publication; either via the github action mentioned at https://www.npmjs.com/package/strip-gh-theme-links, or doing something in setup.py.

Alternatively, we could just accept an unreadable logo on github dark mode and just remove the light mode image.

Milestoning as 1.7 so we don't forget before a release.

**Comment by ktbarrett** [comment]
There is now a new recommended way to change images based on theme. The old way using `#light-mode-only` and `#dark-mode-only` are deprecated. [Github Docs.](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)
