### ISSUE TITLE
Include logger name in log output

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2953]
The culprit is logged, but the new "short" log format doesn't include the logger name so I don't get any useful information from this. IMO the default log format should include the logger name.
https://github.com/cocotb/cocotb/blob/c69454db92388a8915c99a35ca9cba06565fe4d5/cocotb/scheduler.py#L451

**Comment by jonpovey** [comment]
Agreement from the peanut gallery over here. I have to work around this.
