### ISSUE TITLE
cocotb installation on questasim

### ISSUE THREAD

**Issue by manjins** [cocotb/cocotb#2977]
Windows 64bit
Python version used: 3.10

cocotb\share\lib\fli\FliCbHdl.cpp(155): error C2664: 'int mti_Cmd(char *)': cannot convert argument 1 from 'const char [22]' to 'char *'
  cocotb\share\lib\fli\FliCbHdl.cpp(155): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)
  C:\questasim_10.0b\include\mti.h(624): note: see declaration of 'mti_Cmd'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

Help me fix this so that I can start working.

**Comment by marlonjames** [comment]
Your environment appears to be using `/Zc:strictStrings`.

**Comment by manjins** [comment]
I was able to resolve the error, thank you. Though I have one more query: I am trying to set up cocotb on windows setup with questa and pycharm installed. I am not sure how if that is possible ? Can you please help on how to run the makefile in case I want to test the inbuild example

**Comment by marlonjames** [comment]
Windows installation documentation is here: https://docs.cocotb.org/en/stable/install.html
We recommend conda environment at this point if you want to use makefiles.

If you already have a simulation flow for Questa, we have some documentation about extending your Tcl scripts to start cocotb tests: https://docs.cocotb.org/en/stable/custom_flows.html#extending-existing-build-flows
