### ISSUE TITLE
Running cocotb-test

### ISSUE THREAD

**Issue by TomO700** [cocotb/cocotb#2996]
I am trying to modify the default python and run with the following command using verilator, and end up with the error below

**Command**

`SIM=verilator pytest -o log_cli=True test_mod.py`

**Error**

```
E       SystemExit: Process 'perl' terminated with error 2

/../../.local/lib/python3.9/site-packages/cocotb/runner.py:134: SystemExit
```

Any help would be highly appreciated

**Comment by marlonjames** [comment]
Looks like currently, `stdout` and `stderr` are not captured in the runner:
https://github.com/cocotb/cocotb/blob/cda36036cec45fe9564bb1839c591514cfcfdf1a/cocotb/runner.py#L245-L266

You could try modifying the cocotb runner to get more information on the error.

**Comment by themperek** [comment]
Try `SIM=verilator pytest -s -o log_cli=True test_mod.py`.
Try to run `perl /usr/local/bin/verilator` 

This issue should to https://github.com/themperek/cocotb-test/issues. 
I will close it here.

**Comment by TomO700** [comment]
This did not work either, its still the same error.
Let me create an issue in the link you have pointed...
