### ISSUE TITLE
CRITICAL Failed to import module test_endian_swapper: No module named 'cocotb.drivers'

### ISSUE THREAD

**Issue by TomO700** [cocotb/cocotb#3009]
Hi,

I tried with a few versions on my mac and get the above error.

This `No module named 'cocotb.drivers` error comes in all versions I tried (1.7 dev version and a couple of much older versions)

What would be the possible fix?

Thanks!

**Comment by ktbarrett** [comment]
`cocotb.drivers` was moved to the `cocotb-bus` package in v1.6. I'm not sure where you are finding `test_endian_swapper` but if it's the endian swapper example that used to be in this repo, it was moved to `cocotb-bus` as well. You *must* run examples from the repo with the same version of cocotb you have installed. For example, if you have installed cocotb v1.6.2, you can only run tests and examples from the cocotb repo if you check out the tag v1.6.2.
