### ISSUE TITLE
Issues with `cocotb.start`

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3025]
`cocotb.start` is intended to run the given coroutine and block until it has started. Right now it's literally just `cocotb.start_soon` followed by `await NullTrigger()`. The behavior of `cocotb.start` is not currently useful because of the `NullTrigger`; there is no guarantee, like with `cocotb.fork`, that the given coroutine is the next thing that is scheduled. Additionally, I have experienced that users 1. don't look at the warning emitted by `fork`, 2. don't read the documentation, 3. don't look at examples, 4. come and ask me what the difference between the two is. It might be better to not give users the option since they do not understand how this stuff work. Since `cocotb.start` is not doing anything the user couldn't easily do themselves, I think we could deprecate it.

**Comment by marlonjames** [comment]
The idea was not to create an exact `async` copy of `cocotb.fork`.
It is akin to `await asyncio.sleep(0)`, allowing all other pending triggers and unstarted Tasks to run, before continuing.
There is a guarantee that before coroutine execution resumes after `await cocotb.start(coro)`, the new coroutine will have run in another Task. Other Tasks may also have run.
