### ISSUE TITLE
cocotb.simulator link does not exist

### ISSUE THREAD

**Issue by H0sseinR0stami** [cocotb/cocotb#3034]
the following link is broken:
https://docs.cocotb.org/en/v1.6.2/_modules/cocotb/simulator.html

**Comment by cmarqu** [comment]
The link is autogenerated, apparently from the imports it sees in the Python code, but that module is implemented in C++: https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/simulator/simulatormodule.cpp

**Comment by ktbarrett** [comment]
As stated, the documentation is not broken, this is a Sphinx issue.

**Comment by H0sseinR0stami** [comment]
Hi. I have found it in an other repository in the link below:
https://github.com/mciepluc/cocotb-test/blob/master/cocotb_test/simulator.py

**Comment by marlonjames** [comment]
@H0sseinR0stami That is not the correct module.
The `cocotb.simulator` module is a Python extension module written in C++, and the source code was linked by @cmarqu above.
