### ISSUE TITLE
Upstreaming Cocotb into Conda-forge

### ISSUE THREAD

**Issue by tianrui-wei** [cocotb/cocotb#3122]
Hi Folks,

I'm opening this issue to let you know I opened a PR at [conda-forge](https://github.com/conda-forge/staged-recipes/pull/21056) to upstream cocotb into conda-forge. Given we already have a PyPI package from [this issue](https://github.com/cocotb/cocotb/issues/440), it seems only fair conda has a package as well :) I'm happy to maintain the conda package, and I'm also happy if someone else wants to take over.

Best regards,
Tianrui

**Comment by imphil** [comment]
Thanks! I replied over at https://github.com/conda-forge/staged-recipes/pull/21056#issuecomment-1309329721.

**Comment by tianrui-wei** [comment]
Sounds good, thank's Philipp!
