### ISSUE TITLE
Error when calling a C function that calls an SV function using DPI

### ISSUE THREAD

**Issue by AntonBabundin** [cocotb/cocotb#3154]
I would like to know if it is possible to use `ctypes` in the cocotb test to call a function in C that, by DPI, calls a task inside itself inside SV ?
I tried to do it directly, but I get this error:
![image](https://user-images.githubusercontent.com/59487235/205301888-61dd2242-018d-4225-9ad4-ce826280bef6.png)
tb code:
```SystemVerilog
module automatic tb;
 
  export "DPI-C" function helloFromSV;
  import "DPI-C" context function void helloFromCppp();
 
  function void helloFromSV();
    $display("Hello form SV");
  endfunction

endmodule
```

C code:
```c
#include <iostream>
#include <svdpi.h>
//#include <dpi_header.h>

using namespace std;

extern "C" void helloFromSV();

extern "C" int helloFromCppp(svLogic a) {
  // 0 is 0
  // 1 is 1
  // 2 is Z
  // 3 is X
  int a_int = a;
  cout << "(C++) a is " << a_int << endl;
  helloFromSV();
  return 0;
}
```
Python code:
```python
import cocotb
from ctypes import CDLL 
### Test seqeunces ###
so_files = "./xcelium.d/run.lnx8664.20.09.d/librun.so"

@cocotb.test()
async def apb_regs_seq(dut):
    dut._log.critical("################### FIRST TIME #################")
    my_funct = CDLL(so_files)
    my_funct.helloFromCppp(0)
```
cocotb version: cocotb 1.7.0
OS: Ubuntu 22.04.
Python ver.: 3.10

**Comment by marlonjames** [comment]
Use of DPI scope-related APIs is outside the scope of ieee1800-2017, as noted in section 35.5.3.
The interaction between VPI callbacks and the DPI related functions is completely simulator dependent.
See #1989 for more context.

**Comment by marlonjames** [comment]
You may be able to save the correct context by calling `svGetScope()` from an imported function, then using `svSetScope()` with that saved context inside a VPI callback. I would check with simulator support to see if they support DPI contexts from VPI callbacks.

**Comment by ktbarrett** [comment]
To add. VPI callbacks run *between* SV task execution at confluence points in the SV timing model. There will never, by definition, be a DPI task running when a VPI callback is executed. The only real way to get the two to communicate is via asynchronous queues. And even at that point you will still need a VPI callback registered to re-enter cocotb.

I think `svSetScope` would not work as it is basically just a blocking mutex acquire which would deadlock the cocotb scheduler.
