### ISSUE TITLE
Coredump on assertion failure.

### ISSUE THREAD

**Issue by jahagirdar** [cocotb/cocotb#3157]
I have seen this issue on both local machine and on Github Actions.
https://github.com/dyumnin/cocotb_coredump/actions/runs/3646391815/jobs/6157420573#step:5:28

The assertion on Line 15 of https://github.com/dyumnin/cocotb_coredump/blob/delayed/tests/dut_test.py#L15 triggers a coredump.

On my local machine the version info is as follows

Python 3.10.6
OS:    Linux Mint 21
Modules in venv
pip3 freeze                                                                                                                     ─╯
attrs==22.1.0
cocotb==1.7.0
cocotb-bus==0.2.1
cocotb-coverage==1.1.0
exceptiongroup==1.0.4
iniconfig==1.1.1
packaging==22.0
pluggy==1.0.0
pytest==7.2.0
python-constraint==1.4.0
PyYAML==6.0
tomli==2.0.1

**Comment by ktbarrett** [comment]
The repo link appears to be private.

**Comment by jahagirdar** [comment]
Changed the visibility to public.

**Comment by ktbarrett** [comment]
You can use the makefile variable [`SIM_CMD_PREFIX`](https://docs.cocotb.org/en/stable/building.html#var-SIM_CMD_PREFIX) to run your simulation with gdb to catch where it is segfaulting.

**Comment by cmarqu** [comment]
Another way of attaching gdb is described in https://docs.cocotb.org/en/stable/troubleshooting.html?highlight=gdb#attaching-a-debugger

**Comment by jahagirdar** [comment]
Looks like an issue with iverilog, The test works on the devel version.
