### ISSUE TITLE
version 1.7.2. install succeeds but reports version as 0.2.3

### ISSUE THREAD

**Issue by gilbertwaltoon** [cocotb/cocotb#3162]
Hi,  

I'm installing the latest cocotb with pip with `pip install cocotb`

Things seem (mostly) o.k. I get  `Successfully installed cocotb-1.7.2`
and afterwards I can run simulations etc.

However typing `$ cocotb --version` reports only `0.2.3` (?)

I do get a "Failed building wheel" message during the install (tho' the install still succeeds). Following the troubleshooting guide however, I've also tried pip-uninstalling and reinstalling with `pip install --no-cache-dir cocotb`
This removes the 'wheel error' but I still get version as 0.2.3
  
I'm on Ubuntu 18.04 with python 3.8.0 and pip 9.0.1  in a virtual env. I've not installed any other cocotb versions on my machine.

 
![image](https://user-images.githubusercontent.com/22557448/208864374-2c855925-d919-450f-bbac-1d9cf191fd07.png)

**Comment by imphil** [comment]
The "cocotb" binary is part of cocotb-test. You need to type "cocotb-config --version" to get the version of cocotb itself.
