### ISSUE TITLE
How to pullup/pulldown signal in cocoTB

### ISSUE THREAD

**Issue by suchi2108** [cocotb/cocotb#3188]
### Discussed in https://github.com/cocotb/cocotb/discussions/3187

<div type='discussions-op-text'>

<sup>Originally posted by **suchi2108** January 16, 2023</sup>
I am aware of 'cocotb.handle' library, and how force, deposit, freeze and release works.

I want to pull up the signal to '1'. I believe if it is pulled up, and I release it after some time, it will go to '1', instead of 'Z'. We just write 'pullup(SDA)', where 'SDA' is wire type and it works fine in HDL. 

What could be substitute in CocoTB?

Any lead will be really helpful.

 </div>

**Comment by ktbarrett** [comment]
> What could be substitute in CocoTB?

This is out of cocotb's control. It would require the creation of a driver, which is not possible in either the VPI or VHPI which cocotb use to interact with simulators.

Please, do not open issues because your discussions have no gotten any responses.
