### ISSUE TITLE
Increase number of builds before coverage colection

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3224]
From [here](https://github.com/cocotb/cocotb/blob/8fef13a10b43edccae1ac6649f9a0582f88d6e22/.codecov.yml#L20). I think we have more now as I just saw it make a coverage comment before all of the private CI tests were finished.

**Comment by marlonjames** [comment]
Last fully successful commit had 15 results uploaded:
https://app.codecov.io/gh/cocotb/cocotb/commit/8fef13a10b43edccae1ac6649f9a0582f88d6e22
