### ISSUE TITLE
TWOS_COMPLIMENT binary representation is not giving correct answer

### ISSUE THREAD

**Issue by RehanQasim-dev** [cocotb/cocotb#3249]
I have just started learning cocotb and I am trying to get BinaryValue representation of int 6 in 2's compliment but i am not getting correct answer it should be 1010 but i am getting 0110,

async def simple_test(dut):
    """simple test of 1+2"""
    A=BinaryValue(6,binaryRepresentation=BinaryRepresentation.TWOS_COMPLEMENT)
    print("TWO's compliment of 6 is=",A)

![image](https://user-images.githubusercontent.com/110167105/219393648-6ecb2f75-b94f-4f14-bb10-a1dacc385bb1.png)

**Comment by eric-wieser** [comment]
Why would you expect `1010`? That looks like `-6` or `10` to me.

**Comment by RehanQasim-dev** [comment]
> Why would you expect `1010`? That looks like `-6` or `10` to me.
00110 is the binary representation of 6. To find its two's complement I take its negation and add 1 which comes out to be 11010

**Comment by eric-wieser** [comment]
"Twos complement" here descrives the representation, not an operation. If you want to get it's negation, use `-`.
