### ISSUE TITLE
Release 1.8

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3262]
Milestone: https://github.com/cocotb/cocotb/milestone/23

Release process checklist:
- [x] Close all issues blocking the milestone
- [x] prepare RC release
- [x] do an extended regression run: https://dev.azure.com/fossi-foundation/cocotb-private/_build/results?buildId=3922&view=results, https://github.com/cocotb/cocotb/actions/runs/5248617434
- [x] prepare release announcement blog post
- [x] tag release
- [x] test release build on PyPi
- [x] send out announcement to blog, Twitter, Linkedin, etc.

**Comment by imphil** [comment]
cocotb 1.8.0 is now released, the release announcement is available at https://www.cocotb.org/2023/06/15/v1.8.0.html
