### ISSUE TITLE
RecursionError in _resume_coro_upon when error happen

### ISSUE THREAD

**Issue by suzizecat** [cocotb/cocotb#3267]
Using :
 - Cocotb 1.7.2
 - Ubuntu 22.04 (In WSL 2.0 for Windows 10) 
 - Verilator 5.004

When an exception occurs in the scheduler `_react` function on:
```python
        if self._pending_triggers:
            raise InternalError(
                "Expected all triggers to be handled but found {}".format(
                    self._pending_triggers
                )
            )
```
With remaining triggers, during the call to the `trigger.prime` function of the `_resume_coro_upon()` :
```python
if not trigger.primed:
    # ... 
    try:
        trigger.prime(self._react)
    except Exception as e:
        # discard the trigger we associated, it will never fire
        self._trigger2coros.pop(trigger)
        # replace it with a new trigger that throws back the exception
        self._resume_coro_upon(
            coro,
            NullTrigger(
                name="Trigger.prime() Error", outcome=outcomes.Error(e)
            ),
        )
```

The call of `self._resume_coro_upon` with the `NullTrigger` will end up throwing the same `InternalError`, hence recursively throwing until Python itself explodes.

I managed to avoid the recursion error by changing the code around `InternalError`. Adding a `self._cleanup()` force the scheduler to cleanup the remaining triggers and fail in another way, after properly reporting the `InternalError`. 

The resulting code for `_react` is:
```python
def _react(self, trigger):
    """
    Called when a trigger fires.
    We ensure that we only start the event loop once, rather than
    letting it recurse.
    """
    # ... 
    if self._pending_triggers:
        self._cleanup() # <--- Force the cleanup of remaining _pending_triggers
        raise InternalError(
            "Expected all triggers to be handled but found {}".format(
                self._pending_triggers
            )
        )
```

**Comment by ktbarrett** [comment]
I think instead `InternalError` should either specifically handled in the wrapper around `trigger.prime` or it should become a `BaseException`.

**Comment by ktbarrett** [comment]
@suzizecat Can you provide a test for this?

**Comment by ktbarrett** [comment]
I used the test from #3270 to reproduce the issue. Changing to BaseException worked, I'll put up a PR once I figure out the rest of #3270.

**Comment by suzizecat** [comment]
The test from my other issue is indeed the most reliable (and simple-ish) way I found to trigger this.
