### ISSUE TITLE
Nested context managers not unscheduled correctly at the end of tests.

### ISSUE THREAD

**Issue by suzizecat** [cocotb/cocotb#3270]
Using cocotb 1.7.2 from pip on Ubuntu 22.04 and Python 3.10.

This bug as been seen with verilator 5 and a hacked 4.212 versions. However I suspect that this is a Python-side issue. 

When ending a test while a coroutine is started from within a nested context manager, `First()` events seems not to be unscheduled properly.
This leads to a non-empty event list upon starting the next test and blows everything up (due to #3267 )

Please note that starting the `buggy` test alone will work fine and that the actual test result isn't relevant.

It is a bit tricky to makes this appear, but the following codes demonstrates the issue.
Run with `make SHOW_BUG=1`  to display the unexpected behavior.  

For understanding purpose, the goal of `MonitorChange`  is to provide a context manager which will throw if changes are unexpected on a combination of signals. This is a reduced testcase from a much bigger bench and appears quite useless in the present bug report.

The following dummy IP is a counter triggering a pulse and managing an additional `valid`  signal for the purpose of showing the issue.
```systemverilog
module trigger_counter (
    input logic i_clk,  //!
    input logic i_rst_n,  //!
    input logic i_trg,  //!
    input logic i_valid,
    input logic [7:0] i_cnt,  //!
    output logic o_pulse,  //!
    output logic o_valid
);


  logic [7:0] cnt;

  always_ff @(posedge i_clk or negedge i_rst_n) begin : p_seq_
    if (~i_rst_n) begin
      cnt <= 0;
      o_pulse <= 0;
      o_valid <= 0;
    end else begin
      o_pulse <= 0;
      o_valid <= i_valid;
      if (i_trg) begin
        cnt <= i_cnt;
      end else if (cnt != 0) begin
        cnt <= cnt - 1;
        o_pulse <= (cnt == 1) ? 1'b1 : 1'b0;
      end
    end
  end

endmodule
```
The following python demonstrate the relevant bug.
```python
from cocotb.clock import Clock
from cocotb.triggers import *
import cocotb

import os

class MonitorChange:
    def __init__(self, signal, valid,expect_change = True) -> None:
        self.monitor_process = None
        self.signal = signal
        self.valid = valid
        self.expect_change = expect_change

    def __enter__(self) :
        self.start_monitor()
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is None :
            self.assert_change()
            return True
        else :
            self.stop_monitor()
            return False
    
    async def _monitor_req_design_update(self) :
        update = False
        while not update :
            cocotb.log.info(f"Started monitor. Expect is {self.expect_change}")
            
            if "SHOW_BUG" in os.environ and int(os.environ["SHOW_BUG"]):
                await First(RisingEdge(self.signal), RisingEdge(self.valid))
            else :
                await RisingEdge(self.valid)

            update = self.signal.value and self.valid.value
            cocotb.log.info(f"Some signal moved. Update is {update} (valid is {self.valid.value} and signal is {self.signal.value})")
        cocotb.log.info("Change occured")
        assert self.expect_change, f"Unexpected change happened"
    
    def stop_monitor(self):
        if self.monitor_process is not None :
            self.monitor_process.kill()
        self.monitor_process = None

    def start_monitor(self):
        self.stop_monitor()
        self.monitor_process = cocotb.start_soon(self._monitor_req_design_update())

    def assert_change(self) :
        is_ok = True
        if not (self.monitor_process is None or self.monitor_process.done()) :
            cocotb.log.info(f"Asserting change. No change occured")
            is_ok = not self.expect_change
        self.stop_monitor()    
        assert is_ok, f"Change SHOULD have happened"

async def init_dut(dut) :
    dut.i_rst_n.value = 1
    dut.i_clk.value = 0
    dut.i_trg.value = 0
    dut.i_valid.value = 0
    dut.i_cnt.value = 0
    await Timer(1)
    dut.i_rst_n.value = 0
    await Timer(10,"ns")
    dut.i_rst_n.value = 1
    return cocotb.start_soon(Clock(dut.i_clk,1,"ns").start())


@cocotb.test()
async def buggy(dut):
    clk = await init_dut(dut)

    async def stuff(dut) :
        with MonitorChange(dut.o_pulse, dut.o_valid, expect_change=False) :
            with MonitorChange(dut.i_trg, dut.o_valid, expect_change=False) : 
                await Timer(10,"us")

    coro = cocotb.start_soon(stuff(dut))
    
    await Timer(5,"ns")
    await RisingEdge(dut.i_clk)
    dut.i_cnt.value = 5
    dut.i_trg.value = 1
    dut.i_valid.value = 0
    await RisingEdge(dut.i_clk)
    dut.i_trg.value = 0

    await RisingEdge(dut.o_pulse)
    clk.kill()
    coro.kill() # <--- This have no influence.
    await Timer(1,"us")

@cocotb.test()
async def basic_ok(dut):
    clk = await init_dut(dut)

    with MonitorChange(dut.o_pulse, dut.o_valid, expect_change=True) :
        await Timer(5,"ns")
        await RisingEdge(dut.i_clk)
        dut.i_cnt.value = 5
        dut.i_trg.value = 1
        dut.i_valid.value = 1
        await RisingEdge(dut.i_clk)
        dut.i_trg.value = 0

        await RisingEdge(dut.o_pulse)
        await Timer(10,"ns")

    await Timer(10,"ns")
    clk.kill()
```

**Comment by ktbarrett** [comment]
I'm at a loss. Debugging is show the `_pending_triggers` being modified in the middle of the `_cleanup` call at a distance, as if there is some spooky thread stuff going on.

**Comment by suzizecat** [comment]
One thing that might be of importance is (maybe) a weird management due to the context manager.
You might think of it as an exception handler (A `try: ... except: ... ` block) 

Therefore, when killing all the tasks, if the outer task is killed before the inner task, that might be triggering some weird stuff.
I need to test out the fact that a GeneratorExit "error" must be propagated (and not captured) in the exit part of the context manager. 
Otherwise, I'll look into it when I have tome but at the moment I have limited access to internet. 
I would dig into weird concurrency issues though.

**Comment by ktbarrett** [comment]
So the issue seems to be that during cleanup as we are unpriming triggers (for instance `RisingEdge(self.signal)`) the unpriming causes downstream `First`s triggers to fire (calls `_react` and adds them to the `_pending_triggers`).

The cleanup actually done in `_cleanup` is also pretty half-assed and leverages a bunch of assumptions. The cleanup behavior is scattered thoughtlessly through the codebase.

A quick test replacing `First` with the below radically improves the scheduler behavior.

```python
async def First(*awaitables: Awaitable[Any]) -> List[Task[Any]]:
    event = Event()

    async def waiter(awaitable: Awaitable[Any]) -> Any:
        return_data = await awaitable
        event.set()
        return return_data

    tasks = []
    for aw in awaitables:
        task = cocotb.start_soon(waiter(aw))
        tasks.append(task)

    await event.wait()
    for task in tasks:
        if not task.done():
            task.kill()
    return tasks
```

But I guess we need to figure what the best way of doing scheduler cleanup is considering this limitation. Moving around the cleanup of the triggers to follow the cleanup of all the coroutines helps prevent the issue, but the currently "handled" trigger when the test end may still cause a `First` to be added when the trigger is finally unprimed, perhaps a special case will work. Or perhaps this needs a ton more thought...

**Comment by ktbarrett** [comment]
Just an FYI, `First` and `Combine` have caused so much heartache for us that we internally ban their use in favor of functions like the above.
