### ISSUE TITLE
Fail make cocotb 1.2.0

### ISSUE THREAD

**Issue by gtleon** [cocotb/cocotb#3283]
My system is Windows 7 x86 Professional, according to the documentation for version 1.2.0, I installed MinGW/Msys,
installed https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi.
Simulator Questasim 10.7 (x86).
After executing the make command, a message is displayed, as shown in the screenshot:

![Снимок](https://user-images.githubusercontent.com/47860047/233305257-4842bc2d-d44a-4f06-818a-f74da41b27cb.PNG)

**Comment by ktbarrett** [comment]
We do not support old versions of cocotb. Sorry.
