### ISSUE TITLE
Fail cocotb run in Windows 10

### ISSUE THREAD

**Issue by gtleon** [cocotb/cocotb#3285]
My system is Windows 10 Home, Version 21H1,
installed Miniconda3 (Python 3.7.16)
Simulator Questasim 10.4c (win64).
After executing the make command, a message is displayed, as shown in the screenshot:
![Снимок2](https://user-images.githubusercontent.com/47860047/233655987-66c8be2b-9350-4758-818b-4ab50c38cb83.PNG)

**Comment by marlonjames** [comment]
It appears that questa is not in your path.
