### ISSUE TITLE
Find a solution for sphinx domaintools bugs

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#3314]
Sphinx domaintools (https://github.com/sphinx-contrib/domaintools) seems to be unmaintained and has at least two issues that we stumble across regularly:

* https://github.com/sphinx-contrib/domaintools/pull/13 (patch by @eric-wieser)
* https://github.com/sphinx-contrib/domaintools/pull/7

Since these issues are rather fundamental, I'm wondering if we're close to the only user of sphinx-domaintools? What would be our alternatives?

**Comment by imphil** [comment]
Oh sorry @eric-wieser, I meant to link to https://github.com/sphinx-contrib/domaintools/pull/7. I edited the original issue description.

**Comment by ktbarrett** [comment]
We could make our own Makefile Sphinx domain. The amount of code involved looks to be extremely small. As a first pass we could just use the existing domaintools and makedomain source code with the appropriate patches. If a repo is made in the org, I'll work on setting it up this weekend.

**Comment by imphil** [comment]
Since it's probably a very small sphinx extension we can probably have it simply within the cocotb repository? Looking at domaintools and the makefile domain it seems that we're the only user.

**Comment by imphil** [comment]
If you prefer, I can of course also setup a repo or repos within the cocotb GitHub org, let me know what which ones you'd like me to create.

**Comment by ktbarrett** [comment]
I can do it locally.
