### ISSUE TITLE
Remove unnecessary VPI objects from discovery

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3353]
Remove support for the discovery of initial, always, and function blocks from the VPI, and potentially other interfaces. The discovery of these blocks is of little actual value, especially seeing as variables cannot be declared in initial or always blocks and discovery of function blocks does not allow the discovery of per-instance local variables.

https://github.com/cocotb/cocotb/blob/c28a922da81996d21855568c0f9c6723d772f17c/cocotb/share/lib/vpi/VpiImpl.cpp#L138-L140

Removing these should impact exactly 0 people, but will affect the results of the discovery tests in the regressions.

**Comment by AbdouTharwat** [comment]
Hi @ktbarrett Is there any updates regarding this PR? This one is blocking the integration of new Questa flow scripts
