### ISSUE TITLE
Support equality in BinaryValue with signed integers

### ISSUE THREAD

**Issue by benjamintaitapa** [cocotb/cocotb#3376]
At the moment there is a surprising behaviour that asserting with `assert sig.value == -30` fails even though the value contains `111100010` which is -30 sign-extended to the type width. Looks like the correct approach is `assert sig.value.signed_integer == -30`, but the two levels of indirection feels strange.

Assignment works as expected (likely because you convert under-the-hood), but assertions appear to have been overlooked? If there is a correct way of doing this, it should be documented in the section describing passing and failing tests.

**Comment by ktbarrett** [comment]
This has nothing to do with assertions and everything to do with quality comparisons with `BinaryValue`. An easy work around is you simply convert the BinaryValue to a signed integer before comparing.

```python
assert sig.value.signed_integer == -30
```

In the future, BinaryValue will go away, and the replacement, `LogicArray`, may have better support for automatic type promotion in operators (including equality).
