### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by HamzaShabbir517** [cocotb/cocotb#3389]
Previously i was using cocotb for the hardware simulation and it was working fine. Since i have upgrade my system with Ubuntu 22.04 as an operating system, Python 3.10.12, Cocotb version 1.8 and verilator version 4.106 i am unable to run the simulations. when ever i try to run any example i am receiving the following error
 
![Screenshot from 2023-08-04 18-17-29](https://github.com/cocotb/cocotb/assets/53592110/a3f10ac3-fbb7-4de0-bf84-a5b01bb27876)

Any help regarding this error will be helpful.

Thanks in advance

**Comment by marlonjames** [comment]
Starting with cocotb 1.8, Verilator 5.006 or later is required.
https://docs.cocotb.org/en/stable/simulator_support.html#verilator
