### ISSUE TITLE
cocotb + verilator: No waveform is generated while EXTRA_ARGS is set

### ISSUE THREAD

**Issue by Nado15** [cocotb/cocotb#3395]
![proof](https://github.com/cocotb/cocotb/assets/20690763/b2ba8a01-3972-48ea-9d7e-c87472416b39)
Hi,

I run a simple test case with cocotb and verilator as a simulator and even though I use 

EXTRA_ARGS += --trace --trace-structs

no waveform is generated

Verilator version 5.015 devel
cocotb v1.8.0 
ubuntu 5.4.0-156-generic
python 3.8.10 (system)

Do I miss something?

**Comment by ktbarrett** [comment]
I tested and it worked fine. Make sure to clean the build up and compile from scratch every time you change a make variable. The way verilator works, this is necessary.
