### ISSUE TITLE
PEP 668 compliant systems won't be able to use the current install instructions. 

### ISSUE THREAD

**Issue by forensicgarlic** [cocotb/cocotb#3399]
I think for folks on distros that implement PEP 668, the current `pip install cocotb` instructions aren't going to work because of the `externally-managed-environment` error. I'm on Ubuntu 23.04, Python 3.11 trying to run from the system and getting these issues. 

I think following the instructions in that error message are sufficient for install. 
```
python3 -m venv <venv_path>
<venv_path/bin/pip install cocotb
<venv_path>/bin/cocotb-config --version
```

though i haven't gotten too deep into figuring out where this is going to cause problems if files are expecting system python instead of the venv python, and haven't done any path updating to try to deal with it yet.

**Comment by forensicgarlic** [comment]
next failures seem related to gpi_embed.cpp not detecting venv, and 
```
~/git/cocotb/examples/adder/tests$ make VIRTUAL_ENV=<venv_path>
```
works from there.

**Comment by imphil** [comment]
If you use a venv, you need to activate it (or modify your environment in a way that matches the venv activation: modify PATH, and set VIRTUAL_ENV at least). cocotb works just fine when run in a venv.

Can you be more specific about the error you were seeing initially?

**Comment by forensicgarlic** [comment]
agreed, cocotb does seem to work fine in a venv. The issue is mostly that for some flavors of linux, the install instructions may no longer be sufficient. 

Here's the full text of the error I got when trying to install. 
```
$ pip install cocotb
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

So following the instructions in that error message regarding `venv` is what i needed to do, along with removing older installs from my system (since i had upgraded to ubuntu 23.04 and it had worked in the past) and finding the undocumented `VIRTUAL_ENV` check in gpi_embed.cpp. 

If it'd seem useful, I can do a pull request to the documentation with a note about PEP 668 and some of the steps to take?

**Comment by ktbarrett** [comment]
I['m not sure why it's cocotb's responsibility to handle  and inform users of all the wild and wonderful ways in which Python can be installed to a system. This problem is apparent for every Python project, so I would think anyone stuck on such a system would eventually clue into the fact that virtualenvs must be used and activated to get packages installed and working.

**Comment by imphil** [comment]
An alternative to using a venv would be using "pip --user". Either way, it's a shame that it's almost impossible to give installation instructions that reliably work.

**Comment by imphil** [comment]
@forensicgarlic I'd love to give users reliable, actionable, ane easy advise on how to install cocotb. And as @ktbarrett said, it's a common problem faced by many Python projects. Are you able to come up with such instructions? Or alternatively, can you look around to see what other Python projects are doing?

Ideally we don't have a lengthy decision tree of instructions with tons of ifs and elses, but I'm becoming less and less hopeful on that front.
