### ISSUE TITLE
Incorrect error handling with Xcelium and cocotb 1.8.0

### ISSUE THREAD

**Issue by impinj-tbrown** [cocotb/cocotb#3423]
Since updating to 1.8.0, python errors are not reported correctly if the errors occurs during time=0.
This is what is reported every time, making it very difficulty to find the actual mistake. Note: this did not occur in 1.7.2.
![image](https://github.com/cocotb/cocotb/assets/110573912/a2a38dce-fb22-4413-8feb-60caa1c74357)

If the error occurs after awaiting a coroutine (NOT time=0), the correct error handling occurs.
This is what is reported with the same attribute error after a coroutine is awaited.  
![image](https://github.com/cocotb/cocotb/assets/110573912/86a4eb49-b495-42ff-b32c-b4982b5652ac)

Version : 1.8.0
OS: RedHat Enterprise 7.9
Simulator: Xcelium 21.09-s008
Python 3.10.12 installed via poetry

**Comment by ktbarrett** [comment]
This was fixed on master and also related on the stable/1.8 branch. We intend on releasing a 1.8.1 version with the fix some point soon. Until then, feel free to directly install from either of those branches.
