### ISSUE TITLE
Bug: BinaryValue class returns an empty string for two's complement of 0, whereas the actual two's complement of 0 is 0.

### ISSUE THREAD

**Issue by ShagnikPal** [cocotb/cocotb#3443]
cocotb version: 1.8
Operating system and version: Ubuntu 20.04.5. 64-bit
Simulator and version: ModelSim for Questa-64 version 2022.02
Python version: 3.8. Running via local installed on system

To reproduce, running the following python code with above configurations:
```
from cocotb.binary import BinaryValue, BinaryRepresentation
bv = BinaryValue(value=0, n_bits=8, bigEndian=False, binaryRepresentation=BinaryRepresentation.TWOS_COMPLEMENT)
print("2's complement of 0:{}".format(int(bv.binstr, 2)))
```

Throws an error:
```
    print("2's complement of 0:{}".format(int(bv.binstr, 2)))
ValueError: invalid literal for int() with base 2: '
```

**Comment by ktbarrett** [comment]
BinaryValue is known to have many problems, try using LogicArray instead. It will be the default type of values returned from logic and logic array handles starting in 2.0, which will be the next release.
