### ISSUE TITLE
Documentation: error rendering inheritance diagrams (v1.8.1)

### ISSUE THREAD

**Issue by joaopccarvalho** [cocotb/cocotb#3449]
Diagram images not rendering (https://docs.cocotb.org/en/stable/library_reference.html#simulation-object-handles)

cocotb version: v1.8.1

**Comment by cmarqu** [comment]
Thanks for the report!

The error in the doc build logs is "WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting"
