### ISSUE TITLE
Did not detect Python virtual environment. Using system-wide Python interpreter: Windows(conda)

### ISSUE THREAD

**Issue by thenameisT** [cocotb/cocotb#3454]
I get this error when I run in conda env(but the test run is successful)

```
# Loading C:/Users/anaconda3/envs/env/Lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll
#      -.--ns INFO     gpi                                ..mbed\gpi_embed.cpp:78   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
```

But when I run directly from command prompt in windows 
I get the following error:

```
 Loading C:/Users/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/cocotb/libs/cocotbvpi_modelsim.dll
#      -.--ns ERROR    gpi                                ..s\cocotb_utils.cpp:56   in utils_dyn_open                  Unable to open lib C:\Users\anaconda3\envs\env\python311.dll: The specified module could not be found.
```

Question 1: Why the message _Did not detect Python virtual environment. Using system-wide Python interpreter_ displayed in conda ?
Question 2: What should I do to run cocotb test in Windows command prompt(without using conda)?
PS:(path variable has been set) and I am trying to [extend existing build flow](https://docs.cocotb.org/en/latest/custom_flows.html)

**Comment by ktbarrett** [comment]
1. You aren't running from a virtualenv. This is expected.
2. Does `C:\Users\anaconda3\envs\env\python311.dll` actually exist?

**Comment by thenameisT** [comment]
1. I am using virtual env in anaconda.
2. Yes it exist. 
3. I also created a virtualenv in windows and I am getting the below error
 Loading V:/cocotbenv/Lib/site-packages/cocotb/libs/cocotbvpi_modelsim.dll
#      -.--ns ERROR    gpi                                ..s\cocotb_utils.cpp:56   in utils_dyn_open                  Unable to open lib C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\python311.dll: Access is denied.

**Comment by ktbarrett** [comment]
Conda envs are not the same as other virtual environments. You have a two python environments that are in conflict. In the original comment your cocotb install is in your Python App Store install `C:/Users/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/cocotb/`, but it's trying to load the conda env's libpython `C:\Users\anaconda3\envs\env\python311.dll`. If you set up conda to add it's stuff to the PATH of the system, you've got a conflict. I would reinstall anaconda and *not* select that option (it warns about it for a reason), or just uninstall anaconda.

**Comment by thenameisT** [comment]
It was trying to load conda env's libpython beacuse I had set the LIBPYTHON_LOC=C:\Users\anaconda3\envs\env\python311.dll
Now I have removed it from the path.

I am running in command prompt, this is the error I get
```
Loading C:/Users/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/site-packages/cocotb/libs/cocotbvpi_modelsim.dll
#      -.--ns ERROR    gpi                                ..s\cocotb_utils.cpp:56   in utils_dyn_open                  Unable to open lib C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\python311.dll: Access is denied.
```

**Comment by ktbarrett** [comment]
@mattrfrancis beyond this issue, you won't be able to use 32 bit modelsim with a 64 bit python.

**Comment by mattrfrancis** [comment]
> @mattrfrancis beyond this issue, you won't be able to use 32 bit modelsim with a 64 bit python.

I believe I've set up 32 bit python as per [https://github.com/cocotb/cocotb/wiki/Tier-2-Setup-Instructions#conda-based-installation-all-os](url)

**Comment by pintert3** [comment]
I'm getting this too

**Comment by ktbarrett** [comment]
Have you considered using the Python.org/Chocolately install instead of conda and using the new Python runner rather than Makefiles? This will be the recommendation going forward after the 2.0 release. Windows' various Unix-compat environment has given us so many problems and we really don't want to deal with them anymore.

**Comment by pintert3** [comment]
Haven't yet. Just got to know about this. Didn't know of any Python Runner cause the default installation and quickstart documentation didn't mention them.

**Comment by ktbarrett** [comment]
@pintert3 See https://docs.cocotb.org/en/stable/runner.html.

**Comment by ktbarrett** [comment]
Tracking in #4091.
