### ISSUE TITLE
Thoughts on adding git rev to dev version numbers?

### ISSUE THREAD

**Issue by toddstrader** [cocotb/cocotb#3562]
How would everyone feel about adding `git rev-parse --short HEAD` to `__version__`?  Currently it is `2.0.0.dev0` and I'm not sure what the final `0` is for, but I'm guessing it's to manually increment as one feels like?  What if instead it were `2.0.0.dev-d379318e`?  I'd propose that we build the file on the fly in `setup.py` but only add the git rev when the non-suffixed version (stored as a variable in `setup.py`) includes `dev`.

I can take a stab at this if people are onboard.

**Comment by ktbarrett** [comment]
setuptools-scm did this. But it did a lot more than that, poorly. Maybe you can extract the logic it uses from it. Technically I think the correct version we should be using is `2.0.devN`, but I'd have to check the PEP. I'd like the N incremented for each commit as well.

**Comment by marlonjames** [comment]
I would like this as well.
