### ISSUE TITLE
Signal probing throws ModifiableObject error

### ISSUE THREAD

**Issue by yotarid** [cocotb/cocotb#3589]
Dear cocotb experts,

When running my simulation, I stumble upon the following error 
```
assert dut.axi_mem_rd_strobe_o.value == 1
AssertionError: assert 0 == 1
+  where 0 = ModifiableObject(axi4lite_slave_if.axi_mem_rd_strobe_o).value
+    where ModifiableObject(axi4lite_slave_if.axi_mem_rd_strobe_o) = HierarchyObject(axi4lite_slave_if with definition axi4lite_slave_if
```

This happens when I try to assert that the signal `axi_mem_rd_strobe_o`, defined as an output in my entity `axi4lte_slave_if`, is `high` / equal to `1`. 
Inside my entity architecture, the signal is assigned in a concurrent statement as follows 
```
axi_mem_rd_strobe_o <= slv_reg_rden_s;
```

Can anyone please explain to me why I cannot probe the value of that signal ? And whether there is a possible solution ? 

Information on environment: 
- cocotb-version : `1.8.1`
- operating-system : `CentOS Linux 7`
- simulator : `QuestaSim 2020.4_4`
- python-version : `3.11.5` coming from Anaconda

Many thanks in advance
Younes

**Comment by ktbarrett** [comment]
> ```
> assert dut.axi_mem_rd_strobe_o.value == 1
> AssertionError: assert 0 == 1
> +  where 0 = ModifiableObject(axi4lite_slave_if.axi_mem_rd_strobe_o).value
> +    where ModifiableObject(axi4lite_slave_if.axi_mem_rd_strobe_o) = HierarchyObject(axi4lite_slave_if with definition axi4lite_slave_if
> ```

The important part is `assert 0 == 1`. `dut.axi_mem_rd_strobe_o.value` is `0` when the assert statement runs. Your assert statement failed is the only thing that is happening. The rest is pytest's assertion rewriting telling where the value `0` came from: `where 0 = ModifiableObject(axi4lite_slave_if.axi_mem_rd_strobe_o).value` then `where ModifiableObject(axi4lite_slave_if.axi_mem_rd_strobe_o) = HierarchyObject(axi4lite_slave_if with definition...`, etc. etc.

**Comment by yotarid** [comment]
Indeed ... Thanks for the help and sorry for my noise.
