### ISSUE TITLE
VHPI doesn't take null ranges into account

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3606]
https://github.com/cocotb/cocotb/blob/ee652a27a32c6a0f284c6054a7c07742920fe1a5/src/cocotb/share/lib/vhpi/VhpiCbHdl.cpp#L231-L235

Computing the number of elements using left and right cannot be assumed because of null ranges. `0 downto 7` has a length of 0, but the algorithm above would compute the length as 8.

EDIT: I don't see a way to check direction, but it could be inferred by checking if the range is null using `vhpiIsNullP`. Is there a better way @marlonjames?

**Comment by nickg** [comment]
> 
> EDIT: I don't see a way to check direction, but it could be inferred by checking if the range is null using `vhpiIsNullP`. 

`vhpiIsUpP` gives you the direction.
