### ISSUE TITLE
weird problem about input signals to dut not updating 

### ISSUE THREAD

**Issue by muzafferkal** [cocotb/cocotb#3616]
I'm using cocotb version 1.8.1 with verilator 5.019 devel rev v5.018-40-gc8063e573. This is running on windows WLS with python 3.10.6.

I have a systemverilog dut which has two (among other things) axi-stream like interfaces. My problem is that one of the interfaces works well, where I can do
    dut.wgt_vld.value = 1
    while ...
        dut.wgt_adr.value = 2*row + 1
        await RisingEdge(dut.clk)
etc and I see the values change in the RTL as observed by gtkwave. 
The problem is that the other interface has out_rdy  and out_addr signals and what changes I make to these signals in my cocotb python code doesn't update in the RTL sim. I can set the out_rdy signal at a very time in the sim and get it to be visible in RTL but if I move it to closer to where out_vld is seen high its value doesn't change. Also I can't change the out_addr values. 
I checked the direction of the ports, multiple writers etc. and I can't see anything wrong. I had a systemverilog TB where this worked but I don't want to go back and add all the changes I have done in the python code now.
Any suggestions which might be wrong and/or how to debug this issue?

**Comment by imphil** [comment]
Hi, thanks for giving cocotb a try! Verilator is least supported among all simulators, so it would be great if you can test against another simulator as first step.

To go further here, we would then need the code you're trying to run (both Python and Verilator), ideally a minimal form of it that still shows the problem.
