### ISSUE TITLE
Prefix environment variables that are passed through to simulator with `COCOTB_`

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3644]
I don't so much care about prefixing variables that are used only by the Makefiles or Python runner, but anything needed to cross into cocotb's Pythonland should be prefixed to prevent getting stomped by simulator environment variables and provide an easy way to support passthrough otherwise.

**Comment by cmarqu** [comment]
So these?:
* https://docs.cocotb.org/en/stable/building.html#envvar-TOPLEVEL --> `COCOTB_TOPLEVEL`
* https://docs.cocotb.org/en/stable/building.html#envvar-MODULE --> `COCOTB_MODULE`
* https://docs.cocotb.org/en/stable/building.html#envvar-TESTCASE --> `COCOTB_TESTCASE`
* https://docs.cocotb.org/en/stable/building.html#envvar-COVERAGE --> `COCOTB_USER_COVERAGE` (in analogy to https://docs.cocotb.org/en/stable/building.html#envvar-COCOTB_LIBRARY_COVERAGE)
* https://docs.cocotb.org/en/stable/building.html#envvar-RANDOM_SEED --> `COCOTB_RANDOM_SEED`
