### ISSUE TITLE
Vpi Package: >32 bit parameters are interpreted as Integers

### ISSUE THREAD

**Issue by AndrewNolte** [cocotb/cocotb#3662]
Large parameters are mapped to GPI_INTEGER, which leads to issues when trying to read from them. I think we should check the size of the parameters before assigning to GPI_INTEGER

**Comment by ktbarrett** [comment]
Which simulator does this?

**Comment by AndrewNolte** [comment]
I'm seeing it on verilator, will test on xcelium as well

**Comment by ktbarrett** [comment]
If you write up a test you can open a PR with the test and run it against all the simulators? Even if we have to merge it with everything marked fail, that's still good info.

**Comment by ktbarrett** [comment]
Closed by #3729.
