### ISSUE TITLE
Error regarding no root handle found

### ISSUE THREAD

**Issue by Saikiran196** [cocotb/cocotb#3703]
I am trying to execute Frequency divider using cocotb python testbench. But when i am trying to execute the makefile, I am getting error like No root handle found

**Comment by ktbarrett** [comment]
There is simply not enough information here to attempt to help. Please follow the issues template and include the simulator, simulator version, OS, cocotb version, and Python version.

**Comment by Saikiran196** [comment]
Simulator : modelsim
simulator version : modelsim 10.5
OS : Windows 10
cocotb version : 1.8.1
Python Version : 3.10

**Comment by ktbarrett** [comment]
Are you filling out the `TOPLEVEL` variable with the toplevel module name?
