### ISSUE TITLE
Make `SimFailure` private

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3788]
No reasonable user is going to write tests that are expected to cause the simulator to fail. I feel this is a regression-only feature. I think this will require some refactoring to list what happens when a simulator *does* fail in the results.xml.

The fact this is public provides to users a way to fail the result of the regression by throwing it themselves, or to catch it, which may not work as intended. I don't think we should be providing these implicit behaviors.

**Comment by cmarqu** [comment]
We should rename it to `SimulatorFailure`/`_SimulatorFailure` at the same time.
"Sim" mostly means "simulation" as in "testcase" to me.
