### ISSUE TITLE
Support Pytest Fixtures

### ISSUE THREAD

**Issue by anrusal** [cocotb/cocotb#3811]
Hi all,
I was wondering if there are any plans to provide support for Pytest fixtures as this could be useful providing simulation capabilities to existing tests frameworks based on Pytest.
At present the cocotb decorator @cocotb.test() only allows to provide the dut as input and is not possible to pass any other argument like a fixture to be used inside the test. 
Thanks, Toni

**Comment by ktbarrett** [comment]
That would require us to adapt the whole of pytest into the regression manager. This has been discussed before and is not really possible without extensive changes and breaks. We don't plan on supporting this in the foreseeable future.
