### ISSUE TITLE
Allow Logic for BinaryValue.__eq__() in cocotb 1.8

### ISSUE THREAD

**Issue by wimiko** [cocotb/cocotb#3845]
As BinaryValue is deprecated and will be removed in 2.0, but is is still the return type for handler.value

It would be practical to allow

`dut.mysignal == Logic('X')`

in cocotb 1.8 so we can already stop using BinaryValue and avoid more porting work when 2.0 arrives

**Comment by imphil** [comment]
This has made it into the cocotb 1.9 branch through #3878.
