### ISSUE TITLE
Possible feature request: Define path of simulator binary

### ISSUE THREAD

**Issue by cweickhmann** [cocotb/cocotb#3939]
Using cocotb, I just realised the simulator binary (in my case ghdl) is fixed.
Either it is `/usr/bin/ghdl` or what ever `which ghdl` returns. As far as I can see, simply setting an alias, does not help.

Can the simulator binary path be changed within a cocotb Makefile?

I've compiled ghdl 3.x with certain options and would like to use that on *some* testbenches. Unfortunately, my system comes with an ancient ghdl 1.0 installed under `/usr/bin/ghdl`.

**Comment by ktbarrett** [comment]
There's the `CMD` make variable, but it's not documented because this is not really a feature I see anyone else using. 

> I've compiled ghdl 3.x with certain options and would like to use that on some testbenches.

Why only "some"?
