### ISSUE TITLE
Renamed variable COCOTB_COVERAGE_RCFILE won't have an effect

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#3947]
I think the PR that did the renaming of the COVERAGE_RCFILE variable in the code (#3925) has slightly broken the coverage functionality.
Unless I'm misunderstanding things, we did rely on `coverage.py` to read the original name `COVERAGE_RCFILE` (see https://coverage.readthedocs.io/en/latest/config.html#configuration-reference), which it won't do for `COCOTB_COVERAGE_RCFILE`.

_Originally posted by @cmarqu in https://github.com/cocotb/cocotb/pull/3943#discussion_r1645031484_

**Comment by cmarqu** [comment]
Re-exporting this variable under its original name would help - or we revert the name change.
We should have a comment that explains the fact that it's `coverage.py` which actually does interpret the variable.
We should also have a test for this functionality.

**Comment by teobiton** [comment]
I investigated a bit and there is also the possibility to pass the `config_filepath` as an argument of `coverage.coverage()`, and it will use that. The coverage module only looks at `COVERAGE_RCFILE` if `config_path`  argument of the Coverage class is left to its default value.

**Comment by ktbarrett** [comment]
> I investigated a bit and there is also the possibility to pass the config_filepath as an argument of coverage.coverage(), and it will use that.

I like this option. That should be a simple change, right?
