### ISSUE TITLE
Consider removing data and name attributes of `Event`

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3980]
One can set a data attribute when `set()`ing and can give the Event a name. These features aren't used anywhere in the current tests and is something the user can do with a companion variable fairly easily. Nor is this something that `asyncio` supports.

**Comment by alexforencich** [comment]
This is used extensively in cocotbext-axi.  Deleting it without deprecating it first is a bit rude.

**Comment by ktbarrett** [comment]
1.9 will receive the deprecation. We plan on doing a "here's everything that's deprecated" release of 1.9 to act as a way to know what to change for 2.0 for existing tests.

I think there was a misunderstanding with 1.X that anything in particular was public API because there was no real effort put into separating the interfaces. 2.X+ will be a far more seemless experience for everyone.

**Comment by ktbarrett** [comment]
On second thought, I might reintroduce this. It isn't standing in the way of 2.0 changes. But it will be deprecated.
