### ISSUE TITLE
Could someone remind me: What is an unwatched task?

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#3982]
```
     4.00ns ERROR    ..ponse.<locals>.SeqTest.run_phase Exception raised by this forked coroutine
/Users/raysalemi/venvs/pyuvm_dev/lib/python3.8/site-packages/cocotb/scheduler.py:585: FutureWarning: "Unwatched" tasks that throw exceptions will not cause the test to fail. See issue #2664 for more details.
```

Could someone remind me what an unwatched task is? 

I'm afraid https://github.com/cocotb/cocotb/issues/2664 is a developer conversation and not an explanation.

**Comment by ktbarrett** [comment]
"unwatched" means you aren't awaiting the Task to finish

```python
task = cocotb.start_soon(coro())
await task  # "watching" task
```

Unwatched tasks are tasks that you spin off and never intend to join, this is common with implementing drivers, monitors, etc.

That being said, the behavior is actually changing in the *other* direction now. cocotb 1.9 (releasing sometime next week) should have the truer warning message. In 2.0 tasks created with `cocotb.start_soon` will *always` fail the test if they see an exception and will *never* propagate exceptions. There will be a new mechanism (not yet available on master) if you intend to join tasks and want exception propagation.

**Comment by raysalemi** [comment]
Thanks!
