### ISSUE TITLE
 No warning when driving a value that is already driven by the testbench

### ISSUE THREAD

**Issue by slagernate** [cocotb/cocotb#3998]
It seems like it would be quite useful if, when assigning a value, the test bench would complain if it is already driven by the design, instead of failing silently. E.g.

```
dut.some_value = 1
```

will have no effect if `some_value` is already driven by the testbench.

cocotb version 1.8.1
Ubuntu 23.04
Verilator 5.012
Python 3.11.6

Perhaps there already is a warning for this and I've somehow suppressed / missed it?

**Comment by ktbarrett** [comment]
If you can figure it out, go for it.
