### ISSUE TITLE
Couldn't install cocotb_tools through `pip3 install cocotb`

### ISSUE THREAD

**Issue by AtaraxiaZ** [cocotb/cocotb#4011]
The cocotb version I installed in v1.8.1. The operating system is MacOS ARM64. I installed cocotb through pipx.

**Comment by imphil** [comment]
cocotb_tools isn't part of a stable cocotb release. Refer to the stable documentation at https://docs.cocotb.org/en/stable/ what what's supported in cocotb 1.8.1 (the latest stable version).

Further reading:

* on cocotb_tools: https://github.com/cocotb/cocotb/issues/3809
* If you really used pipx (your description contradicts the title a bit in your issue): https://github.com/cocotb/cocotb/issues/3643
