### ISSUE TITLE
Failed to import libcppyy3_9. Please check that ROOT has been built for Python 3.9 - cocotb error 

### ISSUE THREAD

**Issue by pencils967** [cocotb/cocotb#4064]
Cocotb version - 1.8.1 
python version - python 3.9.18
CERN root version - 6.30.08, GCC 11.4.1 (Red Hat 11.4.1-3), Linux 
operating system - Alma9 

```
#      0.00ns CRITICAL cocotb.regression                  Failed to import module TB_ChannelSignalReco: Failed to import libcppyy3_9. Please check that ROOT has been built for Python 3.9
#      0.00ns INFO     cocotb.regression                  MODULE variable was "TB_ChannelSignalReco"
#      0.00ns INFO     cocotb.regression                  Traceback: 
#      0.00ns INFO     cocotb.regression                  Traceback (most recent call last):
#                                                           File "/root_files_v30.08/install/lib/cppyy/__init__.py", line 60, in <module>
#                                                             importlib.import_module(libcppyy_mod_name)
```

I have all the paths added to the bash_profile. The $echo returns them correctly as well. 
The root version was complied and is compatible with the python version. Wrote a small PyROOT script to check and it worked perfectly. 

Not sure how to resolve this error.

**Comment by ktbarrett** [comment]
I have no idea what cppyy is. This doesn't seem to have anything to do with cocotb, but is a Python environment issue.
