### ISSUE TITLE
QuickStart Example Error

### ISSUE THREAD

**Issue by xiuhu17** [cocotb/cocotb#4073]
* the cocotb version: 1.8.1
* the operating system: Sonoma 14.3
* the simulator: verilator 5.027 devel rev v5.026-75-g0d43c14b9
* the Python version: Python 3.12.4, MiniConda
* part of the log file: unexpected keyword argument 'sources'

When using ```pytest``` for the given QuickStart example of 1.8.1 version, will throw this error. It will be fixed if change to ```verilog_sources = ...``` .

**Comment by ktbarrett** [comment]
The current stable documentation is for cocotb 1.9, not 1.8.1. Use the correct documentation or update your version of cocotb.
