### ISSUE TITLE
failure due to deprecated MODULE in testcase Makefile

### ISSUE THREAD

**Issue by ahmedalsawi** [cocotb/cocotb#4127]
Running `make test` fails due to error in `cocotb/tests/test_cases/issue_253/Makefile` as it uses deprecated MODULE not COCOTB_TEST_MODULE

>         raise RuntimeError(
>                                                         RuntimeError: Environment variable COCOTB_TEST_MODULES, which defines the module(s) to execute, is not defined or empty.
> 

Replacing MODULE with COCOTB_TEST_MODULE works fine

**Comment by ktbarrett** [comment]
Yeah, the regression needs to be updated post-#3925.
