### ISSUE TITLE
Add support for alias'ing sub-handles

### ISSUE THREAD

**Issue by leftink** [cocotb/cocotb#418]
When dealing with long hierarchy paths to signals, there can be a lot of repetitive typing.  It would be nice for handles at any level to support adding an alias.

I saw a post that one could add an alias by modifying the _sub_handles dictionary like below:

``` python
dut._sub_handles["alias1"] = dut.a.b.c   # handle to an integer
dut.alias1 = 5              # 1/3 ways to set the value
dut.alias1 <= 6             # 2/3 ways to set the value
dut.alias1.value = 7        # 3/3 ways to set the value
```

I see two issues with this approach:
1. Allowing the user to modify the underlying dictionary offers no protection of them stomping on an existing alias name, or for that matter, if _discover_all() is called it could overwrite the alias.
2. The other issue is that when "iterating" over all the handles at a level, now the aliases will show up.

Another approach is to set variable to the handle and use the variable:

``` python
alias1 = dut.a.b.c   # handle to an integer
alias1.value = 5     # 1/2 ways to set the value
alias1 <= 6          # 2/2 ways to set the value
```

I see two issues with this approach as well:
1. You lose one of the ways to set the value.  If that way is the way commonly used, errors will happen.
2. This variable as well as other aliases will need to be propagated around the design possibly removing any benefit of creating the aliases.

If the Python handle supported a function, i.e. `add_alias(name, handle)`, then most if not all the issues above are resolved.
1. To prevent stomping on valid handle mappings, store aliases in a separate dictionary that is checked after _sub_handles when getting/setting an attribute.
2.  Don't iterate over the separate dictionary so the aliases don't show up when iterating over the handle.
3. Since the alias will still have a parent handle, all three ways of setting the signal will still be supported.
4. Since the aliases will be packaged with the parent handle, multiple aliases could be create and only the parent handle needs to be passed through the design.

Example:

``` python
dut.add_alias("alias1", dut.a.b.c)
dut.alias1 = 5
```

**Comment by ktbarrett** [comment]
> Another approach is to set variable to the handle and use the variable:
> 
> ```python
> alias1 = dut.a.b.c   # handle to an integer
> alias1.value = 5     # 1/2 ways to set the value
> alias1 <= 6          # 2/2 ways to set the value
> ```
> 
> I see two issues with this approach as well:
> 
> 1. You lose one of the ways to set the value.  If that way is the way commonly used, errors will happen.

Using `__setattr__` to set signals is to be discouraged.

> 2. This variable as well as other aliases will need to be propagated around the design possibly removing any benefit of creating the aliases.

As would the `dut` object if creating aliases.

If you have a collection of handle aliases you want to move around rather than passing them individually, you can encapsulate in a `dict`, `namedtuple`, or `dataclass` and not have to move the `dut` top level object around. This is partially the responsibility of the `Bus` type, no?
