### ISSUE TITLE
Cocotb combined with QuestaSim simulation

### ISSUE THREAD

**Issue by wangyajun001** [cocotb/cocotb#4181]
Hello,
Recently I am using cocotb simulation on an open source code. Taking [`DNPCIe_40G_KU_LL_2QSFP`](https://github.com/corundum/corundum/tree/master/fpga/mqnic/DNPCIe_40G_KU_LL_2QSFP/fpga/tb/fpga_core) as an example, if I directly use the default simulator `icarus` in the Makefile, it can pass. However, after I changed `SIM ?= icarus` to `SIM ?= questa`, an error message was reported. I still can't find out what went wrong. Can you give me an answer? 
Thank you.
![1](https://github.com/user-attachments/assets/1cb5a0d6-3db8-4ef2-baba-e0732b131b46)
![2](https://github.com/user-attachments/assets/19d99967-7eec-4c31-8923-adb06eb1159b)
cocotb: Version: 1.8.1
OS: Ubuntu 22.04
Simulator: Questa Sim2021.2
Python 3.8.10

**Comment by imphil** [comment]
The error messages gives the right hint: at least one bit in the data read from the simulator is "z" (high impedance). Cocotb is unable to silently convert z to an integer value, hence the error message. 

As a fix, you'll need to explicitly resolve all z values, or update the simulation not to have this state. Either way, it's a question about the test itself, and not about cocotb. Please follow up with the test author as necessary.
