### ISSUE TITLE
Request to add `value.hexstr`

### ISSUE THREAD

**Issue by musmuris** [cocotb/cocotb#4229]
In a similar way that `dut.o_value.value.binstr`  would it be possible to add `dut.o_value.value.hexstr` as a convenience to `hex(dut.o_value.value.integer)` ?

**Comment by musmuris** [comment]
Just went to look at the code with a view to making a pull request - but looks like binstr has been deprecated (which given just logging the value did the same anyway). Will hold off for now

**Comment by ktbarrett** [comment]
I think using the builtin `hex()` function does the same thing.

Hmmm... Looks like this could be helped by implementing `__index__` so that `hex(logic_array_value)` works.
