### ISSUE TITLE
Add support for new type of "error", i.e. DataError()

### ISSUE THREAD

**Issue by leftink** [cocotb/cocotb#471]
With the current mechanisms, either the user compares the data and determines how to handle the error or the user leaves that job to the Scoreboard, but even if the Scoreboard is used and configured to not stop on errors, the user has to query the Scoreboard for the test results.

Where this approach starts to breakdown is to potential of having multiple Scoreboards in a design.  An example of this might be a complex protocol that could embed a Scoreboard in the test component to check protocol specific items while leaving actual "data" checking to the Scoreboard instantiated by the user.

My suggestion is to do the following:
1. Create a DataError() object like TestError() and TestFailure(), the use of such an error would be to "yield" the result as opposed to "raising" an error, to allow the scheduler to continue execution.
2. Add configuration to the test decorator to indicate how to handle a data error, i.e. continue or die, and maybe the ability to specify the number of expected data errors.
3. Add a field to the test class to track the number of "errors" reported.
4. Modify the scheduler to report the error to the test, and then depending on test configuration, end the test or return control to the coroutine that yielded the "error".
5. Modify the scoreboard to `yield DataError()` instead of raising a TestFailure.  Support for raising a TestFailure can be maintained for backwards compatibility.
6.  TestSuccess would now be determined by the test having the "expected" number of errors.
7.  Modify the Results reporting to report the number of errors.

One of the nice things about this approach is the user no longer has to query the Scoreboard(s) for the test result.  The test coroutine and complete as normal and rely on the reported data errors to determine pass/fail criteria.

**Comment by ktbarrett** [comment]
I think this is built on the faulty assumption that there should be multiple Scoreboards in a test. There should be one scoreboard and it should be passed around (or someplace global) and all components should register scorers with the scoreboard. This is kind of what the suggestion of the `DataError` is doing anyways; making the scheduler/test into a scoreboard and counting/failing whenever a `DataError` is seen.

I don't think we would accept this change.
