### ISSUE TITLE
Bug in SimBaseLog Initialization

### ISSUE THREAD

**Issue by leftink** [cocotb/cocotb#487]
@stuarthodgson and @chiggs 
I am not sure if this is a bug or not since everything seems to work as it is, but when I was going through the logging code I saw something that didn't seem right to me.

``` python
class SimBaseLog(logging.getLoggerClass()):
    def __init__(self, name):
        #some initialization code
        # ...
        logging.__init__(name)
        self.addHandler(hdlr)
        self.setLevel(logging.NOTSET)
```

Isn't `logging.__init__(name)` incorrect?  Shouldn't that line be `logging.getLoggerClass().__init__(name)`?

**Comment by eric-wieser** [comment]
Yes, this was super broken, and results in this nonsense:
```python
>>> logging
<module 'logging' from 'C:\\...\\Python\\Python38\\lib\\logging\\__init__.py'>
>>> logging.__init__('wat')
>>> logging
<module 'wat' from 'C:\\...\\Python\\Python38\\lib\\logging\\__init__.py'>
```

Fixed in 32a2fed7faee9e066d6c8284da3675b0cfbfdbe5
