### ISSUE TITLE
Hierarchy access for generate statement

### ISSUE THREAD

**Issue by kirknodeng** [cocotb/cocotb#497]
When we instantiate some block with generate statement. 
How to access that hierarchical module?

example) When I want to access "SubBlock[3].u_SubModule.a". 
genvar i;
generate 
  for(i=0;i<5;i=i+1) begin : SubBlock
    SubModule u_SubModule(
       .a(...),
       .b(...),
    );
  end
endgenerate

First, I tried to do this 
RisingEdge(dut.SubBlock[3].u_SubModule.a) -> cocotb can't find SubBlock

and, Second
RisingEdge(dut.u_SubModule.a) -> cocotb find their object. but, which module accessed? 
                                                         I instantiated five modules.

**Comment by leftink** [comment]
The first way should work I believe.  What simulator are you using?

You should try running test_array.  It tests something similar.

**Comment by kirknodeng** [comment]
I tried to running test_array using VCS. It's similar. but, different.

So, I want to make this case test into test_cases. Can I make it? 
It is first time to make test case and push request. Is it okay?

**Comment by ktbarrett** [comment]
If you are still having trouble create a new issue.

**Comment by mattvenn** [comment]
I believe there is still an issue with hierarchy access - please see this MVCE
https://github.com/mattvenn/cocotb-mvce-generate-bug/blob/master/test.py

**Comment by mattvenn** [comment]
This is with icarus 10.3 compiled from source

**Comment by ktbarrett** [comment]
Running with debugging I get [this](https://github.com/cocotb/cocotb/files/5255524/output.log). If I set line 9 to `True`, the test passes and I get [this](https://github.com/cocotb/cocotb/files/5255513/output.log). I'll look into this more later, but there is definitely a problem with the discovery of pseudo-region. Calling in the expert on pseudo-regions @garmin-mjames.

**Comment by ktbarrett** [comment]
I see the problem and I'm astonished that this hasn't been caught before...

When attempting to access `genblk1`, the VPI implementation is unaware that it is a pseudo-region, causing `vpi_handle_by_name` to fail. When iterating over "top" beforehand, the pseudo-region is discovered, created, and cached so that following accesses succeeds. There are a lot of ways to fix this issue, I'm not sure which is best.

I'm starting to think we should be iterating over all related objects, properly creating and caching those related-objects, whenever we access an object. This approach is also the best solution for #1128.

**Comment by garmin-mjames** [comment]
@ktbarrett It might be enough to call `_discover_all` before looking for sub handles.

**Comment by ktbarrett** [comment]
```diff
--- a/cocotb/handle.py
+++ b/cocotb/handle.py
@@ -249,6 +249,11 @@ class HierarchyObject(RegionObject):
         except KeyError:
             pass
 
+        if not self._discovered:
+            self._discover_all()
+
+        return self.__get_sub_handle_by_name(name)
+
         # Cache to avoid a call to the simulator if we already know the name is
         # invalid. Unclear if we care, but we had this before.
         if name in self._invalid_sub_handles:
```

This resolves the problem. If someone wants they could make a PR.

**Comment by garmin-mjames** [comment]
Adding a follow-up note, icarus doesn't reveal `vpiGenScopeArray` through the VPI.
cocotb VPI code around handling pseudo-regions assumes tool support for `vpiGenScopeArray`:

https://github.com/cocotb/cocotb/blob/a77f8b01328a3c233acb98001e6ded551ea02362/cocotb/share/lib/vpi/VpiImpl.cpp#L305

**Comment by ktbarrett** [comment]
Is that a correct assumption? Is Icarus lacking support? Or is it something we need to handle on our end?

**Comment by garmin-mjames** [comment]
icarus supports only `vpiGenScope`, but not the enclosing `vpiGenScopeArray`. I think it's missing functionality from the standard.
Looking at Section 37.83 of the SV standard, it definitely looks like a **gen scope** is always inside a **gen scope array**.

In other simulators I'm pretty sure I've seen an array even if there's only one generate inside. I'll double check though.

**Comment by garmin-mjames** [comment]
The VHPI code does the iteration in `VhpiImpl.cpp` looking for a match and creates the pseudo-region. The comments indicate inconsistency across tools.
We could move the iteration from #2079 out of `handle.py` into the VPI code to match the behavior.
