### ISSUE TITLE
`external` decorator does not work for bound methods anymore (in the same way)

### ISSUE THREAD

**Issue by TL-SjoerdOptLand** [cocotb/cocotb#593]
Since the (good) change of the `external` decorator into a class ([line 306 of decorators.py](https://github.com/potentialventures/cocotb/commit/4252a71a6bf3da8a8fdda58c7fdae08392fc1481#diff-50cba5f5b7403490a756bc38659fdabcR306)), bound methods cannot be called without passing `self` anymore.

This was already taken care for with a magic `__get__` in the `function` and `coroutine` decorators, but just not for the `external` decorator. Would adding this break any existing functionality? Would outfactoring this functionality be worthwile?

@ardwiersma, is this something you could look into?

**Comment by ardwiersma** [comment]
In our case, the decorated function is a class method similar to the example below:
```
class Test(object):
    @cocotb.coroutine
    def test_coro(self):
        ...

    @cocotb.external
    def test_ext(self):
        ...

    @cocotb.test
    def test(self):
        yield self.test_coro()
        yield self.test_ext()
```
So both methods are invoked in the same way and the caller does not need to know whether it is an 'external' or a 'coroutine'

After the recent changes to the cocotb.external mechansim, the call of 'external' method  requires 'self' to be passed as a parameter => `yield self.test_ext(self)`

This is the result of the 'external' decorator type changing from 'function' to 'class'. It issue is resolved by adding the following `__get__` method to the decorator class:
```
   def __get__(self, obj, type=None):
        """Permit the decorator to be used on class methods
            and standalone functions"""
        return self.__class__(self._func.__get__(obj, type))

```
