### ISSUE TITLE
wrong BinaryValue assign/initialization with 3 bits

### ISSUE THREAD

**Issue by Fatsie** [cocotb/cocotb#608]
Following code:
```#!python
    v = BinaryValue(3,3)
    print(v.integer)
```
gives 6 as output
This is under python 3.6

**Comment by wstucker** [comment]
@Fatsie  Your example used the default kwarg of bigEndian=True. I think that setting bigEndian=False would probably give you the expected behavior.

```
be = BinaryValue(3,3)
print("Big Endian", be.integer)
le = BinaryValue(3,3, bigEndian=False)
print("Little Endian", le.integer)
```

Yields:

```
('Big Endian', 6)
('Little Endian', 3)
```

**Comment by Fatsie** [comment]
I can't see this reply online so I reply by email.
OK, but I think this still indicates inconsistency with how bigEndian
value is treated during initialization and conversion back to integer.
greets,Staf.
William Stucker schreef op do 05-04-2018 om 23:15 [+0000]:

**Comment by Fatsie** [comment]
Did some more testing with results given below.

init int | init length | init bigEndian | .binstr | .integer
-------- | ----------- | ------------------ | -------- | ---------
3 | 3 | True | 110 | 6
4 | 3 | True | 100 | 4
3 | 3 | False | 011 | 3
4 | 3 | False | 100 | 4
5 | 5 | True | 10100 | 20
2 | 5 | True | 10000 | 16
5 | 5 | False | 00101 | 5
2 | 5 | False | 00010 | 2

So to me the bug seems to be that conversion from and to integer is wrong for bigEndian=True

**Comment by eric-wieser** [comment]
Seems I re-reported this as #636

**Comment by hashhsah** [comment]
I hit this bug, too. Looking forward to its fix being merged.

In addition, I wonder `if big_endian` could be a class variable so I can set endianess globally in a project. This way, I would still have the option of setting the opposite endianess to a few `BinaryValue` object.

**Comment by juliusbaxter** [comment]
I'd second exposing the BinaryValue default endianess as a global switch which can be set.

I'm not sure how Pythonic that is, or whether this would result in compatibility issues, for example if one module sets it one way, and the next sets it back, would that break functionality in the former?

**Comment by aubindetrez** [comment]
I started working on a fix for this binary.BinaryValue issue regarding BigEndian.

Each BinaryRepresentation needs to be tested/fixed:
- [x] UNSIGNED
- [ ] SIGNED_MAGNITUDE
- [ ] TWOS_COMPLEMENT

With more testing we may find other issue with that file...
I am thinking about openning a PR when every BinaryRepresentations are tested.

**Comment by imphil** [comment]
@aubindetrez I know @ktbarrett has been thinking about BinaryValue a lot, but I think nobody ever found the time to push it through completely. Would you be interested in spending a bit time on that? It's not a 1 day-project, but could be quite rewarding I think. Let me know!

**Comment by aubindetrez** [comment]
@imphil Yes I can work on it.

If BinaryValue has to stay around for compatibility reason I think it is worth fixing what it really wrong/broken.
Meanwhile maybe we can flag it as 'deprecated' and propose a replacement? (like the mentioned `cocotb.types.LogicArray`)

**Comment by ktbarrett** [comment]
1.7 will be released soon. Then I think we should start breaking things wherever we see fit.

**Comment by ktbarrett** [comment]
BinaryValue is dead.
