### ISSUE TITLE
Basic support for coverage collection

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#64]
We want a base class to help with collecting transaction level coverage.  Base class will define a collect(transaction) method which will collect various metrics from a particular transaction type.

The collect(transaction) should call super().collect(transaction) right the way up until we get to the base Coverage class which will be responsible for collecting common metrics (transaction length, time-based statistics etc).

We probably also want to provide some common helpers for performing binning/histograms etc. or select a suitable 3rd party library like numpy.

**Comment by ktbarrett** [comment]
This functionality lays outside of the scope of cocotb and is already handled well by an [extension](https://github.com/mciepluc/cocotb-coverage). Handing UCDB dumps and merging is also out of scope.
