### ISSUE TITLE
Provide "COCOTB_SIM_DEBUG" Makefile variable

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#669]
For the kind of debugging work in #639, it would be good to have a documented Makefile variable like ``COCOTB_SIM_DEBUG`` which would switch options like Cadence Incisive/Xcelium's ``-plinowarn`` and ``-pliverbose``.
Does anyone know examples of such switches for other simulators?

Example code:
```
ifeq ($(COCOTB_SIM_DEBUG),1)
    EXTRA_ARGS += -pliverbose
    EXTRA_ARGS += -messages
else
    EXTRA_ARGS += -plinowarn
endif
```

**Comment by cmarqu** [comment]
This is loosely related to #168.

**Comment by cmarqu** [comment]
We should also merge ``VERILATOR_SIM_DEBUG`` and ``COCOTB_NVC_TRACE`` into this.

**Comment by cmarqu** [comment]
The documentation should make clear that these are simulator options, not options for either cocotb's C/C++ code nor the log level for the logging module.

**Comment by cmarqu** [comment]
An alternative would be to not have this variable at all but just add examples of e.g. additional ``EXTRA_ARGS`` to the documentation.

**Comment by ktbarrett** [comment]
My opinion is if using these options is common, and beginners would benefit from using them, they should be separate variables and documented well. I think a "debug" variable that "does the right thing" for each simulator falls into that case.

**Comment by cmarqu** [comment]
@wallento What do you think about the idea of throwing together ``VERILATOR_SIM_DEBUG`` and ``VERILATOR_TRACE`` under ``COCOTB_SIM_DEBUG``?

**Comment by cmarqu** [comment]
Closing as we want to get rid of as many variables as possible, see #1495.
