### ISSUE TITLE
Coverity scan not run since 2015

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#675]
The Coverity scan (linked to from the README) at https://scan.coverity.com/projects/cocotb has not run since 2015.

**Comment by imphil** [comment]
... and since coverity is now Synopsys and broken (https://community.synopsys.com/s/article/Coverity-Scan-Update) I'm just going to remove it for now. I don't expect Synopsys to restore this service any time soon.

**Comment by cmarqu** [comment]
It looks like they are up again: https://community.synopsys.com/s/coverity-scan-status

**Comment by imphil** [comment]
Ah, it's not worth it. There are more useful techniques these days.
