### ISSUE TITLE
Switch from property() to @property syntax

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#719]
Since Python 2.6 the @property/@x.setter syntax is supported, and gives a cleaner syntax than `property()`. Convert existing uses of `property()` to the newer syntax. 

This requires figuring out what to do with the existing setters and getter functions, which are often public (i.e. set_x() and get_x()). If existing code depends on these, we probably should keep compat wrappers and issue a deprecation warning.

**Comment by eric-wieser** [comment]
> we probably should keep compat wrappers

An easy trick for this is
```python
@property
def my_prop(self):
    ...

@my_prop.setter
def my_prop(self, value):
    ...

# aliases for compatibility
set_my_prop = my_prop.fset
get_my_prop = my_prop.fset
```

**Comment by eric-wieser** [comment]
Ah, not addressed by gh-1497: Deprecating these. I'll open a new issue.
