### ISSUE TITLE
"undefined symbol: _Py_TrueStruct" on Python 3.6+

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#728]
cocotb is broken is Python 3.6 and 3.7:

~~~
vvp -M /home/travis/build/potentialventures/cocotb/build/libs/x86_64 -m gpivpi sim_build/sim.vvp   
gpivpi:`/home/travis/build/potentialventures/cocotb/build/libs/x86_64/gpivpi.vpl' failed to open using dlopen() because:
    /home/travis/build/potentialventures/cocotb/build/libs/x86_64/libgpilog.so: undefined symbol: _Py_TrueStruct.
~~~

A full log is available at https://travis-ci.org/potentialventures/cocotb/jobs/468756352 (that's test for a new CI configuration, so don't worry about anything else in this run failing)

**Comment by mciepluc** [comment]
Isn't it the problem?
```
1500 pyenv: python3.6-config: command not found
1501
1502 The `python3.6-config' command exists in these Python versions:
1503  3.6
1504  3.6.7
```

**Comment by imphil** [comment]
Still looking into it, the Makefiles have a lot of duct tape in various places, some of  which is essential, some of which seems to work around bugs somewhere else.

**Comment by eric-wieser** [comment]
@imphil: can this be closed?

**Comment by imphil** [comment]
I'm pretty sure it can. Thanks.
