### ISSUE TITLE
Readthedocs commit hook broken

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#736]
According to https://readthedocs.org/projects/cocotb/builds/ the documentation isn't getting updated with the latest commits. Possibly the GitHub service deprecation is playing a role here?

@stuarthodgson or @chiggs could you have a look what's going on there? If you want me to have a look please enable the user 'imphil' in the settings for backend access on RTD.

**Comment by imphil** [comment]
Now that #740 has landed the RTD setup needs a small change. If not already done, please check in the settings that the build dependencies are loaded from `documentation/requirements.txt` (it's a setting in https://readthedocs.org/dashboard/cocotb/advanced/)

@chiggs please let me know if something needs changing on the code side.

**Comment by cmarqu** [comment]
Should this be a blocker for the 1.1 release?

**Comment by imphil** [comment]
no

**Comment by imphil** [comment]
@stuarthodgson any update on this?

**Comment by imphil** [comment]
The RTD configuration is now fixed, but the commit hook is still broken. I'll let you know once that's fixed.

**Comment by themperek** [comment]
@imphil It seems to work now?

**Comment by imphil** [comment]
Fixed now after repository moved.
