### ISSUE TITLE
Handle X values in BinaryValue()

### ISSUE THREAD

**Issue by Matthewar** [cocotb/cocotb#765]
Continuing from #750 - need to add handling of X values in the following functions in `BinaryValue()` class:
- `__iand__`
- `__ixor__`
- `__ior__`
- `__hex__`
- `__oct__`

**Comment by eric-wieser** [comment]
In my opinion, the `__iop__` overloads are a mistake, and we should not have added them in the first place.

The problem they have is something like:
```
a = BinaryValue(1)
b = a
a += 1
assert b.integer == 2 
assert b.integer == 1   # fails if we implement __iadd__, passes if we don't
```

Regarding `__hex__` and `__oct__` - these methods are removed in python 3, and python 2 is EOL at the end of the year - so it may not be worth spending the time to implement them.

**Comment by ktbarrett** [comment]
BinaryValue was replaced with LogicArray and it should not have issues with Xs or Zs in bitwise logic operators.
