### ISSUE TITLE
Doxygen annotation in C code incomplete

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#8]
Some of the C files need tidying up.

**Comment by themperek** [comment]
@cmarqu Can this be closed?

**Comment by cmarqu** [comment]
No, there is barely anything documented in Doxygen format in the non-Python files.

**Comment by ktbarrett** [comment]
I will complete the documentation of the GPI once all the libraries are merged (#2274).

**Comment by ktbarrett** [comment]
We decided to pare down the C documentation to just the GPI (#2274), and that is now down.
