### ISSUE TITLE
COCOTB_ANSI_OUTPUT=1 broken

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#809]
@Matthewar https://github.com/potentialventures/cocotb/commit/5c399d9a7a2fe092e8ee9a3fe92e4daa6b34afd9 has broken usage of ``COCOTB_ANSI_OUTPUT=1``.
I have suggested a fix there as a comment.

**Comment by cmarqu** [comment]
Related: https://bixense.com/clicolors/

**Comment by eric-wieser** [comment]
The same change also broke setting it to 0
