### ISSUE TITLE
Remove FIXMEs from docstrings

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#811]
In PR #798/https://github.com/potentialventures/cocotb/pull/798/commits/1cfeeb02472fb0d33a1a04ef521703e55f67a429, I introduced some FIXMEs in docstring for methods in ``triggers.py`` (https://github.com/potentialventures/cocotb/blob/master/cocotb/triggers.py).
Someone knowledgeable should properly document these methods.

**Comment by eric-wieser** [comment]
Easy documentation for `prime`: "Don't call this in your own code, this is for internal by the scheduler"

**Comment by cmarqu** [comment]
Okay :) Internal enough so that we should rename this to ``_prime()``?

**Comment by eric-wieser** [comment]
Possibly. `prime` is public API if you're writing your own scheduler :)

**Comment by cmarqu** [comment]
This is fixed now.
