### ISSUE TITLE
b2b1ddb0ecdc3a89b2be4718e779bf4ad2e2cac7 associated USER_DIR problem

### ISSUE THREAD

**Issue by lcapossio** [cocotb/cocotb#816]
Commit b2b1ddb0ecdc3a89b2be4718e779bf4ad2e2cac7 broke my modelsim runs. It seems if I make USER_DIR=$(SIM_ROOT) it fixes it. The problem is associated with it trying to make some symbolic links and getting protocol error.
If I use USER_DIR=PWD (where my user makefile resides) then I get the error: `Assembler messages:
Fatal error: can't create build/obj/i686/cocotb_utils.o: No such file or directory`

Found the failing commit using `git bisect`

Haven't tried other simulators.

**Comment by themperek** [comment]
This should not happen anymore. If does please reopen.
