### ISSUE TITLE
function decorator doesn't support being called concurrently

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#827]
Issue seems to be here:

https://github.com/potentialventures/cocotb/blob/8cb1e9eb2269428ae476475927eb78dbf09f7020/cocotb/decorators.py#L304-L310

Basically, instead of `self._event` it should be `_event` (not an instance variable).

For example, let's say we have multiple threads trying to share a single wrapped function (e.g. accessing a bus). When the first thread begins it will initialize the `self._event` and then go on its merry way. It will yield some time after `execute_function` is run and the `event.result` is set. When the next thread comes in, it will reinitialize `self._event` back to None. When the first guy gets control again, it looks as if the return value is None.

**Comment by ktbarrett** [comment]
This doesn't seem to be an issue anymore.

https://github.com/cocotb/cocotb/blob/a9cd7ad2625cd8cbfcde3fb5959fb7316b33b4a2/cocotb/decorators.py#L396-L397
https://github.com/cocotb/cocotb/blob/a9cd7ad2625cd8cbfcde3fb5959fb7316b33b4a2/cocotb/scheduler.py#L574-L590
