### ISSUE TITLE
Quick Reference Card/Cheat Sheet

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb#835]
We should have a one-page quick reference card in the style of http://docs.sphinxdocs.com/en/latest/cheatsheet.html and http://www.tcnj.edu/~hernande/r/VHDL_QRC__01.pdf etc.

Topics:
* how to assign/read/print value in different formats
* X/Z handling, ``BinaryValue``
* yield
* fork/join/kill a coroutine
* do checks
* finish test
* ...

(please suggest more below).

The card should show which imports are needed for each item.

**Comment by pwiecha** [comment]
I think a good start would be to reuse what Luke has done for Orconf 2018 (with his permission ofc).
https://github.com/lukedarnell/cocotb/tree/master/tests/test_cases/orconf2018

**Comment by ktbarrett** [comment]
@cmarqu this closed right?
