### ISSUE TITLE
Document using cocotb installed as Python package

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#837]
After #836 goes in the only way of installing and the preferred way of using cocotb is through a Python package. We need to have documentation for that.

**Comment by cmarqu** [comment]
We should also mention how to do development work.
Is https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs the way to go, for instance?

**Comment by imphil** [comment]
`pip install --user -e .` works in a git checkout without root permissions

**Comment by themperek** [comment]
`pip install develop` should work also

**Comment by imphil** [comment]
That's now part of the documentation.
