### ISSUE TITLE
Make AXI bus driver/monitor an extension

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#863]
With cocotb installable as Python package now we want to explore moving the bus support components into extensions of cocotb. Note that these extensions could live in the cocotb repo, we just need to find a good place for them, but they should create a separate `cocotb-bus-axi` (or similar) package.

The starting point for this work is the AXI support code in this repo, and the following PRs which improve it:
- #553
- #550

**Comment by cospan** [comment]
Should I hold off on updating my pull request until these new extensions are sorted out?

**Comment by ktbarrett** [comment]
Has been moved to cocotb-bus.
