### ISSUE TITLE
Assigning Python ints to signals >32 bits

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#913]
If I assign a signed value to a signal larger than 32 bits wide, cocotb attempts to convert the int into an unsigned little-endian BinaryValue before assigning the value ([code](https://github.com/potentialventures/cocotb/blob/master/cocotb/handle.py#L592)). When it receives my negative value, the `_convert_to_unsigned` method fails and gives me a totally useless stacktrace. I know to look for this now, but wasted my time until I figured this out; and lucky for me I could, others may not be so lucky.

This convenience conversion makes a poor assumption rather than informing the user it doesn't have enough information to continue. This is bad coding practice. Instead, it might be better to give a warning or throw an error stating that you cannot assign Python ints to signals greater than 32 bit wide, but instead it will only take a BinaryValue for such signals.

```python
width = len(dut.data)   # dut.data begin a 36 bit width sfixed
for i in range(n):
    yield RisingEdge(dut.clk)
    dut.data <= randint(-(2**(width-1)), (2**(width-1))-1)
```

**Comment by elgorwi** [comment]
Fixed by #2316
