### ISSUE TITLE
cocotb.hook does not do anything unless in a module present in COCOTB_HOOKS

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#920]
Marking a function with `@cocotb.hook` is insufficient for it to do anything - you also have to set the `COCOTB_HOOKS` environment variable to contain the module name where the decorated function resides.

Either we should document this, or we should just remove `cocotb.hook`. None of our tests test `cocotb.hook`. Is anyone using it?

**Comment by imphil** [comment]
The hooks functionality was added in https://github.com/potentialventures/cocotb/pull/565 by @stuarthodgson and @chiggs. So it's most likely used or has been used by them. There's a tiny bit of documentation at https://github.com/potentialventures/cocotb/blob/b6f24c142b14ade52a99e8c8c3d2fd46d49a9e77/cocotb/__init__.py#L113-L114.

@stuarthodgson @chiggs 
- Are you using cocotb.hook() at the moment and is it still useful to you?
- Can you outline a quick use case?

**Comment by stuarthodgson** [comment]
It is used by others are organisation so please don't go removing it. I'll try and dignup some documentation for it buts it's a bit esoteric.

**Comment by imphil** [comment]
Thanks @stuarthodgson. A use case would be nice to make sure we can add tests to ensure it doesn't get broken.

**Comment by stuarthodgson** [comment]
I'm backtracking on this. It can be killed with great predudice.
