### ISSUE TITLE
coroutines marked with cocotb.hook only run during the first test

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#921]
```python
@cocotb.test()
def test_a(dut):
    yield Timer(3)

@cocotb.test()
def test_b(dut):
    yield Timer(3)

@cocotb.hook()
def the_hook(dut):
    while True:
        print("running")
        yield Timer(1)
```

If `COCOTB_HOOKS` is set appropriately (#920), this prints "running" three times during the first test, and then never prints it again.

This is due to the scheduler killing all pending coroutines between each test.

**Comment by ktbarrett** [comment]
Hooks are deprecated as of #2201.
