### ISSUE TITLE
Recommend using latest Python 3 for performance reasons

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#965]
#961 has discovered that Python 3.5 is slower than Python 3.7. It has also uncovered that Python 2.7 is slower than Python 3.7, but faster than Python 3.5.

We should:
- Check the performance of a larger testbench for Python 2.7, 3.5, 3.6 and 3.7
- Formulate recommendations/expectations based on these observations
- Add them to the documentation.

**Comment by cmarqu** [comment]
This is done now.
